

#FUNCTION DECLARE

In [ ]:
import os
import requests


def download_dosm_xlsx(json_url, output_dir="./dosm_xlsx_downloads"):
    """Downloads ONLY .xlsx / .xls files from an OpenDOSM Next.js JSON endpoint.

    Parameters:
        json_url (str): The _next/data JSON endpoint URL from browser Network
        tab.
        output_dir (str): Local directory path to save downloaded Excel files.
    """
    os.makedirs(output_dir, exist_ok=True)

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Referer": "https://open.dosm.gov.my/",
    }

    print(f"Fetching JSON payload from:\n{json_url}\n")
    response = requests.get(json_url, headers=headers)

    if response.status_code != 200:
        print(
            f"❌ Failed to fetch JSON payload. HTTP Status Code: {response.status_code}"
        )
        return

    data = response.json()

    # Recursive search restricted STRICTLY to .xlsx / .xls file extensions
    def extract_excel_urls(item):
        urls = []
        if isinstance(item, dict):
            for value in item.values():
                urls.extend(extract_excel_urls(value))
        elif isinstance(item, list):
            for elem in item:
                urls.extend(extract_excel_urls(elem))
        elif isinstance(item, str):
            item_lower = item.lower().split("?")[0]
            # Strict filter: Only download Excel spreadsheets
            if item_lower.endswith(".xlsx") or item_lower.endswith(".xls"):
                if item.startswith("http") or item.startswith("/"):
                    urls.append(item)
        return urls

    file_links = list(set(extract_excel_urls(data)))

    if not file_links:
        print("⚠️ No .xlsx / .xls files found in this JSON payload.")
        return

    print(f"✅ Found {len(file_links)} Excel file(s):")
    for link in file_links:
        print(f"  - {link}")
    print("-" * 60)

    # Download loop
    for idx, file_url in enumerate(file_links, 1):
        if file_url.startswith("/"):
            file_url = f"https://open.dosm.gov.my{file_url}"

        file_name = file_url.split("/")[-1].split("?")[0]
        save_path = os.path.join(output_dir, file_name)

        print(f"[{idx}/{len(file_links)}] Downloading: {file_name}...")
        file_res = requests.get(file_url, headers=headers, stream=True)

        if file_res.status_code == 200:
            with open(save_path, "wb") as f:
                for chunk in file_res.iter_content(chunk_size=8192):
                    f.write(chunk)
            print(f"    ✔ Saved to: {save_path}")
        else:
            print(
                f"    ❌ Download failed (HTTP Status: {file_res.status_code})"
            )

    print(f"\n🎉 Done! All Excel files saved in '{output_dir}'.\n")

#DOWNLOAD scraping

In [ ]:
# =========================================================
# 🔄 REUSE THIS BLOCK MULTIPLE TIMES FOR DIFFERENT PAGES
# =========================================================

# --- Domestic Tourism 2025 ---
URL_1 = "https://open.dosm.gov.my/_next/data/LfTEis7GeaBsN5mtmQeor/en-GB/publications/tourism_domestic_annual_2025.json?page=1&search=tourism&pub_id=tourism_domestic_annual_2025"
download_dosm_xlsx(json_url=URL_1, output_dir="./water")


# --- Q1 Domestic Tourism 2026 ---
URL_2 = "https://open.dosm.gov.my/_next/data/LfTEis7GeaBsN5mtmQeor/en-GB/publications/tourism_domestic_2026-q1.json?page=1&search=tourism&pub_id=tourism_domestic_2026-q1"
download_dosm_xlsx(json_url=URL_2, output_dir="./water")


# --- 2024 TSA ---
URL_3 = "https://open.dosm.gov.my/_next/data/LfTEis7GeaBsN5mtmQeor/en-GB/publications/tourism_2024.json?page=1&search=tourism&pub_id=tourism_2024"
download_dosm_xlsx(json_url=URL_3, output_dir="./water")

# ---  ---
# URL_4 = "YOUR_THIRD_JSON_URL_HERE"
# download_dosm_xlsx(json_url=URL_4, output_dir="./water")

Fetching JSON payload from:
https://open.dosm.gov.my/_next/data/LfTEis7GeaBsN5mtmQeor/en-GB/publications/tourism_domestic_annual_2025.json?page=1&search=tourism&pub_id=tourism_domestic_annual_2025

✅ Found 1 Excel file(s):
  - https://storage.dosm.gov.my/tourism/tourism_domestic_2025.xlsx
------------------------------------------------------------
[1/1] Downloading: tourism_domestic_2025.xlsx...
    ✔ Saved to: ./water/tourism_domestic_2025.xlsx

🎉 Done! All Excel files saved in './water'.

Fetching JSON payload from:
https://open.dosm.gov.my/_next/data/LfTEis7GeaBsN5mtmQeor/en-GB/publications/tourism_domestic_2026-q1.json?page=1&search=tourism&pub_id=tourism_domestic_2026-q1

✅ Found 1 Excel file(s):
  - https://storage.dosm.gov.my/tourism/tourism_domestic_2026-q1.xlsx
------------------------------------------------------------
[1/1] Downloading: tourism_domestic_2026-q1.xlsx...
    ✔ Saved to: ./water/tourism_domestic_2026-q1.xlsx

🎉 Done! All Excel files saved in './water'.

Fetching JSON payload from:
https://open.dosm.gov.my/_next/data/LfTEis7GeaBsN5mtmQeor/en-GB/publications/tourism_2024.json?page=1&search=tourism&pub_id=tourism_2024

✅ Found 1 Excel file(s):
  - https://storage.dosm.gov.my/tourism/tourism_2024.xlsx
------------------------------------------------------------
[1/1] Downloading: tourism_2024.xlsx...
    ✔ Saved to: ./water/tourism_2024.xlsx

🎉 Done! All Excel files saved in './water'.

#CLEANED tourist 2025 data; (2018-2025); State

In [ ]:
import pandas as pd
import os

file_path = './water/tourism_domestic_2025.xlsx'

# --- Clean Sheet 1 (Key Statistics) ---
df_s1_raw = pd.read_excel(file_path, sheet_name='1')
years_s1 = [int(y) for y in df_s1_raw.iloc[2, 2:].values]
metrics_s1 = (
    df_s1_raw.iloc[[5, 6, 7, 8, 9, 11, 13, 15], 0]
    .apply(lambda x: str(x).split('\n')[1].strip() if '\n' in str(x) else str(x).strip())
    .values
)
data_s1 = df_s1_raw.iloc[[5, 6, 7, 8, 9, 11, 13, 15], 2:].values
df_sheet1_clean = pd.DataFrame(data_s1, index=metrics_s1, columns=years_s1)

# --- Clean Sheet 8B (Top Districts) ---
df_s8b_raw = pd.read_excel(file_path, sheet_name='8B')
df_sheet8b_clean = df_s8b_raw.iloc[4:10, [1, 2]].copy()
df_sheet8b_clean.columns = ['State', 'Top_5_Districts']
df_sheet8b_clean['State'] = df_sheet8b_clean['State'].str.replace('\n', '').str.strip()
df_sheet8b_clean['Top_5_Districts'] = df_sheet8b_clean['Top_5_Districts'].str.replace('\n', ', ').str.strip(', ')

# --- Clean Sheet 9 (State Visitors) ---
df_s9_raw = pd.read_excel(file_path, sheet_name='9')
years_s9 = [int(y) for y in df_s9_raw.iloc[3, 1:9].values]
df_sheet9_clean = df_s9_raw.iloc[5:21, [0] + list(range(1, 9))].copy()
df_sheet9_clean.columns = ['State'] + years_s9
df_sheet9_clean['State'] = df_sheet9_clean['State'].str.strip()

print("--- Sheet 1: Key Statistics ---")
display(df_sheet1_clean)
print("\n--- Sheet 8B: Top Districts ---")
display(df_sheet8b_clean)
print("\n--- Sheet 9: State Visitors ---")
display(df_sheet9_clean)

--- Sheet 1: Key Statistics ---

,2018,2019,2020,2021,2022,2023,2024,2025
Tourism Expenditure (RM million),92561.341706,103183.759714,40424.334334,18410.193742,64080.299582,84932.125000,106746.111050,121280.623042
Domestic Visitors (RM million),82741.382549,92638.159000,38634.646976,17450.979950,59216.955871,78676.422000,98446.228495,112080.740487
Visited Households (RM million),9819.959157,10545.602000,1789.687358,959.213792,4863.343711,6255.703000,8299.882555,9199.882555
Annual Growth Rate (%),11.381991,11.476085,-60.822968,-54.457645,248.069664,32.540150,25.684022,13.615964
Domestic Visitors ('000),221272.480734,239120.865665,131660.150788,65975.955000,171602.963000,213743.544000,260125.842000,290064.703712
Tourism Trips ('000),302414.636522,332378.003274,146990.043575,72398.831000,207785.257000,241474.125000,297853.174000,332215.028000
Average Length of Stay,2.444800,2.520000,1.930000,2.185110,2.546765,2.445889,2.492058,2.555495
Average Expenditure per Trip (RM),306.072260,310.000000,275.000000,254.288550,308.396758,351.723498,358.385004,365.066637

--- Sheet 8B: Top Districts ---

             State                                    Top_5_Districts
4            Johor  Johor Bahru, Batu Pahat, Muar, Kota Tinggi, Se...
5            Kedah    Kota Setar, Langkawi, Kuala Muda, Baling, Kulim
6         Kelantan  Kota Bharu, Bachok, Pasir Mas, Pasir Puteh, Ta...
7           Melaka                   Melaka Tengah, Alor Gajah, Jasin
8  Negeri Sembilan  Seremban, Port Dickson, Tampin, Kuala Pilah, J...
9           Pahang  Kuantan, Bentong, Cameron Highlands, Rompin, T...

--- Sheet 9: State Visitors ---

,State,2018,2019,2020,2021,2022,2023,2024,2025
5,Johor,13487.237912,14274.0,7243.0,3657.550,12376.202,15804.890,17138.338000,18196.973000
6,Kedah,14480.018396,14831.0,10108.0,4023.002,11186.197,13444.055,14651.487954,15607.884000
7,Kelantan,9846.123436,10986.0,6058.0,1920.930,6627.155,7549.370,10514.411000,12062.016000
8,Melaka,13122.604163,13979.0,7275.0,3878.140,11757.166,15558.661,19128.405000,20832.201530
9,Negeri Sembilan,12802.118906,13303.0,7918.0,5485.170,11490.144,14959.470,17784.532000,19356.545000
10,Pahang,18111.356576,18498.0,9905.0,3404.772,13188.959,16455.567,20173.876000,23161.166000
11,Pulau Pinang,14450.491191,15411.0,8929.0,5060.864,10002.735,13127.587,16604.803000,17717.979000
12,Perak,17553.161206,21070.0,13173.0,4489.273,14566.727,17107.518,21776.217000,23642.055000
13,Perlis,2155.507903,2088.0,1193.0,406.796,1669.175,1950.771,3225.428000,3755.682000
14,Selangor,30179.047204,33589.0,19715.0,10211.580,21989.558,27579.478,34460.828046,36376.442000
15,Terengganu,13742.366364,14158.0,7420.0,3719.052,10233.282,11760.516,14460.728000,15462.278000
16,Sabah,20359.881091,22035.0,10337.0,3815.016,12589.005,16080.074,20591.813000,22361.168000
17,Sarawak,19380.230199,19793.0,9393.0,6510.900,15464.621,17901.190,19625.552000,22721.527000
18,W.P. Kuala Lumpur,19165.497171,22633.0,12435.0,9116.005,16912.534,22232.643,26982.957000,35059.933182
19,W.P. Labuan,544.932022,524.0,107.0,53.899,243.695,331.360,449.630000,604.370000
20,W.P. Putrajaya,1891.906993,1949.0,451.0,223.006,1305.808,1900.379,2556.836000,3146.484000

#READABLE tourist 2026 Q1; (2012-2023); National

In [ ]:
import pandas as pd

file_path = './water/tourism_domestic_2026-q1.xlsx'

# Load the raw data
df_raw = pd.read_excel(file_path)

# The actual headers are in row 4 (index 4 in the raw load)
# We extract them and clean the column names
new_header = df_raw.iloc[4]
df_clean = df_raw.iloc[5:].copy()
df_clean.columns = new_header

# Optional: Clean up bilingual column names if they are too long
# df_clean.columns = ['Year', 'Quarter', 'Domestic Visitors', 'QoQ_Visitors', 'YoY_Visitors', 'Domestic Tourists', 'QoQ_Tourists', 'YoY_Tourists', 'Total Expenditure', 'QoQ_Expenditure', 'YoY_Expenditure']

# Reset index for a clean look
df_clean = df_clean.reset_index(drop=True)

# Remove rows that are completely empty (if any)
df_clean = df_clean.dropna(how='all')

# Show the whole content
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
display(df_clean)

4,Tahun,Suku Tahun,Bil. Pelawat Domestik,QoQ,YoY,Bil. Pelancong Domestik,QoQ,YoY,Jumlah Perbelanjaan Pelancongan,QoQ,YoY
0,Year,Quarter,No. of Domestic Visitors,NaN,NaN,No. of Domestic Tourists,NaN,NaN,Total Tourism Expenditure,NaN,NaN
1,NaN,NaN,('000),NaN,%,('000),NaN,%,(RM juta/ \nRM million),NaN,%
4,2012,NaN,141433,NaN,NaN,NaN,NaN,NaN,47778,NaN,NaN
5,2013,NaN,152875,NaN,8.09005,NaN,NaN,NaN,54016,NaN,13.056218
6,2014,NaN,169282,NaN,10.732298,NaN,NaN,NaN,62151,NaN,15.060352
7,2015,NaN,176936,NaN,4.521449,NaN,NaN,NaN,67842,NaN,9.156731
8,2016,NaN,189253,NaN,6.961274,NaN,NaN,NaN,74773,NaN,10.216385
9,2017,NaN,205408,NaN,8.536192,NaN,NaN,NaN,83103,NaN,11.140385
10,2018,NaN,221272,NaN,7.723166,NaN,NaN,NaN,92561,NaN,11.381057
11,2019,NaN,239121,NaN,8.066543,NaN,NaN,NaN,103184,NaN,11.476756
12,2020,NaN,131660,NaN,-44.940009,NaN,NaN,NaN,40424,NaN,-60.823383
14,2021,NaN,65975.937177,NaN,-49.88922,NaN,NaN,NaN,18410,NaN,-54.457748
15,NaN,1,14154.379396,-57.2,-69.630713,NaN,NaN,NaN,3968.667337,-54.2,-73.3
16,NaN,2,11082.090476,-21.705571,-35.639629,NaN,NaN,NaN,2160.853527,-45.552163,-53.9
17,NaN,3,13469.917866,21.546723,-61.273755,NaN,NaN,NaN,3206.480409,48.389531,-73.7
18,NaN,4,27269.549439,102.447778,-17.493536,NaN,NaN,NaN,9074.192469,182.995413,4.7
20,2022,NaN,171602.966,NaN,160.099323,NaN,NaN,NaN,64080,NaN,248.0717
21,NaN,1,36362.769628,33.345693,156.901194,NaN,NaN,NaN,13065.373493,43.98387,229.213118
22,NaN,2,45468.07625,25.04019,310.28429,NaN,NaN,NaN,17652.568327,35.109558,716.925724
23,NaN,3,43000.245615,-5.427612,219.231684,NaN,NaN,NaN,14995.623444,-15.051322,367.666149
24,NaN,4,46771.874506,8.77118,71.516858,NaN,NaN,NaN,18366.734317,22.480632,102.406268
26,2023,NaN,213743,NaN,24.556705,NaN,NaN,NaN,84932.123977,NaN,32.540768
27,NaN,1,49262,5.3,35.5,NaN,NaN,NaN,19206.216436,4.567975,47.003444
28,NaN,2,55284,12.2,21.6,NaN,NaN,NaN,21877.902505,13.911811,23.933057
29,NaN,3,54165,-2.023147,26,NaN,NaN,NaN,20070.10253,-8.263601,33.83569
30,NaN,4,55032,1.600665,17.7,NaN,NaN,NaN,23777.902505,18.474851,29.459915
32,2024,NaN,260125.613899,NaN,21.700179,NaN,NaN,NaN,106746.11105,NaN,25.684024
33,NaN,1,58614,6.509182,18.983452,NaN,NaN,NaN,24063.308672,1.2003,25.289167
34,NaN,2,68438.524551,16.761272,23.794582,NaN,NaN,NaN,28136.150681,16.925528,28.605339
35,NaN,3,66255.705347,-3.18946,22.321337,NaN,NaN,NaN,25561.822735,-9.149539,27.362691
36,NaN,4,66817.384,0.847744,21.415511,NaN,NaN,NaN,28984.828962,13.391088,21.898174
38,2025,NaN,290064.703712,NaN,11.509474,106525.059396,NaN,NaN,120996.201781,NaN,13.349517
39,NaN,1,69677.897276,4.281091,18.875861,25208.283628,1.968773,37.64737,29384.30117,1.378211,22.112472
40,NaN,2,73752.758448,5.84814,7.764974,27393.072958,8.7,4.2,29205.670278,-0.607913,3.801229
41,NaN,3,72604.334769,-1.6,9.6,26708,-2.5,11.4,29840,2.2,16.7
42,NaN,4,74029.713218,1.963214,10.794728,27215.702811,1.9,10.1,32566.230333,9.1,12.4
44,2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,1,74665.366158,0.858646,7.157892,27415.075542,0.732565,8.754233,34039.064104,4.5,15.840986

#2024 TSA

In [ ]:
import pandas as pd

file_path_2024 = './water/tourism_2024.xlsx'
xl = pd.ExcelFile(file_path_2024)

def clean_tsa_sheet(df, sheet_name):
    # Basic cleaning: remove fully empty rows/cols
    df = df.dropna(how='all', axis=0).dropna(how='all', axis=1)

    if 'Indicator' in sheet_name:
        # Headers for Indicator sheets are typically in the first two rows
        headers = df.iloc[0].fillna(df.iloc[1] if len(df) > 1 else '').astype(str)
        headers = [h.replace('\n', ' ').strip() for h in headers]
        df.columns = headers
        df = df.iloc[2:].reset_index(drop=True)
    else:
        # For 'Jad' (Table) sheets, find the first row with significant data to use as header
        header_idx = 0
        for i in range(len(df)):
            if df.iloc[i].notna().sum() > 2:
                header_idx = i
                break
        headers = df.iloc[header_idx].astype(str)
        headers = [h.replace('\n', ' ').strip() for h in headers]
        df.columns = headers
        df = df.iloc[header_idx + 1:].reset_index(drop=True)

    # Clean up the first column (usually labels with bilingual text)
    if not df.empty and len(df.columns) > 0:
        first_col = df.columns[0]
        df[first_col] = df[first_col].apply(lambda x: str(x).split('\n')[-1].strip() if '\n' in str(x) else str(x).strip())

    return df.dropna(subset=[df.columns[0]] if len(df.columns) > 0 else [])

# Dictionary to store all cleaned DataFrames
all_cleaned_sheets = {}

for sheet in xl.sheet_names:
    df_raw = pd.read_excel(file_path_2024, sheet_name=sheet)
    df_clean = clean_tsa_sheet(df_raw, sheet)
    all_cleaned_sheets[sheet] = df_clean

    print(f"\n{'='*30} {sheet} {'='*30}")
    display(df_clean.head(10))

============================== Indicator Inbound ==============================

,Tahun Year,nan,2019.0,2020,2021,2022.0,2023.0,2024.0
0,nan,A1. Ketibaan pelawat ke Malaysia dari negara t...,35045625.0,6101378,399865,14267416.0,28964308.0,37961485.0
1,nan,Singapore,17033066.0,2871340,16729,8399088.0,14828553.0,18855680.0
2,nan,Indonesia,3882666.0,762854,13161,1601156.0,3479392.0,4145127.0
3,nan,China,3330129.0,428642,7729,260079.0,1613312.0,3725894.0
4,nan,Thailand,2223243.0,545803,318245,1185459.0,2300158.0,2268182.0
5,nan,Brunei Darussalam,1621344.0,190241,4039,404087.0,1116211.0,1732119.0
6,nan,India,846874.0,175104,3920,360256.0,773221.0,1365387.0
7,nan,Philippines,576107.0,87950,2842,203989.0,461787.0,571533.0
8,nan,South Korea,764882.0,137924,3033,175553.0,465617.0,553165.0
9,nan,Australia,421267.0,84319,1324,174365.0,400909.0,447785.0

============================== Indicator Domestik ==============================

,A. Pelawat domestik Domestic visitors,Tahun Year,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
0,nan,A1. Pelawat domestik mengikut negeri dikunjung...,176937,189253.0,205408.0,221272.0,239121.0,131660.0,65976.0,171603.0,213744.0,260126.0
1,nan,Johor,11589,12207.0,13141.0,13487.0,14274.0,7243.0,3658.0,12376.0,15805.0,17138.0
2,nan,Kedah,12425,13188.0,13305.0,14480.0,14831.0,10831.0,4023.0,11186.0,13444.0,14651.0
3,nan,Kelantan,9070,8646.0,9624.0,9846.0,10986.0,6058.0,1921.0,6627.0,7549.0,10514.0
4,nan,Melaka,11552,12268.0,12625.0,13123.0,13979.0,7275.0,3878.0,11757.0,15559.0,19128.0
5,nan,Negeri Sembilan,9984,10130.0,10822.0,12802.0,13303.0,7918.0,5485.0,11490.0,14959.0,17785.0
6,nan,Pahang,14398,14168.0,16491.0,18111.0,18498.0,9905.0,3405.0,13189.0,16456.0,20174.0
7,nan,Pulau Pinang,9341,12565.0,12643.0,14450.0,15411.0,8929.0,5061.0,10003.0,13128.0,16605.0
8,nan,Perak,15966,16783.0,20110.0,17553.0,21070.0,13173.0,4489.0,14567.0,17108.0,21776.0
9,nan,Perlis,1410,1410.0,1414.0,2156.0,2088.0,1193.0,407.0,1669.0,1951.0,3225.0

============================== Jad 1 ==============================

,nan,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
0,Products,RM Juta\nRM Million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Accommodation services,17656.4,20142.5,21034.2,21622.8,22007.3,3144.0,64.8,5234.1,14369.0,19752.7
2,Food and beverage serving services,10106.2,10602.9,11446.0,11784.7,12019.2,2011.2,78.6,5603.0,10574.6,17102.7
3,Passenger transport services,13362.5,14476.1,14850.5,15188.0,16023.7,2413.0,178.0,7160.7,16290.8,20449.0
4,Travel agencies and other reservation services,4165,4612.8,4217.0,3869.6,4047.1,582.5,0.5,740.7,3295.1,4302.6
5,"Cultural, sports and recreational services",2200.2,2424.1,2555.6,2366.3,2526.7,395.1,9.8,1755.8,2845.8,2892.5
6,Retail sale of automotive fuel,646.3,657.7,602.4,615.6,467.2,24.0,0.1,325.9,748.9,1075.6
7,Country-specific tourism characteristic goods,23827.5,25920.9,28141.7,29373.7,29924.4,4717.9,44.4,11288.4,25387.6,38672.9
8,Country-specific tourism characteristic services,2673.5,2782.8,2883.3,2861.7,2405.3,406.0,94.8,1703.1,2314.8,2780.6
9,Total,74637.6,81619.7,85730.8,87682.4,89421.0,13693.7,470.9,33811.7,75826.5,107028.5

============================== Jad 1A ==============================

,nan,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
0,Products,RM Juta\nRM Million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Accommodation services,17656.4,20142.5,21034.2,21622.8,22007.3,3144.0,64.8,5234.1,14369.0,19752.7
2,Food and beverage serving services,9727.4,10190.2,10928.0,11274.1,11517.1,1907.2,49.7,5338.2,10069.0,16255.2
3,Passenger transport services,12952.3,14011.7,14297.4,14639.4,15456.2,2297.3,168.4,6834.3,15616.7,19547.4
4,Travel agencies and other reservation services,4008.9,4433.3,4026.1,3702.0,3878.0,552.4,0.4,705.7,3137.6,4089.4
5,"Cultural, sports and recreational services",2117.7,2329.8,2439.9,2263.8,2421.2,374.7,7.8,1672.8,2709.7,2749.1
6,Retail sale of automotive fuel,622.1,632.1,575.2,589.0,447.7,22.8,0.0,310.5,713.1,1022.3
7,Country-specific tourism characteristic goods,22934.4,24912.0,26868.0,28101.2,28674.2,4473.9,10.8,10755.0,24173.6,36756.4
8,Country-specific tourism characteristic services,2573.3,2674.4,2752.8,2737.7,2304.8,385.0,87.8,1622.7,2204.1,2642.8
9,Total,72592.5,79325.9,82921.5,84929.9,86706.5,13157.3,389.8,32473.3,72992.8,102815.3

============================== Jad 1B ==============================

,nan,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
0,Products,RM Juta\nRM Million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Food and beverage serving services,378.8,412.7,518.1,510.5,502.1,104.0,28.8,264.8,505.7,847.5
2,Passenger transport services,410.2,464.4,553.2,548.6,567.5,115.7,9.6,326.4,674.0,901.6
3,Travel agencies and other reservation services,156.1,179.5,190.9,167.6,169.1,30.1,0.1,35.0,157.6,213.2
4,"Cultural, sports and recreational services",82.5,94.4,115.7,102.5,105.6,20.4,2.0,83.0,136.1,143.3
5,Retail sale of automotive fuel,24.2,25.6,27.3,26.7,19.5,1.2,0.0,15.4,35.8,53.3
6,Country-specific tourism characteristic goods,893.1,1008.9,1273.8,1272.5,1250.2,244.0,33.6,533.4,1214.0,1916.4
7,Country-specific tourism characteristic services,100.2,108.3,130.5,124.0,100.5,21.0,7.0,80.5,110.7,137.8
8,Total,2045.1,2293.8,2809.3,2752.5,2714.5,536.5,81.1,1338.4,2833.8,4213.2
9,Annual percentage change (%),..,12.2,22.5,-2.0,-1.4,-80.2,-84.9,1550.4,111.7,48.7

============================== Jad 2 ==============================

,nan,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
0,Products,RM Juta\nRM Million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Accommodation services,6133.3,6598.3,7164.1,7882.8,8625.7,2087.9,1087.4,5956.5,10653.5,11914.4
2,Food and beverage serving services,9317.8,10311.7,11450.4,12785.6,14702.4,7497.4,2783.2,9725.2,13802.8,17342.5
3,Passenger transport services,4560,4868.3,5215.1,5777.4,6384.5,2506.3,888.9,4816.7,5691.1,7187.2
4,Travel agencies and other reservation services,1054.6,1264.8,1284.0,1400.9,1603.5,94.6,21.1,774.5,1050.2,1270.9
5,"Cultural, sports and recreational services",968.9,1055.3,1234.2,1390.2,1695.3,569.1,457.0,2022.4,2269.5,2965.4
6,Retail sale of automotive fuel,11480.5,11939.4,12599.4,13710.3,15498.5,3627.2,2038.8,8839.7,11226.7,13507.9
7,Country-specific tourism characteristic goods,23192.1,26376.8,30149.2,34757.9,39033.4,21267.4,9263.9,24939.2,30842.7,39910.5
8,Country-specific tourism characteristic services,3833.7,4083.1,4565.7,5036.4,5094.9,984.9,910.8,2142.9,3139.9,4347.5
9,Total,60541.1,66497.7,73662.1,82741.4,92638.2,38634.6,17451.0,59217.0,78676.4,98446.2

============================== Jad 2A ==============================

,nan,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
0,Products,RM Juta\nRM Million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Accommodation services,6133.3,6598.3,7164.1,7882.8,8625.7,2087.9,1087.4,5956.5,10653.5,11914.4
2,Food and beverage serving services,6295.7,6813.8,7449.2,8372.5,9756.1,4969.6,1153.8,6186.5,8734.7,10736.5
3,Passenger transport services,3985.3,4338.2,4629.4,5063.4,5617.4,2110.9,693.4,4205.5,4837.5,6094.6
4,Travel agencies and other reservation services,994.9,1255.9,1274.9,1392.0,1596.5,93.7,20.6,773.2,1048.3,1267.6
5,"Cultural, sports and recreational services",485.4,496.3,560.6,684.3,757.8,232.8,199.8,1318.1,1336.2,1724.8
6,Retail sale of automotive fuel,9197.3,8535.3,9109.0,9603.5,10533.5,2109.9,889.3,5078.8,6891.0,8221.8
7,Country-specific tourism characteristic goods,8464.2,10714.3,14064.5,16187.6,18803.1,9526.1,2176.9,10310.1,12159.9,14219.9
8,Country-specific tourism characteristic services,1948.3,2056.5,2019.4,2377.1,2896.3,743.3,694.1,1159.7,1874.6,2690.3
9,Total,37504.5,40808.4,46271.1,51563.2,58586.5,21874.2,6915.3,34988.5,47535.7,56870.0

============================== Jad 2B ==============================

,nan,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
0,Products,RM Juta\nRM Million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Food and beverage serving services,3022.1,3497.9,4001.1,4413.1,4946.4,2527.7,1629.4,3538.6,5068.1,6606.0
2,Passenger transport services,574.7,530.1,585.7,714.1,767.1,395.3,195.5,611.2,853.5,1092.6
3,Travel agencies and other reservation services,59.7,9.0,9.2,8.9,7.0,0.8,0.5,1.3,1.9,3.2
4,"Cultural, sports and recreational services",483.5,559.1,673.6,705.9,937.5,336.3,257.2,704.3,933.2,1240.6
5,Retail sale of automotive fuel,2283.2,3404.1,3490.4,4106.7,4964.9,1517.3,1149.4,3760.8,4335.7,5286.0
6,Country-specific tourism characteristic goods,14727.9,15662.5,16084.7,18570.3,20230.2,11741.3,7087.0,14629.1,18682.8,25690.6
7,Country-specific tourism characteristic services,1885.4,2026.7,2546.3,2659.2,2198.6,241.6,216.7,983.1,1265.3,1657.2
8,Total,23036.6,25689.3,27391.0,31178.2,34051.7,16760.5,10535.7,24228.5,31140.7,41576.2
9,Annual percentage change (%),..,11.5,6.6,13.8,9.2,-50.8,-37.1,130.0,28.5,33.5

============================== Jad 3 ==============================

,nan,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
0,Products,RM Juta\nRM Million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Accommodation services,8184.9,8238.0,9072.3,9624.1,10080.0,3747.6,3133.1,4800.7,7859.5,9229.8
2,Food and beverage serving services,3423.4,3914.8,4748.5,5470.1,5824.0,2213.4,2107.6,3763.9,5670.3,6014.0
3,Passenger transport services,11795,12220.9,13789.9,13000.8,14224.0,5927.5,2822.7,6986.9,8685.0,11860.9
4,Travel agencies and other reservation services,809.2,987.2,1158.2,1451.8,1568.0,575.8,104.9,788.8,1292.0,1545.3
5,"Cultural, sports and recreational services",746.9,851.0,1042.4,1275.0,1568.0,592.3,94.4,473.3,717.8,835.3
6,Country-specific tourism characteristic goods,5819.7,7387.0,8570.4,9731.1,10886.4,3675.3,1887.4,5161.3,10838.2,11485.0
7,Country-specific tourism characteristic services,342.3,442.5,501.9,575.8,649.6,487.3,335.5,563.5,825.4,793.5
8,Total,31121.4,34041.4,38883.5,41128.7,44800.1,17219.2,10485.6,22538.4,35888.2,41763.7
9,Annual percentage change (%),..,9.4,14.2,5.8,8.9,-61.6,-39.1,114.9,59.2,16.4

============================== Jad 4 ==============================

,nan,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
0,Products,RM Juta\nRM Million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Accommodation services,23789.7,26740.8,28198.3,29505.5,30633.0,5231.9,1152.2,11190.6,25022.5,31667.1
2,Food and beverage serving services,19424,20914.6,22896.4,24570.2,26721.7,9508.6,2861.7,15328.1,24377.4,34445.2
3,Passenger transport services,17922.5,19344.3,20065.6,20965.4,22408.3,4919.3,1066.9,11977.4,21981.8,27636.2
4,Travel agencies and other reservation services,5219.6,5877.7,5501.0,5270.5,5650.6,677.1,21.6,1515.2,4345.4,5573.4
5,"Cultural, sports and recreational services",3169.1,3479.5,3789.9,3756.5,4222.0,964.2,466.8,3778.2,5115.3,5857.8
6,Retail sale of automotive fuel,12126.8,12597.0,13201.8,14325.9,15965.7,3651.2,2038.9,9165.6,11975.6,14583.5
7,Country-specific tourism characteristic goods,47019.6,52297.7,58290.9,64131.6,68957.8,25985.2,9308.3,36227.6,56230.3,78583.3
8,Country-specific tourism characteristic services,6507.2,6865.9,7449.0,7898.1,7500.2,1390.9,1005.5,3846.0,5454.7,7128.0
9,Total,135178.7,148117.4,159392.9,170423.8,182059.1,52328.4,17921.9,93028.7,154503.0,205474.8

============================== Jad 5 ==============================

,nan,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023e,2024p
0,Industry,RM Juta\nRM Million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Accommodation services,19810,21269.0,22948.4,24733.1,26406.8,12137.9,9712.6,14727.5,18704.9,20415.3
2,Food and beverage serving services,26355.7,29380.0,33154.9,37782.1,43166.7,35571.2,33845.9,42052.4,45159.9,47726
3,Passenger transport services,7331.1,7834.5,8352.1,8798.6,9379.5,4863.0,3682.1,5790.0,7534.6,8473.2
4,Travel agencies and other reservation services,2897.8,3139.6,3453.0,3818.9,4226.9,1641.5,1092.9,3265.9,4109,4855.5
5,"Cultural, sports and recreational services",8987,9440.2,9895.3,10482.2,11307.1,6307.6,4215.3,8873.0,10287.3,11875.3
6,Retail sale of automotive fuel,3170.6,3490.5,3985.4,4467.9,4725.9,4181.6,4361.6,4300.8,4892.7,5162.2
7,Country-specific tourism characteristic goods,74792.8,82570.4,92847.3,102523.9,111121.6,106560.0,111617.8,134633.2,145804.7,154456
8,Country-specific tourism characteristic services,22593,24545.0,26045.4,27778.3,29695.0,29036.5,30013.2,31591.0,35434,38957.8
9,Total Gross Value Added of Tourism Industries,165938,181669.1,200681.9,220385.0,240029.5,200299.2,198541.4,245233.8,271927.1,291921.4

============================== Jad 6 ==============================

,nan,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023e,2024p
0,Products,Penawaran mengikut industri (RM Juta)\nSupply ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Accommodation services,25793.5,28663.3,30806.8,31647.4,31824.3,18490.3,5612.1,21437.2,26742.3,32844.6
2,Food and beverage serving services,63907.1,70692.4,79928.0,87025.2,96026.7,75318.3,24541.9,75812.7,82072.1,111553.9
3,Passenger transport services,33286.9,35284.2,37460.3,38609.9,42379.5,31300.1,27113.3,31708.8,40690.1,50518.5
4,Travel agencies and other reservation services,6379.7,6840.2,6861.4,6861.3,6973.1,3943.1,226.5,3825.7,6094.5,7863.7
5,"Cultural, sports and recreational services",19982.8,21080.7,21886.0,23227.1,24776.6,13993.9,9718.9,16746.2,18290.8,20576.5
6,Retail sale of automotive fuel,36759,40203.6,41300.3,44232.9,47612.6,27042.4,24292.7,37013.3,37647.5,44264.6
7,Retail trade,106878.9,118858.8,133617.0,147239.8,159423.4,153134.5,159968.0,175561.3,189568.9,204219.5
8,Country-specific tourism characteristic services,42099.2,45592.1,48625.2,51805.6,55584.1,53316.3,47675.9,53283.9,65482.4,65206.7
9,Total,335087.2,367215.3,400484.9,430649.2,464600.4,376538.9,299149.2,415389.1,466588.4,537047.9

============================== Jad 7 ==============================

,nan,2015,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
0,Industry,Ribu orang\nThousand persons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Accommodation services,184.1,207.4,210.5,222.4,233.8,209.9,202.8,218.7,225.6,231.9
2,Food and beverage serving services,912.7,1002.6,1087.0,1183.0,1237.7,1189.1,1164.4,1189.5,1244.5,1294.4
3,Passenger transport services,159.2,164.5,162.5,171.3,177.3,158.2,154.1,167.9,171.9,175.7
4,Travel agencies and other reservation services,32.7,35.8,40.1,38.7,40.7,31.0,23.6,25.7,27.7,29.4
5,"Cultural, sports and recreational services",75.6,74.8,78.9,80.9,81.2,63.2,48.0,50.2,54.6,58.4
6,Retail sale of automotive fuel,32.9,33.4,34.4,34.6,34.7,31.0,29.5,29.7,30.4,31.4
7,Retail trade,992.5,1106.0,1104.5,1147.9,1158.1,1156.6,1166.7,1178.2,1254.9,1339.5
8,Country-specific tourism characteristic services,294.5,317.1,348.6,370.5,356.9,342.5,347.9,364.8,372.6,377.1
9,Total,2684.2,2941.7,3066.5,3249.4,3320.3,3181.5,3137.0,3224.7,3382.2,3537.8

# Merging State-Level Domestic Tourism Data (2015-2025)

merge the data from `tourism_2024.xlsx` (Indicator Domestik) and `tourism_domestic_2025.xlsx` (Sheet 9).

1. Extract 2015-2024 data from the 2024 TSA file.
2. Extract 2018-2025 data from the 2025 Annual file.
3. Compare values for the overlapping years (2018-2024).
4. Create a final merged DataFrame.

In [ ]:
import pandas as pd
import numpy as np

# 1. Load the specific sheet from the 2024 file
df_2024_raw = all_cleaned_sheets['Indicator Domestik']

# Find the row where 'Johor' exists in ANY column to avoid indexing errors
mask = df_2024_raw.apply(lambda row: row.astype(str).str.contains('Johor', case=False, na=False).any(), axis=1)

if not mask.any():
    print("❌ Could not find 'Johor' in the dataset. Printing first 10 rows for inspection:")
    print(df_2024_raw.head(10))
else:
    start_idx = df_2024_raw[mask].index[0]

    # States usually span 16 rows (13 states + 3 Federal Territories)
    states_2024_raw = df_2024_raw.iloc[start_idx : start_idx + 16].copy()

    # Dynamically find the column containing the state names (the one that actually has 'Johor')
    state_col_idx = states_2024_raw.apply(lambda col: col.astype(str).str.contains('Johor', case=False, na=False).any()).idxmax()

    # Standard TSA sheets for 2024 usually have years starting from column index 3 (2015)
    # We'll map them carefully.
    states_2024 = pd.DataFrame({
        'State': states_2024_raw[state_col_idx].astype(str).str.strip(),
        2015: pd.to_numeric(states_2024_raw.iloc[:, 3], errors='coerce'),
        2016: pd.to_numeric(states_2024_raw.iloc[:, 4], errors='coerce'),
        2017: pd.to_numeric(states_2024_raw.iloc[:, 5], errors='coerce')
    })

    # 2. Use the already cleaned 2025 data (2018-2025)
    states_2025 = df_sheet9_clean.copy()

    # 3. Final Merge
    final_df = pd.merge(states_2024, states_2025, on='State', how='outer')

    # Cleanup: Remove non-state rows or headers
    final_df = final_df[~final_df['State'].str.contains('nan|None|Jumlah|Total|Pelawat', case=False, na=True)]

    # Sort and clean
    final_df = final_df.sort_values('State').reset_index(drop=True)

    print("--- Consolidated Domestic Visitors by State (2015-2025) ---")
    print("Units: '000 visitors")
    display(final_df)

--- Consolidated Domestic Visitors by State (2015-2025) ---
Units: '000 visitors

,State,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Johor,12207.0,13141.0,13487.0,13487.237912,14274.0,7243.0,3657.550,12376.202,15804.890,17138.338000,18196.973000
1,Kedah,13188.0,13305.0,14480.0,14480.018396,14831.0,10108.0,4023.002,11186.197,13444.055,14651.487954,15607.884000
2,Kelantan,8646.0,9624.0,9846.0,9846.123436,10986.0,6058.0,1920.930,6627.155,7549.370,10514.411000,12062.016000
3,Melaka,12268.0,12625.0,13123.0,13122.604163,13979.0,7275.0,3878.140,11757.166,15558.661,19128.405000,20832.201530
4,Negeri Sembilan,10130.0,10822.0,12802.0,12802.118906,13303.0,7918.0,5485.170,11490.144,14959.470,17784.532000,19356.545000
5,Pahang,14168.0,16491.0,18111.0,18111.356576,18498.0,9905.0,3404.772,13188.959,16455.567,20173.876000,23161.166000
6,Perak,16783.0,20110.0,17553.0,17553.161206,21070.0,13173.0,4489.273,14566.727,17107.518,21776.217000,23642.055000
7,Perlis,1410.0,1414.0,2156.0,2155.507903,2088.0,1193.0,406.796,1669.175,1950.771,3225.428000,3755.682000
8,Sabah,16518.0,17792.0,20360.0,20359.881091,22035.0,10337.0,3815.016,12589.005,16080.074,20591.813000,22361.168000
9,Sarawak,16282.0,17670.0,19380.0,19380.230199,19793.0,9393.0,6510.900,15464.621,17901.190,19625.552000,22721.527000
10,Selangor,24124.0,25491.0,30179.0,30179.047204,33589.0,19715.0,10211.580,21989.558,27579.478,34460.828046,36376.442000
11,Terengganu,12010.0,12979.0,13742.0,13742.366364,14158.0,7420.0,3719.052,10233.282,11760.516,14460.728000,15462.278000
12,W.P. Kuala Lumpur,16784.0,19049.0,19165.0,19165.497171,22633.0,12435.0,9116.005,16912.534,22232.643,26982.957000,35059.933182
13,W.P. Labuan,354.0,381.0,545.0,544.932022,524.0,107.0,53.899,243.695,331.360,449.630000,604.370000
14,W.P. Putrajaya,1816.0,1872.0,1892.0,1891.906993,1949.0,451.0,223.006,1305.808,1900.379,2556.836000,3146.484000

# National Tourists Consolidation (2012 - 2026 Q1)

1. **2024 TSA**: Historical annual data.
2. **2025 Annual**: Latest annual data and forecasts.
3. **2026 Q1**: Recent quarterly data including Q1 2026 and historical quarterly series.

In [ ]:
import os
import pandas as pd
import numpy as np

def build_cleaned_2012_2025_dataset(
    file_2025_path="./water/tourism_domestic_2025.xlsx",
    file_q1_path="./water/tourism_domestic_2026-q1.xlsx"
):
    # --- 1. Process 2012-2025 National Series from 2026-Q1 File ---
    df_q1_raw = pd.read_excel(file_q1_path)

    # Extract header at row index 4
    header_q1 = df_q1_raw.iloc[4]
    df_q1 = df_q1_raw.iloc[5:].copy()
    df_q1.columns = [str(c).strip() for c in header_q1]

    # Strict Filter to avoid Temporal Aggregation Leakage:
    # Keep ONLY rows where 'Suku Tahun' (Quarter) is NaN and 'Tahun' (Year) is valid
    annual_q1 = df_q1[df_q1['Suku Tahun'].isna() & df_q1['Tahun'].notna()].copy()
    annual_q1['Year'] = pd.to_numeric(annual_q1['Tahun'], errors='coerce')
    annual_q1 = annual_q1.dropna(subset=['Year'])
    annual_q1['Year'] = annual_q1['Year'].astype(int)
    annual_q1 = annual_q1[(annual_q1['Year'] >= 2012) & (annual_q1['Year'] <= 2025)]

    # Ingest and convert core metrics
    national_q1 = annual_q1[['Year', 'Bil. Pelawat Domestik', 'Jumlah Perbelanjaan Pelancongan']].copy()
    national_q1.columns = ['Year', 'Domestic_Visitors_000', 'Tourism_Expenditure_RM_mil']
    national_q1['Domestic_Visitors_000'] = pd.to_numeric(national_q1['Domestic_Visitors_000'], errors='coerce')
    national_q1['Tourism_Expenditure_RM_mil'] = pd.to_numeric(national_q1['Tourism_Expenditure_RM_mil'], errors='coerce')

    # --- 2. Process Detailed 2018-2025 Metrics from 2025 File (Sheet 1) ---
    df_s1_raw = pd.read_excel(file_2025_path, sheet_name='1')

    # Extract years from row index 2, columns C onwards
    years_s1 = [int(y) for y in df_s1_raw.iloc[2, 2:].values if pd.notna(y) and str(y).replace('.0','').isdigit()]

    metrics_s1 = [
        'Tourism_Expenditure_RM_mil',
        'Domestic_Visitors_Expenditure_RM_mil',
        'Visited_Households_Expenditure_RM_mil',
        'Annual_Growth_Rate_Pct(Tourism Expenditure-RM Million)',
        'Domestic_Visitors_000',
        'Tourism_Trips_000',
        'Average_Length_Of_Stay',
        'Average_Expenditure_Per_Trip_RM'
    ]

    data_s1 = df_s1_raw.iloc[[5, 6, 7, 8, 9, 11, 13, 15], 2:].values
    df_s1_clean = pd.DataFrame(data_s1, index=metrics_s1, columns=years_s1).T
    df_s1_clean.index.name = 'Year'
    df_s1_clean = df_s1_clean.reset_index()

    # --- 3. Merge & Prevent Revision Leakage ---
    # Perform outer join on 'Year'
    merged_df = pd.merge(
        national_q1,
        df_s1_clean,
        on='Year',
        how='left',
        suffixes=('_q1', '_s1')
    )

    # Prioritize late-release precision (2025 sheet) over earlier Q1 estimates
    merged_df['Domestic_Visitors_000'] = merged_df['Domestic_Visitors_000_s1'].fillna(merged_df['Domestic_Visitors_000_q1'])
    merged_df['Tourism_Expenditure_RM_mil'] = merged_df['Tourism_Expenditure_RM_mil_s1'].fillna(merged_df['Tourism_Expenditure_RM_mil_q1'])

    # Drop temporary merge columns
    merged_df = merged_df.drop(columns=[
        'Domestic_Visitors_000_q1', 'Domestic_Visitors_000_s1',
        'Tourism_Expenditure_RM_mil_q1', 'Tourism_Expenditure_RM_mil_s1'
    ])

    # Reorder columns cleanly
    cols_order = [
        'Year', 'Domestic_Visitors_000', 'Tourism_Expenditure_RM_mil',
        'Domestic_Visitors_Expenditure_RM_mil', 'Visited_Households_Expenditure_RM_mil',
        'Annual_Growth_Rate_Pct(Tourism Expenditure-RM Million)', 'Tourism_Trips_000', 'Average_Length_Of_Stay',
        'Average_Expenditure_Per_Trip_RM'
    ]
    final_df = merged_df[cols_order].sort_values('Year').reset_index(drop=True)
    return final_df

df_2012_2025_clean = build_cleaned_2012_2025_dataset()
print(df_2012_2025_clean.to_string(index=False))

 Year  Domestic_Visitors_000  Tourism_Expenditure_RM_mil  Domestic_Visitors_Expenditure_RM_mil  Visited_Households_Expenditure_RM_mil  Annual_Growth_Rate_Pct(Tourism Expenditure-RM Million)  Tourism_Trips_000  Average_Length_Of_Stay  Average_Expenditure_Per_Trip_RM
 2012          141433.000000                47778.000000                                   NaN                                    NaN                                                     NaN                NaN                     NaN                              NaN
 2013          152875.000000                54016.000000                                   NaN                                    NaN                                                     NaN                NaN                     NaN                              NaN
 2014          169282.000000                62151.000000                                   NaN                                    NaN                                                     NaN                NaN                     NaN                              NaN
 2015          176936.000000                67842.000000                                   NaN                                    NaN                                                     NaN                NaN                     NaN                              NaN
 2016          189253.000000                74773.000000                                   NaN                                    NaN                                                     NaN                NaN                     NaN                              NaN
 2017          205408.000000                83103.000000                                   NaN                                    NaN                                                     NaN                NaN                     NaN                              NaN
 2018          221272.480734                92561.341706                          82741.382549                            9819.959157                                               11.381991      302414.636522                2.444800                       306.072260
 2019          239120.865665               103183.759714                          92638.159000                           10545.602000                                               11.476085      332378.003274                2.520000                       310.000000
 2020          131660.150788                40424.334334                          38634.646976                            1789.687358                                              -60.822968      146990.043575                1.930000                       275.000000
 2021           65975.955000                18410.193742                          17450.979950                             959.213792                                              -54.457645       72398.831000                2.185110                       254.288550
 2022          171602.963000                64080.299582                          59216.955871                            4863.343711                                              248.069664      207785.257000                2.546765                       308.396758
 2023          213743.544000                84932.125000                          78676.422000                            6255.703000                                               32.540150      241474.125000                2.445889                       351.723498
 2024          260125.842000               106746.111050                          98446.228495                            8299.882555                                               25.684022      297853.174000                2.492058                       358.385004
 2025          290064.703712               121280.623042                         112080.740487                            9199.882555                                               13.615964      332215.028000                2.555495                       365.066637

#Water Quality

In [ ]:
import os
import requests


def download_portal_file(
    release_document_id, output_dir="./water", filename="Component_1_2025.xlsx"
):
    os.makedirs(output_dir, exist_ok=True)
    url = f"https://www.dosm.gov.my/portal-main/release-document-log?release_document_id={release_document_id}"

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, Gecko) Chrome/120.0.0.0 Safari/537.36"
    }

    response = requests.get(url, headers=headers, stream=True)
    filepath = os.path.join(output_dir, filename)

    if response.status_code == 200:
      with open(filepath, "wb") as f:
        for chunk in response.iter_content(chunk_size=8192):
          f.write(chunk)
      print(f"Downloaded successfully to {filepath}")
    else:
      print(f"Failed to download. Status code: {response.status_code}")


# Usage for Component 1 2025
download_portal_file(
    release_document_id="18591",
    output_dir="./water",
    filename="Component_1_2025.xlsx",
)

Downloaded successfully to ./water/Component_1_2025.xlsx

In [ ]:
import pandas as pd
wq_df = pd.read_excel('./water/Component_1_2025.xlsx', sheet_name='1.1')
wq_df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,"Jadual 1.1: Purata suhu, jumlah hujan dan pura...",NaN,NaN,NaN,NaN,NaN,NaN
1,"Table 1.1: Mean temperature, total rainfal...",NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Negeri/ Stesen meteorologi terpilih (ketinggia...,Tahun Year,Purata suhu (oC)\nMean temperature,NaN,Hujan\nRainfall,NaN,Purata kelembapan relatif
4,State/ Selected meteorological station (height...,NaN,Min.,Maks.\nMax.,Jumlah (mm)\nTotal (mm),Bil. hari\nNo. of days,Mean relative humidity (%)
5,Johor,NaN,NaN,NaN,NaN,NaN,NaN
6,Batu Pahat,2020,24.4,32.4,2089.6,197,82.3
7,(6.3 m),2021,24.2,32.1,2668.4,193,82.5
8,NaN,2022,24.2,32,2864.2,227,83.1
9,NaN,2023,24.6,32.3,Def.,Def.,83.072312
10,NaN,2024,25,32.7,2097.95,197,83.600815
11,Kluang,2020,24.1,31.9,2574.8,196,82.8
12,(88.1 m),2021,23.8,31.7,2682.1,185,82.6
13,NaN,2022,23.8,31.7,2663.7,197,83.4
14,NaN,2023,24.1,31.9,3035.22,195,84.74328
15,NaN,2024,24.3,32.1,2595.82,213,84.13922
16,Mersing,2020,24.2,31.6,2392.8,177,78.3
17,(43.6 m),2021,23.9,31.4,2317.7,172,84.2
18,NaN,2022,24.1,31.5,2817.8,200,83.9
19,NaN,2023,24.1,31.7,3884.81,194,84.844355
20,NaN,2024,24.4,32,2947.51,181,84.088871
21,Senai,2020,24.2,32.4,2778,208,84
22,(37.8 m),2021,23.9,32.1,2872.6,202,83.7
23,NaN,2022,23.9,32.2,2489.4,205,83.6
24,NaN,2023,24.2,32.4,3081.7,199,83.671505
25,NaN,2024,24.5,32.6,3301.55,215,83.48275
26,Kedah,NaN,NaN,NaN,NaN,NaN,NaN
27,Alor Setar,2020,24.3,33,2408.4,195,83.6
28,(3.9 m),2021,24,32.5,2272,168,82.2
29,NaN,2022,24.1,32.2,2193.6,202,83
30,NaN,2023,24.4,32.5,2460.4,178,78.482231
31,NaN,2024,Def.,Def.,Def.,Def.,77.483961
32,Pulau Langkawi,2020,25.7,32.5,2731.6,189,80.9
33,(6.4 m),2021,25.4,32,2819.6,178,85.4
34,NaN,2022,25.5,31.8,2940,213,78.4
35,NaN,2023,25.7,32.3,2831.86,170,76.110457
36,NaN,2024,26.1,32.9,2594.11,163,75.673477
37,Kelantan,NaN,NaN,NaN,NaN,NaN,NaN
38,Gong Kedak,2020,24.2,31.5,3808,175,82.4
39,(6.0 m),2021,23.9,31.3,3065.8,203,82.3
40,NaN,2022,23.9,31.3,4508.6,213,84.6
41,NaN,2023,24.3,31.6,4230.45,199,82.713387
42,NaN,2024,24.8,32.3,3802.98,155,80.472661
43,Kota Bharu,2020,24.6,31.6,2984.8,165,81.1
44,(4.4 m),2021,24.3,31.2,2527.6,168,81.7
45,NaN,2022,24.1,31,4045.7,202,83.5
46,NaN,2023,24.6,31.5,3486.82,183,81.855887
47,NaN,2024,25,31.8,2682.41,144,79.649203
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,"Jadual 1.1: Purata suhu, jumlah hujan dan pura...",NaN,NaN,NaN,NaN,NaN,NaN
50,"Table 1.1: Mean temperature, total rainfal...",NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Negeri/ Stesen meteorologi terpilih (ketinggia...,Tahun Year,Purata suhu (oC)\nMean temperature,NaN,Hujan\nRainfall,NaN,Purata kelembapan relatif
53,State/ Selected meteorological station (height...,NaN,Min.,Maks.\nMax.,Jumlah (mm)\nTotal (mm),Bil. hari\nNo. of days,Mean relative humidity (%)
54,Kelantan,NaN,NaN,NaN,NaN,NaN,NaN
55,Kuala Krai,2020,23.5,32.9,2776.4,190,83.4
56,(34.9 m),2021,23.1,32.4,Def.,Def.,85.4
57,NaN,2022,23.4,32.3,3220,203,86.2
58,NaN,2023,23.6,32.7,3172.01,203,85.597581
59,NaN,2024,23.9,33.3,2794.0,231,83.026156
60,Melaka,NaN,NaN,NaN,NaN,NaN,NaN
61,Melaka,2020,24,32.3,1712.2,160,79.3
62,(8.5 m),2021,24.1,31.7,2506,175,80.5
63,NaN,2022,24.2,31.6,2643.8,206,80.8
64,NaN,2023,24.4,31.8,2240.67,199,81.016613
65,NaN,2024,25,32.4,2236.48,189,79.838073
66,Negeri Sembilan,NaN,NaN,NaN,NaN,NaN,NaN
67,Kuala Pilah,2020,23.9,31.9,1871,177,81.3
68,(144.0 m),2021,23.2,32,1819.2,163,83.4
69,NaN,2022,23.2,31.9,2227.4,203,84.7
70,NaN,2023,23.3,31.9,1800.42,160,81.638145
71,NaN,2024,23.7,32.3,1704.31,179,82.868548
72,Pahang,NaN,NaN,NaN,NaN,NaN,NaN
73,"Batu Embun, Jerantut",2020,23.6,33,1997,188,84.6
74,(59.5 m),2021,23.6,32.6,2669.4,173,83.7
75,NaN,2022,23.7,32.7,2143.5,189,84.4
76,NaN,2023,23.5,32.6,2019.1,183,83.95444
77,NaN,2024,23.1,32.3,2415.37,178,79.72026
78,Cameron Highlands1,2020,15.9,22.7,2875,257,89.4
79,"(1,545.0 m)",2021,15.7,22.3,3263.6,243,88.7
80,NaN,2022,15.8,22.4,3151.8,263,88.1
81,NaN,2023,16,22.4,2931.51,249,90.168199
82,NaN,2024,16.4,23,3002,240,87.778253
83,Kuantan,2020,24.1,32.3,2409.2,180,75.5
84,(15.2 m),2021,23.9,31.9,Def.,Def.,81.9
85,NaN,2022,23.8,31.9,4134,218,82.8
86,NaN,2023,24.4,32.2,3517.24,183,82.222312
87,NaN,2024,24.3,32.2,3281.78,191,81.789579
88,Muadzam Shah,2020,23.7,32.4,1995,171,80.5
89,(33.3 m),2021,23.4,32.2,2466.6,175,80.2
90,NaN,2022,23.6,32.2,2778.2,169,82.1
91,NaN,2023,24.1,32.6,3375.4,197,81.447016
92,NaN,2024,24.3,33,2598.4,176,79.045627
93,Temerloh,2020,24,33.4,2034.4,172,82.6
94,(39.1 m),2021,23.7,33.2,2167.9,170,83.2
95,NaN,2022,23.7,32.9,1960.6,194,83.2
96,NaN,2023,23.9,33.1,2178.65,164,82.27
97,NaN,2024,24.3,33.5,2341.86,172,82.82698
98,Perak,NaN,NaN,NaN,NaN,NaN,NaN
99,Ipoh,2020,24.3,33,3269.4,210,79.9
100,(40.1 m),2021,23.9,32.8,2965.4,213,79.2
101,NaN,2022,24.1,33.1,3345.5,220,77.3
102,NaN,2023,24.1,32.9,2987.47,215,80.230108
103,NaN,2024,24.4,33.2,3767.14,212,81.506093
104,"Lubok Merbau, Kuala Kangsar",2020,24,33.3,2053.1,213,82.1
105,(77.5 m),2021,23.3,32.8,1988.2,174,81.8
106,NaN,2022,23.4,32.5,1945.6,207,82.5
107,NaN,2023,23.3,32.6,1617.69,193,82.939516
108,NaN,2024,23.8,33.1,2054.47,181,83.047366
109,Sitiawan,2020,24.5,32.6,2115,186,83.9
110,(6.8 m),2021,24.1,32.7,2057,167,81.6
111,NaN,2022,24.2,32.7,1943,181,81.1
112,NaN,2023,24.5,32.6,1945.02,185,80.248656
113,NaN,2024,25.1,33.2,1995.98,173,79.104131
114,Perlis,NaN,NaN,NaN,NaN,NaN,NaN
115,Chuping,2020,24.3,33.2,2195,172,82.8
116,(21.7 m),2021,24.1,32.8,2081,168,83.6
117,NaN,2022,24.3,32.7,2148,189,84
118,NaN,2023,24.4,33,1758.12,166,81.884677
119,NaN,2024,25,34,2037.87,160,80.623826
120,Pulau Pinang,NaN,NaN,NaN,NaN,NaN,NaN
121,Bayan Lepas,2020,25.4,32.2,1831.2,167,77.8
122,(2.5 m),2021,25.1,32,2232.8,168,77.7
123,NaN,2022,25.5,32.2,2140.8,208,76.1
124,NaN,2023,25.8,32.5,2206.21,189,75.061398
125,NaN,2024,26.3,32.9,2096.82,180,72.820332
126,Butterworth,2020,24.8,32.1,2160.8,187,79.2
127,(3.3 m),2021,24.5,31.8,1982.2,177,78.2
128,NaN,2022,24.4,31.5,2034.8,199,82.9
129,NaN,2023,24.7,31.9,2060.22,184,80.834919
130,NaN,2024,25.2,32.6,2184.53,188,74.077599
131,Sabah,NaN,NaN,NaN,NaN,NaN,NaN
132,Keningau,2020,22.6,32,1691.8,189,81.7
133,(319.0 m),2021,22.1,31.6,1589.2,192,82.3
134,NaN,2022,22.3,31.3,2433.1,234,83.3
135,NaN,2023,22.4,32.2,1429.21,184,81.575029
136,NaN,2024,22.2,31.2,1708.6,194,81.219489
137,Kota Kinabalu,2020,24.3,32.2,3456.6,208,82.4
138,(2.1 m),2021,24.1,31.8,3584.8,201,82.7
139,NaN,2022,23.9,31.8,3566.6,208,83
140,NaN,2023,24.5,32.6,2161.87,175,80.450269
141,NaN,2024,24.8,32.7,3046.87,175,81.106604
142,Sabah,NaN,NaN,NaN,NaN,NaN,NaN
143,Kudat,2020,24.6,31,2238.4,165,82.9
144,(3.5 m),2021,24.3,30.7,2802.8,201,84.5
145,NaN,2022,24.4,30.6,2383.4,185,84.7
146,NaN,2023,24.1,30.6,3198.81,191,83.97
147,NaN,2024,24.2,30.2,2159.72,167,82.503704
148,Ranau,2020,20.9,30.1,2521.4,227,82.3
149,(501.0 m),2021,20.7,30,2926,242,82.7
150,NaN,2022,21,30,3116,239,83.1
151,NaN,2023,21,30.3,2902.24,223,83.637366
152,NaN,2024,21.7,30.7,2161.96,211,81.810618
153,Sandakan,2020,24.9,31.4,2380.3,168,82.3
154,(12.1 m),2021,24.6,31.2,3394,212,83.7
155,NaN,2022,24.5,31.2,3419.6,217,84
156,NaN,2023,24.9,31.8,3697.94,207,82.172554
157,NaN,2024,25.4,32,2538.03,167,81.857401
158,Tawau,2020,23.8,31.8,1947.8,185,85
159,(17.5 m),2021,23.6,31.5,1974.4,192,86
160,NaN,2022,23.6,31.4,2303,189,84.9
161,NaN,2023,24.1,32.2,1847.92,179,83.692742
162,NaN,2024,24.4,32.1,2201.43,180,83.928871
163,Sarawak,NaN,NaN,NaN,NaN,NaN,NaN
164,Bintulu,2020,24.2,31.8,4248,242,87.4
165,(24.3 m),2021,23.8,31.9,4021.2,227,85.6
166,NaN,2022,23.7,31.7,4323.4,219,85.87
167,NaN,2023,23.9,32,3403.86,215,87.394892
168,NaN,2024,24.3,32.3,4033.86,225,85.823082
169,Kapit,2020,24.3,32.9,4751.6,292,86.6
170,(35.0 m),2021,23.9,32.8,4346.2,252,86
171,NaN,2022,23.7,32.5,3923.1,270,85.8
172,NaN,2023,22.4,31.1,3393.13,234,85.47
173,NaN,2024,22.3,30.5,5624.02,273,86.326314
174,Kuching,2020,24,32,4079.6,258,86.8
175,(20.9 m),2021,23.6,32,4436.6,236,85.2
176,NaN,2022,23.6,31.8,3958.4,250,86.3
177,NaN,2023,24,32.4,4335.21,248,83.419624
178,NaN,2024,24.3,32.3,5042.78,249,84.726505
179,Limbang,2020,23.8,32.9,3328,226,84
180,(3.6 m),2021,23.6,32.5,4118.6,230,85.3
181,NaN,2022,23.7,32.4,4015.9,243,84.1
182,NaN,2023,23.8,32.8,3187.13,242,84.174866
183,NaN,2024,24.3,33.3,3931.9,229,83.517554
184,Sarawak,NaN,NaN,NaN,NaN,NaN,NaN
185,Miri,2020,24.3,31.6,3344.2,209,86.1
186,(17.0 m),2021,24,31.3,2877.6,211,85.4
187,NaN,2022,23.8,31.1,3327.4,220,85.4
188,NaN,2023,24.2,31.6,2522.7,194,84.194892
189,NaN,2024,24.7,32,2953.24,205,83.958226
190,Sibu,2020,23.8,32.3,3275.4,258,85.5
191,(30.9 m),2021,23.6,32.4,3251.4,235,84.5
192,NaN,2022,23.3,31.8,4202.4,249,85.5
193,NaN,2023,23.7,32.2,3757.51,245,85.895672
194,NaN,2024,24,32.2,3868.49,249,85.845977
195,Mulu,2020,23.5,32.9,5320.8,263,87.7
196,(26.2 m),2021,23.1,32.9,5365.8,264,86
197,NaN,2022,23,32.4,6172.8,289,88.3
198,NaN,2023,20.2,28.8,5213.6,271,86.94
199,NaN,2024,17.6,25,5043.63,270,Def.
200,Sri Aman,2020,23.6,32.4,3343.2,242,87.7
201,(9.6 m),2021,23.2,32.3,3518,222,86.8
202,NaN,2022,23.3,32.5,3604.7,232,86.6
203,NaN,2023,23.1,32.2,3055.21,209,Def.
204,NaN,2024,22.7,31,4000.75,251,86.546071
205,Selangor,NaN,NaN,NaN,NaN,NaN,NaN
206,KLIA Sepang,2020,24.8,32.5,2364.6,179,79.2
207,(16.1 m),2021,24.2,32.3,2059.4,165,78.2
208,NaN,2022,24.3,32.2,2427,194,80.7
209,NaN,2023,24.5,32.3,2492.03,197,80.052097
210,NaN,2024,24.9,32.9,2407.32,193,79.794964
211,Petaling Jaya,2020,25.5,33.3,3817,212,72.5
212,(58.6 m),2021,25.3,33.1,Def.,Def.,72.9
213,NaN,2022,25.1,32.78,Def.,Def.,76
214,NaN,2023,25.29,32.94,Def.,Def.,67.9
215,NaN,2024,24.6,32.18,Def.,Def.,76.465575
216,Subang,2020,25.1,33.5,3236,206,78.5
217,(16.6 m),2021,24.6,33.1,3564.8,188,75.2
218,NaN,2022,24.7,32.9,2810.3,223,77.2
219,NaN,2023,25,33,3197.18,227,77.932984
220,NaN,2024,25.4,33.5,3321.86,215,77.214758
221,Terengganu,NaN,NaN,NaN,NaN,NaN,NaN
222,Kerteh,2020,24.1,31.3,3531,184,85.8
223,(3.7 m),2021,23.8,31,2751.6,197,85.3
224,NaN,2022,23.9,31.1,4501,215,85.4
225,NaN,2023,24.2,31.1,3830.17,206,84.991192
226,NaN,2024,24,31.2,3935.07,190,83.027258
227,Terengganu,NaN,NaN,NaN,NaN,NaN,NaN
228,Kuala Terengganu,2020,24.9,31.5,2946.6,171,82.4
229,(5.2 m),2021,24.5,31.3,2285.2,172,82.2
230,NaN,2022,24.6,31.1,Def.,195,84.8
231,NaN,2023,25,31.5,4020.22,182,83.632204
232,NaN,2024,25.4,32.1,2678.35,146,82.119794
233,W.P. Labuan,NaN,NaN,NaN,NaN,NaN,NaN
234,Labuan,2020,25,31.4,4301.3,203,83.1
235,(27.9 m),2021,24.4,30.9,4127.5,225,83.3
236,NaN,2022,24.6,31,4107.4,220,84
237,NaN,2023,24.7,31.1,3011.55,195,81.604973
238,NaN,2024,25.3,31.7,3457.93,196,82.801246

In [ ]:
import numpy as np

df_1_1 = pd.read_excel('./water/Component_1_2025.xlsx', sheet_name='1.1')

def clean_sheet_1_1(df):
  cleaned_records = []
  current_state = None
  current_station = None

  for idx in range(5, len(df)):
    row = df.iloc[idx]
    col0 = str(row.iloc[0]).strip() if pd.notna(row.iloc[0]) else None

    # Identify state header rows
    if (
        col0
        and not col0.startswith("(")
        and pd.isna(row.iloc[1])
        and pd.isna(row.iloc[2])
    ):
      current_state = col0
      continue

    # Identify station name rows
    if col0 and not col0.startswith("(") and pd.notna(row.iloc[1]):
      current_station = col0

    # Parse annual record
    year = row.iloc[1] if pd.notna(row.iloc[1]) else row.iloc[2]

    try:
      year_val = int(year)
      if 2000 <= year_val <= 2030:

        def parse_numeric(val):
          try:
            return float(val)
          except (ValueError, TypeError):
            return np.nan

        cleaned_records.append({
            "State": current_state,
            "Station": current_station,
            "Year": year_val,
            "Min_Temp_C": parse_numeric(row.iloc[2]),
            "Max_Temp_C": parse_numeric(row.iloc[3]),
            "Total_Rainfall_mm": parse_numeric(row.iloc[4]),
            "Rainfall_Days": parse_numeric(row.iloc[5]),
            "Relative_Humidity_Pct": parse_numeric(row.iloc[6]),
        })
    except (ValueError, TypeError):
      continue

  return pd.DataFrame(cleaned_records)

clean_df_1_1 = clean_sheet_1_1(df_1_1)

In [ ]:
df_1_33 = pd.read_excel("./water/Component_1_2025.xlsx", sheet_name="1.33, 1.34, 1.35")


def clean_sheet_1_33(df):
  records = []
  for idx in range(7, 12):
    row = df.iloc[idx]
    year = int(row.iloc[0])
    total_basins = int(row.iloc[1])

    pollutants = [
        ("Ammoniacal Nitrogen (NH3-N)", 2, 3, 4),
        ("Biochemical Oxygen Demand (BOD5)", 5, 6, 7),
        ("Suspended Solids (SS)", 8, 9, 10),
    ]

    for name, c_idx, st_idx, t_idx in pollutants:
      records.append({
          "Year": year,
          "Total_Basins_Monitored": total_basins,
          "Pollutant": name,
          "Clean_Basins": int(row.iloc[c_idx]),
          "Slightly_Polluted_Basins": int(row.iloc[st_idx]),
          "Polluted_Basins": int(row.iloc[t_idx]),
      })

  return pd.DataFrame(records)


clean_df_1_33 = clean_sheet_1_33(df_1_33)

##cleaned

In [ ]:
print("sheet1.1")
print(clean_df_1_1.head(10))
print("---------------------------------------------")
print("sheet1.33\n")
print(clean_df_1_33.head(10))

sheet1.1
   State     Station  Year  Min_Temp_C  Max_Temp_C  Total_Rainfall_mm  \
0  Johor  Batu Pahat  2020        24.4        32.4            2089.60
1  Johor  Batu Pahat  2021        24.2        32.1            2668.40
2  Johor  Batu Pahat  2022        24.2        32.0            2864.20
3  Johor  Batu Pahat  2023        24.6        32.3                NaN
4  Johor  Batu Pahat  2024        25.0        32.7            2097.95
5  Johor      Kluang  2020        24.1        31.9            2574.80
6  Johor      Kluang  2021        23.8        31.7            2682.10
7  Johor      Kluang  2022        23.8        31.7            2663.70
8  Johor      Kluang  2023        24.1        31.9            3035.22
9  Johor      Kluang  2024        24.3        32.1            2595.82

   Rainfall_Days  Relative_Humidity_Pct
0          197.0              82.300000
1          193.0              82.500000
2          227.0              83.100000
3            NaN              83.072312
4          197.0              83.600815
5          196.0              82.800000
6          185.0              82.600000
7          197.0              83.400000
8          195.0              84.743280
9          213.0              84.139220
---------------------------------------------
sheet1.33

   Year  Total_Basins_Monitored                         Pollutant  \
0  2020                     144       Ammoniacal Nitrogen (NH3-N)
1  2020                     144  Biochemical Oxygen Demand (BOD5)
2  2020                     144             Suspended Solids (SS)
3  2021                     144       Ammoniacal Nitrogen (NH3-N)
4  2021                     144  Biochemical Oxygen Demand (BOD5)
5  2021                     144             Suspended Solids (SS)
6  2022                     144       Ammoniacal Nitrogen (NH3-N)
7  2022                     144  Biochemical Oxygen Demand (BOD5)
8  2022                     144             Suspended Solids (SS)
9  2023                     144       Ammoniacal Nitrogen (NH3-N)

   Clean_Basins  Slightly_Polluted_Basins  Polluted_Basins
0            28                        74               42
1            83                        46               15
2           110                        14               20
3            58                        37               49
4           124                        11                9
5           127                         7               10
6            52                        51               41
7           120                        10               14
8           118                        12               14
9            45                        58               41

coastal, eastry, island marine water quality index

#----------------------------------

## Fish landing

In [ ]:
!pip install pdfplumber

Collecting pdfplumber
  Downloading pdfplumber-0.11.10-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 1.1 MB/s eta 0:00:00
Collecting pdfminer.six==20260107 (from pdfplumber)
  Downloading pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Collecting Pillow>=12.2.0 (from pdfplumber)
  Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting pypdfium2>=5.9.0 (from pdfplumber)
  Downloading pypdfium2-5.13.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 3.8 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (3.4.9)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (50.0.1)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)
Downloading pdfplumber-0.11.10-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 4.4 MB/s eta 0:00:00
Downloading pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 36.8 MB/s eta 0:00:00
Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 57.2 MB/s eta 0:00:00
Downloading pypdfium2-5.13.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 57.4 MB/s eta 0:00:00
Installing collected packages: pypdfium2, Pillow, pdfminer.six, pdfplumber
  Attempting uninstall: Pillow
    Found existing installation: pillow 11.3.0
    Uninstalling pillow-11.3.0:
      Successfully uninstalled pillow-11.3.0
Successfully installed Pillow-12.3.0 pdfminer.six-20260107 pdfplumber-0.11.10 pypdfium2-5.13.0

In [ ]:
import os
import pdfplumber
import pandas as pd

pdf_path_all = [
    "/content/2. JADUAL PENDARATAN IKAN LAUT 2023.pdf",
    "/content/2. Jadual Pendaratan Ikan Laut.pdf",
    "/content/2. JADUAL PENDARATAN IKAN 2025 .pdf"
]

# --- DEFINE A REUSABLE EXTRACTION FUNCTION ---
def extract_fisheries_table(pdf_paths, target_title):
    all_extracted_rows = []

    for pdf_path in pdf_paths:
        file_name = os.path.basename(pdf_path)
        table_found_in_file = False

        with pdfplumber.open(pdf_path) as pdf:
            print(f"Scanning for '{target_title}' in {file_name}...")

            for page_idx, page in enumerate(pdf.pages):
                text = page.extract_text()

                if text:
                    # Look at the first 5 lines for safety
                    lines = text.split("\n")[:5]
                    header_snippet = " ".join(lines)

                    if target_title.lower() in header_snippet.lower():
                        print(f" -> Found title on Page {page_idx + 1}! Extracting...")
                        table_data = page.extract_table()

                        if table_data:
                            # Use table_data[0] explicitly as headers to fix the indexing bug
                            df_temp = pd.DataFrame(table_data[1:], columns=table_data[0])

                            if len(df_temp) >= 22:
                                for col in df_temp.columns:
                                    clean_col = str(col).strip()
                                    if clean_col.isdigit() and len(clean_col) == 4:
                                        raw_val = str(df_temp.loc[21, col])
                                        clean_val = raw_val.replace(" ", "").replace(",", "")

                                        try:
                                            all_extracted_rows.append({
                                                "Year": int(clean_col),
                                                "Value": float(clean_val)
                                            })
                                            table_found_in_file = True
                                        except ValueError:
                                            pass

                                if table_found_in_file:
                                    break # Exit page loop for this PDF

            if not table_found_in_file:
                print(f" -> Warning: Could not locate table for '{target_title}'")

    # Compile, deduplicate, and sort chronologically
    if all_extracted_rows:
        df_result = pd.DataFrame(all_extracted_rows)
        df_result = df_result.drop_duplicates(subset=["Year"], keep="first")
        df_result = df_result.sort_values(by="Year").reset_index(drop=True)
        return df_result
    else:
        return pd.DataFrame() # Return empty DataFrame if nothing found

# --- EXECUTE FOR BOTH TITLES ---

# 1. Extract Landings (Quantity) Data
print("=== EXTRACTING LANDINGS DATA ===")
df_landings = extract_fisheries_table(pdf_path_all, "PENDARATAN PERIKANAN TANGKAPAN")
df_landings.rename(columns={"Value": "Fish_landings"}, inplace=True) # Rename value column to match landings

# 2. Extract Value (Nilai) Data
print("\n=== EXTRACTING VALUE DATA ===")
df_value = extract_fisheries_table(pdf_path_all, "NILAI PERIKANAN TANGKAPAN")
df_value.rename(columns={"Value": "Fish_value_RM"}, inplace=True) # Rename value column to show RM currency

# --- DISPLAY RESULTS ---
print("\n--- Landings Table ---")
print(df_landings.to_string(index=False))

print("\n--- Value Table ---")
print(df_value.to_string(index=False))

=== EXTRACTING LANDINGS DATA ===
Scanning for 'PENDARATAN PERIKANAN TANGKAPAN' in 2. JADUAL PENDARATAN IKAN LAUT 2023.pdf...
 -> Found title on Page 49! Extracting...
Scanning for 'PENDARATAN PERIKANAN TANGKAPAN' in 2. Jadual Pendaratan Ikan Laut.pdf...

KeyboardInterrupt:

In [ ]:
df_fisheries = df_landings.merge(df_value, on=["Year"])

In [ ]:
df_fisheries

In [ ]:
df_2012_2025_clean

In [ ]:
test_df = df_2012_2025_clean.merge(df_fisheries, on=["Year"], how="inner")

In [ ]:
test_df

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# 2. Compute the pairwise correlation matrix (ignoring non-numeric columns)
corr_matrix = test_df.corr(numeric_only=True)

# 3. Set up the matplotlib figure size
plt.figure(figsize=(10, 8))

# 4. Generate the heatmap
sns.heatmap(
    corr_matrix,
    annot=True,          # Display the correlation numbers inside the cells
    fmt=".2f",           # Format the numbers to 2 decimal places
    cmap="coolwarm",     # Use a diverging color scheme (blue = negative, red = positive)
    vmin=-1,             # Minimum anchor value for the scale
    vmax=1,              # Maximum anchor value for the scale
    square=True          # Force cells to be square-shaped
)

# 5. Display the plot
plt.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# 2. Plotting directly with Pandas
# Specify 'x' and 'y'. If 'y' is a list, it plots multiple lines automatically.
test_df.plot(x='Year', y=["Fish_landings"], marker='o', figsize=(10, 6))

# 3. Customize with Matplotlib
plt.title('', fontsize=14, fontweight='bold')
plt.xlabel('Year', fontsize=12)
plt.ylabel('Fish Landings (Tons)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)

# 4. Display the graph
plt.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# 2. Plotting directly with Pandas
# Specify 'x' and 'y'. If 'y' is a list, it plots multiple lines automatically.
test_df.plot(x='Year', y=["Fish_value_RM"], marker='o', figsize=(10, 6))

# 3. Customize with Matplotlib
plt.title('', fontsize=14, fontweight='bold')
plt.xlabel('Year', fontsize=12)
plt.ylabel('Fish value (RM million)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)

# 4. Display the graph
plt.show()

# Marine Protected Area (OLD UNUSED)

In [ ]:
TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJqaXJ1aTMyQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoiamlydWkzMkBnbWFpbC5jb20iLCJyb2xlIjoiMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvdXNlcmRhdGEiOiIiLCJlbWFpbCI6ImppcnVpMzJAZ21haWwuY29tIiwibGFzdHBhc3N3b3JkcmVzZXQiOiIiLCJuYmYiOjE3ODk4NDA2MjcsImV4cCI6MTc4OTg0MTUyNywiaWF0IjoxNzg5ODQwNjI3fQ.eWH3dbo2phy7AL53Ukr5lW2Orlyt33sJBcnntCkx_Aw"

In [ ]:
import requests
import pandas as pd
import json

BASE_URL = "https://myfirst.dof.gov.my"

headers = {
    "Authorization": f"Bearer {TOKEN}",
    "Accept": "application/json, text/plain, */*"
}

url = f"{BASE_URL}/myfirst/pengurusantamanlaut/tamanlautcarianpulau"

params = {
    "kodnegeri": ""
}

r = requests.get(
    url,
    headers=headers,
    params=params,
    verify=False,
    timeout=30
)

print("Status:", r.status_code)
print("URL:", r.url)
print("Content-Type:", r.headers.get("content-type"))
print(r.text[:5000])

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'myfirst.dof.gov.my'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Status: 200
URL: https://myfirst.dof.gov.my/myfirst/pengurusantamanlaut/tamanlautcarianpulau?kodnegeri=
Content-Type: application/json; charset=utf-8
{"pulau":[{"PAGE_ROWNUM":1,"PAGE_TOTALROW":86,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":11,"KOD_NEGERI":"01","NEGERI":"Johor","KOD_DAERAH":"0105","DAERAH":"Mersing","KOD_MPA":"010506","KOD_PULAU":"01050602","PULAU":"Pulau Duyung","WARTA_DATE":null,"NO_WARTA":null,"AREA_HA":133.77918810,"PETA_RUJUK":null,"CARTA_MAL":null,"CATATAN":"Small Island","ID_TAMANLAUT":"01","TAMANLAUT":"Taman Laut Johor","AREA_KMSQ":1.33789654},{"PAGE_ROWNUM":2,"PAGE_TOTALROW":86,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":12,"KOD_NEGERI":"01","NEGERI":"Johor","KOD_DAERAH":"0105","DAERAH":"Mersing","KOD_MPA":"010506","KOD_PULAU":"01050603","PULAU":"Pulau Lang","WARTA_DATE":null,"NO_WARTA":null,"AREA_HA":5.67727703,"PETA_RUJUK":null,"CARTA_MAL":null,"CATATAN":"Small Island","ID_TAMANLAUT":"01","TAMANLAUT":"Taman Laut Johor","AREA_KMSQ":0.05677781},{"PAGE_ROWNUM":3,"PAGE_TOTALROW":86,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":13,"KOD_NEGERI":"01","NEGERI":"Johor","KOD_DAERAH":"0105","DAERAH":"Mersing","KOD_MPA":"010506","KOD_PULAU":"01050604","PULAU":"Pulau Pinang","WARTA_DATE":null,"NO_WARTA":"","AREA_HA":14.89937430,"PETA_RUJUK":"","CARTA_MAL":"","CATATAN":"Small Island","ID_TAMANLAUT":"01","TAMANLAUT":"Taman Laut Johor","AREA_KMSQ":0.14900417},{"PAGE_ROWNUM":4,"PAGE_TOTALROW":86,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":14,"KOD_NEGERI":"01","NEGERI":"Johor","KOD_DAERAH":"0105","DAERAH":"Mersing","KOD_MPA":"010506","KOD_PULAU":"01050601","PULAU":"Pulau Aur","WARTA_DATE":"1994-10-20T00:00:00","NO_WARTA":"P.U. (A) 401/94","AREA_HA":1441.93682532,"PETA_RUJUK":"PW 229","CARTA_MAL":"MAL 625","CATATAN":"Gazette Island","ID_TAMANLAUT":"01","TAMANLAUT":"Taman Laut Johor","AREA_KMSQ":14.42049810},{"PAGE_ROWNUM":5,"PAGE_TOTALROW":86,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":15,"KOD_NEGERI":"01","NEGERI":"Johor","KOD_DAERAH":"0105","DAERAH":"Mersing","KOD_MPA":"010508","KOD_PULAU":"01050801","PULAU":"Pulau Harimau","WARTA_DATE":"1994-10-20T00:00:00","NO_WARTA":"P.U. (A) 401/94","AREA_HA":16.41349125,"PETA_RUJUK":"L.4655 Peta Siri L7030/PW230","CARTA_MAL":"MAL 625","CATATAN":"Gazette Island","ID_TAMANLAUT":"01","TAMANLAUT":"Taman Laut Johor","AREA_KMSQ":0.16417522},{"PAGE_ROWNUM":6,"PAGE_TOTALROW":86,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":16,"KOD_NEGERI":"01","NEGERI":"Johor","KOD_DAERAH":"0105","DAERAH":"Mersing","KOD_MPA":"010510","KOD_PULAU":"01051001","PULAU":"Pulau Mensirip","WARTA_DATE":"1994-10-20T00:00:00","NO_WARTA":"P.U. (A) 401/94","AREA_HA":8.42969396,"PETA_RUJUK":"L.4655 Peta Siri L7030/PW230","CARTA_MAL":"MAL 625","CATATAN":"Gazette Island","ID_TAMANLAUT":"01","TAMANLAUT":"Taman Laut Johor","AREA_KMSQ":0.08431746},{"PAGE_ROWNUM":7,"PAGE_TOTALROW":86,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":17,"KOD_NEGERI":"01","NEGERI":"Johor","KOD_DAERAH":"0105","DAERAH":"Mersing","KOD_MPA":"010509","KOD_PULAU":"01050902","PULAU":"Pulau Kelabang","WARTA_DATE":null,"NO_WARTA":null,"AREA_HA":0.48913964,"PETA_RUJUK":null,"CARTA_MAL":null,"CATATAN":"Small Island","ID_TAMANLAUT":"01","TAMANLAUT":"Taman Laut Johor","AREA_KMSQ":0.00489259},{"PAGE_ROWNUM":8,"PAGE_TOTALROW":86,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":18,"KOD_NEGERI":"01","NEGERI":"Johor","KOD_DAERAH":"0105","DAERAH":"Mersing","KOD_MPA":"010509","KOD_PULAU":"01050901","PULAU":"Pulau Gual","WARTA_DATE":"1994-10-20T00:00:00","NO_WARTA":"P.U. (A) 401/94","AREA_HA":4.52421258,"PETA_RUJUK":"L.4655 Peta Siri L7030","CARTA_MAL":"MAL 625","CATATAN":"Gazette Island","ID_TAMANLAUT":"01","TAMANLAUT":"Taman Laut Johor","AREA_KMSQ":0.04525316},{"PAGE_ROWNUM":9,"PAGE_TOTALROW":86,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":19,"KOD_NEGERI":"01","NEGERI":"Johor","KOD_DAERAH":"0105","DAERAH":"Mersing","KOD_MPA":"010501","KOD_PULAU":"01050101","PULAU":"Pulau Rawa","WARTA_DATE":"1994-10-20T00:00:00","NO_WARTA":"P.U. (A) 401/94","AREA_HA":23.18767872,"PETA_RUJUK":"L.4655 Peta Siri L7030/PW230","CARTA_MAL":"MAL 625","CATATAN":"Gazette Island","ID_TAMANLAUT":"01","TAMANLAUT":"Taman Laut Johor","AREA_KMSQ":0.23193361},{"PAGE_ROWNUM":10,"PAGE_TOTALROW":86,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":20,"KOD_NEGERI":"01","NEGERI":"Johor","KOD_DAERAH":"0105","DAERAH":"Mersing","KOD_MPA":"010502","KOD_PULAU":"01050201","PULAU":"Pulau Babi Hujong","WARTA_DATE":"1994-10-20T00:00:00","NO_WARTA":"P.U. (A) 401/94","AREA_HA":55.14360465,"PETA_RUJUK":"L.4655 Peta Siri L7030/PW230","CARTA_MAL":"MAL 625","CATATAN":"Gazette Island","ID_TAMANLAUT":"01","TAMANLAUT":"Taman Laut Johor","AREA_KMSQ":0.55157709},{"PAGE_ROWNUM":11,"PAGE_TOTALROW":86,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":21,"KOD_NEGERI":"01","NEGERI":"Johor","KOD_DAERAH":"0105","DAERAH":"Mersing","KOD_MPA":"010503","KOD_PULAU":"01050301","PULAU":"Pulau Babi Tengah","WARTA_DATE":"1994-10-20T00:00:00","NO_WARTA":"P.U. (A) 401/94","AREA_HA":54.45259911,"PETA_RUJUK":"L.4655 Peta Siri L7030/PW230","CARTA_MAL":"MAL 625","CATATAN":"Gazette Island","ID_TAMANLAUT":"01","TAMANLAUT":"Taman Laut Johor","AREA_KMSQ":0.54466548},{"PAGE_ROWNUM":12,"PAGE_TOTALROW":86,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":22,"KOD_NEGERI":"01","NEGERI":"Johor","KOD_DAERAH":"0105","

In [ ]:
import requests
import pandas as pd
import json

BASE_URL = "https://myfirst.dof.gov.my"

headers = {
    "Authorization": f"Bearer {TOKEN}",
    "Accept": "application/json, text/plain, */*"
}

url = f"{BASE_URL}/myfirst/pengurusantamanlaut/tamanlautcarianrefugia"

params = {
    "kodnegeri": ""
}

r2 = requests.get(
    url,
    headers=headers,
    params=params,
    verify=False,
    timeout=30
)

print("Status:", r2.status_code)
print("URL:", r2.url)
print("Content-Type:", r2.headers.get("content-type"))
print(r2.text[:5000])

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'myfirst.dof.gov.my'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Status: 200
URL: https://myfirst.dof.gov.my/myfirst/pengurusantamanlaut/tamanlautcarianrefugia?kodnegeri=
Content-Type: application/json; charset=utf-8
{"refugia":[{"PAGE_ROWNUM":1,"PAGE_TOTALROW":2,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":3,"Kod_Negeri":null,"Negeri":"Johor","P_Kuasa":"Seksyen 8","Warta_Year":"2023","Lokasi":"Perairan Johor","Agensi":"Jabatan Perikanan Malaysia","Area_sqkm":1716.00000000,"Carta_MAL":"n/a","Nama":"Lobster Refugia Site","Catatan":"Had kawasan bagi Refugia Udang Karang adalah 1° 55.000’ Utara / 104° 30.000’ Timur, 2° 20.000’ Utara / 104° 30.000’ Timur, 2° 20.000’ Utara / 104° 50.000’ Timur, dan 1° 55.000’ Utara / 104° 50.000’ Timur."},{"PAGE_ROWNUM":2,"PAGE_TOTALROW":2,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":2,"Kod_Negeri":"13","Negeri":"Sarawak","P_Kuasa":"Seksyen 8","Warta_Year":"2023","Lokasi":"Perairan Kuala Baram","Agensi":"Jabatan Perikanan Malaysia","Area_sqkm":857.70000000,"Carta_MAL":"n/a","Nama":"Tiger Prawn Refugia Site","Catatan":"Had kawasan bagi Refugia Udang Harimau adalah 04° 35.40’Utara/  114° 3.84’Timur,  04° 42.30’Utara/ 114° 3.96’Timur,  04° 48.00’Utara/ 113° 58.08’Timur, 04° 34.74’Utara/ 113° 43.32’Timur, 04° 22.80’Utara 114° 0.60’ Timur & 04° 35.40’Utara 113° 59.16’ Timur"}]}

In [ ]:
import requests
import pandas as pd
import json

BASE_URL = "https://myfirst.dof.gov.my"

headers = {
    "Authorization": f"Bearer {TOKEN}",
    "Accept": "application/json, text/plain, */*"
}

url = f"{BASE_URL}/myfirst/pengurusantamanlaut/tamanlautcariankawasanlaranganperikanan"

params = {
    "kodnegeri": ""
}

r3 = requests.get(
    url,
    headers=headers,
    params=params,
    verify=False,
    timeout=30
)

print("Status:", r3.status_code)
print("URL:", r3.url)
print("Content-Type:", r3.headers.get("content-type"))
print(r3.text[:5000])

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'myfirst.dof.gov.my'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Status: 200
URL: https://myfirst.dof.gov.my/myfirst/pengurusantamanlaut/tamanlautcariankawasanlaranganperikanan?kodnegeri=
Content-Type: application/json; charset=utf-8
{"kawasan_larangan_perikanan":[{"PAGE_ROWNUM":1,"PAGE_TOTALROW":8,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":6,"Kod_Negeri":"04","Negeri":"Melaka","Punca_Kuasa":"Seksyen 61","Warta_Year":"1998","Nama_Kawasan":"Kawasan Larangan Perikanan","Lokasi":"Pulau Besar ","Agensi":"Jabatan Perikanan Malaysia","Carta_MAL":"521","Area_sqkm":22.00000000,"Catatan":"Perairan kelautan dalam kawasan satu batu nautika dari titik terluar Pulau Besar pada tikas air surut"},{"PAGE_ROWNUM":2,"PAGE_TOTALROW":8,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":9,"Kod_Negeri":"04","Negeri":"Melaka","Punca_Kuasa":"Seksyen 61","Warta_Year":"1998","Nama_Kawasan":"Kawasan Larangan Perikanan","Lokasi":"Perairan Tanjung Tuan","Agensi":"Jabatan Perikanan Malaysia","Carta_MAL":"532","Area_sqkm":12.30000000,"Catatan":"Perairan kelautan dalam kawasan satu batu nautika dari titik terluar Tanjung Tuan, Melaka yang diukur pada tikas air surut dari Garis Lintang 02°24.86'Utara, Garis Bujur 101°51.53'Timur hingga Garis Lintang 02°24.95'Utara, Garis Bujur 101°51.38'Timur"},{"PAGE_ROWNUM":3,"PAGE_TOTALROW":8,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":7,"Kod_Negeri":"05","Negeri":"Negeri Sembilan","Punca_Kuasa":"Seksyen 61","Warta_Year":"2002","Nama_Kawasan":"Kawasan Larangan Perikanan","Lokasi":"Perairan Tanjung Tuan 1","Agensi":"Jabatan Perikanan Malaysia","Carta_MAL":"532","Area_sqkm":7.50000000,"Catatan":"Perairan kelautan dalam kawasan satu batu nautika dari titik terluar Tanjung Tuan, Melaka yang diukur pada tikas air surut dari Garis Lintang 02°26.90'Utara, Garis Bujur 101°51.35'Timur hingga Garis Lintang 02°24.95'Utara, Garis Bujur 101°51.38'Timur"},{"PAGE_ROWNUM":4,"PAGE_TOTALROW":8,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":8,"Kod_Negeri":"05","Negeri":"Negeri Sembilan","Punca_Kuasa":"Seksyen 61","Warta_Year":"2002","Nama_Kawasan":"Kawasan Larangan Perikanan","Lokasi":"Perairan Tanjung Tuan 2","Agensi":"Jabatan Perikanan Malaysia","Carta_MAL":"532","Area_sqkm":12.10000000,"Catatan":"Perairan kelautan dalam kawasan satu batu nautika dari titik terluar Tanjung Tuan, Melaka yang diukur pada tikas air surut dari Garis Lintang 02°24.86'Utara, Garis Bujur 101°51.53'Timur hingga Garis Lintang 02°25.30'Utara, Garis Bujur 101°51.80'Timur"},{"PAGE_ROWNUM":5,"PAGE_TOTALROW":8,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":3,"Kod_Negeri":"13","Negeri":"Sarawak","Punca_Kuasa":"Seksyen 61","Warta_Year":"1994","Nama_Kawasan":"Kawasan Larangan Perikanan","Lokasi":"Pulau Talang-Talang Kecil","Agensi":"Jabatan Perikanan Malaysia","Carta_MAL":"723","Area_sqkm":37.30000000,"Catatan":"Perairan kelautan dalam kawasan dua batu nautika dari titik terluar diukur pada tikas air surut"},{"PAGE_ROWNUM":6,"PAGE_TOTALROW":8,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":4,"Kod_Negeri":"13","Negeri":"Sarawak","Punca_Kuasa":"Seksyen 61","Warta_Year":"1994","Nama_Kawasan":"Kawasan Larangan Perikanan","Lokasi":"Pulau Talang-Talang Besar ","Agensi":"Jabatan Perikanan Malaysia","Carta_MAL":"723","Area_sqkm":38.20000000,"Catatan":"Perairan kelautan dalam kawasan dua batu nautika dari titik terluar diukur pada tikas air surut"},{"PAGE_ROWNUM":7,"PAGE_TOTALROW":8,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":5,"Kod_Negeri":"13","Negeri":"Sarawak","Punca_Kuasa":"Seksyen 61","Warta_Year":"1994","Nama_Kawasan":"Kawasan Larangan Perikanan","Lokasi":"Pulau Satang Besar ","Agensi":"Jabatan Perikanan Malaysia","Carta_MAL":"731","Area_sqkm":65.60000000,"Catatan":"Perairan kelautan dalam kawasan dua batu nautika dari titik terluar diukur pada tikas air surut"},{"PAGE_ROWNUM":8,"PAGE_TOTALROW":8,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":2,"Kod_Negeri":"11","Negeri":"Terengganu","Punca_Kuasa":"Seksyen 61","Warta_Year":"1991","Nama_Kawasan":"Kawasan Larangan (Rantau Abang)","Lokasi":"Kuala Merchang dan Kg Kuala Abang (Tanjong Jara) & Perairan Rantau Abang","Agensi":"Jabatan Perikanan Malaysia","Carta_MAL":"654","Area_sqkm":513.80000000,"Catatan":"Test"}]}

In [ ]:
import requests
import pandas as pd
import json

BASE_URL = "https://myfirst.dof.gov.my"

headers = {
    "Authorization": f"Bearer {TOKEN}",
    "Accept": "application/json, text/plain, */*"
}

url = f"{BASE_URL}/myfirst/pengurusantamanlaut/tamanlautcarianzonkonservasi"

params = {
    "kodnegeri": ""
}

r4 = requests.get(
    url,
    headers=headers,
    params=params,
    verify=False,
    timeout=30
)

print("Status:", r4.status_code)
print("URL:", r4.url)
print("Content-Type:", r4.headers.get("content-type"))
print(r4.text[:5000])

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'myfirst.dof.gov.my'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Status: 200
URL: https://myfirst.dof.gov.my/myfirst/pengurusantamanlaut/tamanlautcarianzonkonservasi?kodnegeri=
Content-Type: application/json; charset=utf-8
{"zon_konservasi":[{"PAGE_ROWNUM":1,"PAGE_TOTALROW":2,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":3,"Kod_Negeri":"02","Negeri":"Kedah","P_Kuasa":"Syarat Lesen","Warta_Year":" ","Lokasi":"Kedah","Agensi":"Jabatan Perikanan Malaysia","Area_sqkm":663.07600000,"Carta_MAL":" ","Catatan":"1bn dari pantai Negeri Kedah"},{"PAGE_ROWNUM":2,"PAGE_TOTALROW":2,"PAGE":1,"PAGE_TOTAL":1,"OBJECTID":2,"Kod_Negeri":"08","Negeri":"Perak","P_Kuasa":"Syarat Lesen","Warta_Year":" ","Lokasi":"Perak","Agensi":"Jabatan Perikanan Malaysia","Area_sqkm":570.89500000,"Carta_MAL":" ","Catatan":"1bn dari pantai Negeri Perak"}]}

In [ ]:
result = r.json()
result2 = r2.json()
result3 = r3.json()
result4 = r4.json()
island = result.get("pulau")
refugia = result2.get("refugia")
other = result3.get("kawasan_larangan_perikanan")
conservatory = result4.get("zon_konservasi")

df_island = pd.DataFrame(island)
df_refugia = pd.DataFrame(refugia)
df_other = pd.DataFrame(other)
df_conservatory = pd.DataFrame(conservatory)

df_island.columns = df_island.columns.str.lower()
df_refugia.columns = df_refugia.columns.str.lower()
df_other.columns = df_other.columns.str.lower()
df_conservatory.columns = df_conservatory.columns.str.lower()

df_island['mpa_type'] = 'Island'
df_refugia['mpa_type'] = 'Refugia'
df_other['mpa_type'] = 'Fishery Prohibited Area'
df_conservatory['mpa_type'] = 'Conservatory'

df_mpa = pd.concat([df_island, df_refugia, df_other, df_conservatory], ignore_index=True)
df_mpa

,page_rownum,page_totalrow,page,page_total,objectid,kod_negeri,negeri,kod_daerah,daerah,kod_mpa,...,area_kmsq,mpa_type,p_kuasa,warta_year,lokasi,agensi,area_sqkm,nama,punca_kuasa,nama_kawasan
0,1,86,1,1,11,01,Johor,0105,Mersing,010506,...,1.337897,Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,86,1,1,12,01,Johor,0105,Mersing,010506,...,0.056778,Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,86,1,1,13,01,Johor,0105,Mersing,010506,...,0.149004,Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,86,1,1,14,01,Johor,0105,Mersing,010506,...,14.420498,Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,86,1,1,15,01,Johor,0105,Mersing,010508,...,0.164175,Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,6,8,1,1,4,13,Sarawak,NaN,NaN,NaN,...,NaN,Fishery Prohibited Area,NaN,1994,Pulau Talang-Talang Besar,Jabatan Perikanan Malaysia,38.200,NaN,Seksyen 61,Kawasan Larangan Perikanan
94,7,8,1,1,5,13,Sarawak,NaN,NaN,NaN,...,NaN,Fishery Prohibited Area,NaN,1994,Pulau Satang Besar,Jabatan Perikanan Malaysia,65.600,NaN,Seksyen 61,Kawasan Larangan Perikanan
95,8,8,1,1,2,11,Terengganu,NaN,NaN,NaN,...,NaN,Fishery Prohibited Area,NaN,1991,Kuala Merchang dan Kg Kuala Abang (Tanjong Jar...,Jabatan Perikanan Malaysia,513.800,NaN,Seksyen 61,Kawasan Larangan (Rantau Abang)
96,1,2,1,1,3,02,Kedah,NaN,NaN,NaN,...,NaN,Conservatory,Syarat Lesen,,Kedah,Jabatan Perikanan Malaysia,663.076,NaN,NaN,NaN
97,2,2,1,1,2,08,Perak,NaN,NaN,NaN,...,NaN,Conservatory,Syarat Lesen,,Perak,Jabatan Perikanan Malaysia,570.895,NaN,NaN,NaN

In [ ]:
df_mpa.columns

Index(['page_rownum', 'page_totalrow', 'page', 'page_total', 'objectid',
       'kod_negeri', 'negeri', 'kod_daerah', 'daerah', 'kod_mpa', 'kod_pulau',
       'pulau', 'warta_date', 'no_warta', 'area_ha', 'peta_rujuk', 'carta_mal',
       'catatan', 'id_tamanlaut', 'tamanlaut', 'area_kmsq', 'mpa_type',
       'p_kuasa', 'warta_year', 'lokasi', 'agensi', 'area_sqkm', 'nama',
       'punca_kuasa', 'nama_kawasan'],
      dtype='object')

In [ ]:
area_from_ha = df_mpa['area_ha'] / 100

df_mpa['area_km2'] = df_mpa['area_kmsq'].fillna(df_mpa['area_sqkm']).fillna(area_from_ha)

df_mpa['area_name'] = df_mpa['nama'].fillna(df_mpa['nama_kawasan']).fillna(df_mpa['pulau'])

df_mpa['legal_authority'] = df_mpa['p_kuasa'].fillna(df_mpa['punca_kuasa'])

df_mpa = df_mpa.drop(columns=['area_kmsq', 'area_sqkm', 'area_ha', 'page_rownum', 'page_totalrow', 'page', 'page_total', 'objectid', 'nama', 'nama_kawasan', 'pulau', 'p_kuasa', 'punca_kuasa'])

In [ ]:
df_mpa.columns

Index(['kod_negeri', 'negeri', 'kod_daerah', 'daerah', 'kod_mpa', 'kod_pulau',
       'warta_date', 'no_warta', 'peta_rujuk', 'carta_mal', 'catatan',
       'id_tamanlaut', 'tamanlaut', 'mpa_type', 'warta_year', 'lokasi',
       'agensi', 'area_km2', 'area_name', 'legal_authority'],
      dtype='object')

In [ ]:
# Rename columns to standard English
column_mapping = {
    'negeri': 'state',
    'kod_negeri': 'state_code',
    'daerah': 'district',
    'kod_daerah': 'district_code',
    'pulau': 'island',
    'kod_pulau': 'island_code',
    'kod_mpa': 'mpa_code',
    'peta_rujuk': 'map_link',
    'tamanlaut': 'marine_park',
    'id_tamanlaut': 'marine_park_id',
    'lokasi': 'location',
    'agensi': 'agency',
    'nama': 'name',
    'catatan': 'notes',
    'warta_date': 'gazetted_date',
    'warta_year': 'gazetted_year',
    'no_warta': 'gazette_number'
}

df_mpa = df_mpa.rename(columns=column_mapping)

In [ ]:
code_widths = {
    "state_code": 2,
    "district_code": 4,
    "mpa_code": 6,
    "island_code": 8,
    "marine_park_id": 2
}

for col, width in code_widths.items():
    if col in df_mpa.columns:
        df_mpa[col] = (
            df_mpa[col]
            .astype("string")
            .str.strip()
            .str.replace(r"\.0$", "", regex=True)
            .str.zfill(width)
        )

In [ ]:
df_mpa.to_csv("mpa_all.csv", index=False)

In [ ]:
df_mpa

,state_code,state,district_code,district,mpa_code,island_code,gazetted_date,gazette_number,map_link,carta_mal,notes,marine_park_id,marine_park,mpa_type,gazetted_year,location,agency,area_km2,area_name,legal_authority
0,01,Johor,0105,Mersing,010506,01050602,None,None,None,None,Small Island,01,Taman Laut Johor,Island,NaN,NaN,NaN,1.337897,Pulau Duyung,NaN
1,01,Johor,0105,Mersing,010506,01050603,None,None,None,None,Small Island,01,Taman Laut Johor,Island,NaN,NaN,NaN,0.056778,Pulau Lang,NaN
2,01,Johor,0105,Mersing,010506,01050604,None,,,,Small Island,01,Taman Laut Johor,Island,NaN,NaN,NaN,0.149004,Pulau Pinang,NaN
3,01,Johor,0105,Mersing,010506,01050601,1994-10-20T00:00:00,P.U. (A) 401/94,PW 229,MAL 625,Gazette Island,01,Taman Laut Johor,Island,NaN,NaN,NaN,14.420498,Pulau Aur,NaN
4,01,Johor,0105,Mersing,010508,01050801,1994-10-20T00:00:00,P.U. (A) 401/94,L.4655 Peta Siri L7030/PW230,MAL 625,Gazette Island,01,Taman Laut Johor,Island,NaN,NaN,NaN,0.164175,Pulau Harimau,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,13,Sarawak,<NA>,NaN,<NA>,<NA>,NaN,NaN,NaN,723,Perairan kelautan dalam kawasan dua batu nauti...,<NA>,NaN,Fishery Prohibited Area,1994,Pulau Talang-Talang Besar,Jabatan Perikanan Malaysia,38.200000,Kawasan Larangan Perikanan,Seksyen 61
94,13,Sarawak,<NA>,NaN,<NA>,<NA>,NaN,NaN,NaN,731,Perairan kelautan dalam kawasan dua batu nauti...,<NA>,NaN,Fishery Prohibited Area,1994,Pulau Satang Besar,Jabatan Perikanan Malaysia,65.600000,Kawasan Larangan Perikanan,Seksyen 61
95,11,Terengganu,<NA>,NaN,<NA>,<NA>,NaN,NaN,NaN,654,Test,<NA>,NaN,Fishery Prohibited Area,1991,Kuala Merchang dan Kg Kuala Abang (Tanjong Jar...,Jabatan Perikanan Malaysia,513.800000,Kawasan Larangan (Rantau Abang),Seksyen 61
96,02,Kedah,<NA>,NaN,<NA>,<NA>,NaN,NaN,NaN,,1bn dari pantai Negeri Kedah,<NA>,NaN,Conservatory,,Kedah,Jabatan Perikanan Malaysia,663.076000,NaN,Syarat Lesen
97,08,Perak,<NA>,NaN,<NA>,<NA>,NaN,NaN,NaN,,1bn dari pantai Negeri Perak,<NA>,NaN,Conservatory,,Perak,Jabatan Perikanan Malaysia,570.895000,NaN,Syarat Lesen

## start

In [ ]:
import pandas as pd
import numpy as np

mpa = pd.read_csv(
    "/content/mpa_all.csv",
    dtype={
        "state_code": "string",
        "district_code": "string",
        "mpa_code": "string",
        "island_code": "string",
        "marine_park_id": "string",
    })

# -------------------------
# 1. Clean blank strings
# -------------------------

object_cols = mpa.select_dtypes(include="object").columns

for col in object_cols:
    mpa[col] = (
        mpa[col]
        .astype("string")
        .str.strip()
        .replace(["", "NA", "N/A", "None", "<NA>"], pd.NA)
    )


# -------------------------
# 2. Standardise states
# -------------------------

state_map = {
    "W.P Labuan": "Labuan",
}

mpa["state"] = mpa["state"].replace(state_map)

# -------------------------
# 4. Fix known missing Johor code
# -------------------------

mpa.loc[
    (mpa["state"] == "Johor")
    & mpa["state_code"].isna(),
    "state_code"
] = "1"


# -------------------------
# 5. Clean dates
# -------------------------

mpa["gazetted_date"] = pd.to_datetime(
    mpa["gazetted_date"],
    errors="coerce"
)

mpa["gazetted_year"] = pd.to_numeric(
    mpa["gazetted_year"],
    errors="coerce"
).astype("Int64")


# Derive year from gazetted date where possible
mpa["gazetted_year_clean"] = (
    mpa["gazetted_year"]
    .fillna(mpa["gazetted_date"].dt.year)
    .astype("Int64")
)

In [ ]:
mpa["MPA_NAME"] = np.where(
    mpa["mpa_type"] == "Island",
    mpa["area_name"],
    mpa["location"]
)

mpa["MPA_NAME"] = (
    pd.Series(mpa["MPA_NAME"], index=mpa.index)
    .astype("string")
    .str.strip()
)

In [ ]:
mpa["MPA_ID"] = [
    f"MPA_{i:03d}"
    for i in range(1, len(mpa) + 1)
]

In [ ]:
print(mpa.columns.tolist())

print("\nRows:", len(mpa))

for col in [
    "map_link",
    "carta_mal",
    "notes",
    "location",
    "area_name"
]:
    if col in mpa.columns:
        print(
            f"{col}:",
            mpa[col].notna().sum(),
            "non-null"
        )

['state_code', 'state', 'district_code', 'district', 'mpa_code', 'island_code', 'gazetted_date', 'gazette_number', 'map_link', 'carta_mal', 'notes', 'marine_park_id', 'marine_park', 'mpa_type', 'gazetted_year', 'location', 'agency', 'area_km2', 'area_name', 'legal_authority', 'gazetted_year_clean', 'MPA_NAME', 'MPA_ID']

Rows: 98
map_link: 42 non-null
carta_mal: 61 non-null
notes: 98 non-null
location: 12 non-null
area_name: 96 non-null

In [ ]:
import re

coord_pattern = (
    r"\d{1,3}[°º]\s*\d{1,2}['′]?\s*"
    r"(?:\d{1,2}(?:\.\d+)?)?[\"″]?\s*[NSEW]"
)

for col in ["notes", "location", "map_link"]:
    if col in mpa.columns:

        matches = mpa[
            mpa[col]
            .astype("string")
            .str.contains(
                coord_pattern,
                regex=True,
                na=False
            )
        ]

        print(
            col,
            "rows containing possible coordinates:",
            len(matches)
        )

notes rows containing possible coordinates: 0
location rows containing possible coordinates: 0
map_link rows containing possible coordinates: 0

In [ ]:
display(mpa)

,state_code,state,district_code,district,mpa_code,island_code,gazetted_date,gazette_number,map_link,carta_mal,...,mpa_type,gazetted_year,location,agency,area_km2,area_name,legal_authority,gazetted_year_clean,MPA_NAME,MPA_ID
0,01,Johor,0105,Mersing,010506,01050602,NaT,<NA>,<NA>,<NA>,...,Island,<NA>,<NA>,<NA>,1.337897,Pulau Duyung,<NA>,<NA>,Pulau Duyung,MPA_001
1,01,Johor,0105,Mersing,010506,01050603,NaT,<NA>,<NA>,<NA>,...,Island,<NA>,<NA>,<NA>,0.056778,Pulau Lang,<NA>,<NA>,Pulau Lang,MPA_002
2,01,Johor,0105,Mersing,010506,01050604,NaT,<NA>,<NA>,<NA>,...,Island,<NA>,<NA>,<NA>,0.149004,Pulau Pinang,<NA>,<NA>,Pulau Pinang,MPA_003
3,01,Johor,0105,Mersing,010506,01050601,1994-10-20,P.U. (A) 401/94,PW 229,MAL 625,...,Island,<NA>,<NA>,<NA>,14.420498,Pulau Aur,<NA>,1994,Pulau Aur,MPA_004
4,01,Johor,0105,Mersing,010508,01050801,1994-10-20,P.U. (A) 401/94,L.4655 Peta Siri L7030/PW230,MAL 625,...,Island,<NA>,<NA>,<NA>,0.164175,Pulau Harimau,<NA>,1994,Pulau Harimau,MPA_005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,13,Sarawak,<NA>,<NA>,<NA>,<NA>,NaT,<NA>,<NA>,723,...,Fishery Prohibited Area,1994,Pulau Talang-Talang Besar,Jabatan Perikanan Malaysia,38.200000,Kawasan Larangan Perikanan,Seksyen 61,1994,Pulau Talang-Talang Besar,MPA_094
94,13,Sarawak,<NA>,<NA>,<NA>,<NA>,NaT,<NA>,<NA>,731,...,Fishery Prohibited Area,1994,Pulau Satang Besar,Jabatan Perikanan Malaysia,65.600000,Kawasan Larangan Perikanan,Seksyen 61,1994,Pulau Satang Besar,MPA_095
95,11,Terengganu,<NA>,<NA>,<NA>,<NA>,NaT,<NA>,<NA>,654,...,Fishery Prohibited Area,1991,Kuala Merchang dan Kg Kuala Abang (Tanjong Jar...,Jabatan Perikanan Malaysia,513.800000,Kawasan Larangan (Rantau Abang),Seksyen 61,1991,Kuala Merchang dan Kg Kuala Abang (Tanjong Jar...,MPA_096
96,02,Kedah,<NA>,<NA>,<NA>,<NA>,NaT,<NA>,<NA>,<NA>,...,Conservatory,<NA>,Kedah,Jabatan Perikanan Malaysia,663.076000,<NA>,Syarat Lesen,<NA>,Kedah,MPA_097
97,08,Perak,<NA>,<NA>,<NA>,<NA>,NaT,<NA>,<NA>,<NA>,...,Conservatory,<NA>,Perak,Jabatan Perikanan Malaysia,570.895000,<NA>,Syarat Lesen,<NA>,Perak,MPA_098

In [ ]:
mpa.to_csv("mpa_all_cleaned.csv", index=False)

In [ ]:
TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJqaXJ1aTMyQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoiamlydWkzMkBnbWFpbC5jb20iLCJyb2xlIjoiMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvdXNlcmRhdGEiOiIiLCJlbWFpbCI6ImppcnVpMzJAZ21haWwuY29tIiwibGFzdHBhc3N3b3JkcmVzZXQiOiIiLCJuYmYiOjE3ODk4MzY0MzAsImV4cCI6MTc4OTgzNzMzMCwiaWF0IjoxNzg5ODM2NDMwfQ.tiK0K7FoSNGdF_eJ5CDeRU8LGjV_odHGIx04rwOLR7I"

In [ ]:
import requests
import json
import os

TOKEN = TOKEN

BASE_APP = "https://myfirst.dof.gov.my"
BASE_ARCGIS = (
    "https://myfirst.dof.gov.my/"
    "arcgis/rest/services/MYFIRST_TL"
)

session = requests.Session()

# 1. Authenticate against MyFiRSt
session.headers.update({
    "Authorization": f"Bearer {TOKEN}",
    "Accept": "application/json, text/plain, */*"
})

auth_url = (
    f"{BASE_APP}/myfirst/"
    "pengurusantamanlaut/"
    "tamanlautcarianpulau"
)

r = session.get(
    auth_url,
    params={"kodnegeri": ""},
    verify=False,
    timeout=30
)

print("MyFiRSt:", r.status_code)
print("Response:", r.text[:500])
print("Cookies:", [c.name for c in session.cookies])

# 2. Remove JWT before ArcGIS
session.headers.pop("Authorization", None)

session.headers.update({
    "Accept": "*/*",
    "Referer": (
        "https://myfirst.dof.gov.my/"
        "PengurusanTamanLaut/submodul/"
        "penyediaan_maklumat_umum_kawasan_perlindungan_marin"
    )
})

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'myfirst.dof.gov.my'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

MyFiRSt: 401
Response: {"message":"Invalid token"}
Cookies: []

In [ ]:
services = {
    "marine_park_islands": "MU_PulauTamanLaut",
    "marine_park_boundary": "MU_SempadanTamanLaut",
    "refugia": "MU_Refugia",
    "fishery_prohibited_area": "MU_LaranganPerikanan",
    "conservatory": "MU_ZonKonservasiLaut"
}

In [ ]:
for name, service in services.items():

    url = f"{BASE_ARCGIS}/{service}/MapServer"

    meta = session.get(
        url,
        params={"f": "pjson"},
        verify=False,
        timeout=60
    ).json()

    print("\n====================")
    print(name)
    print("====================")

    print(meta.get("layers"))

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'myfirst.dof.gov.my'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

ReadTimeout: HTTPSConnectionPool(host='myfirst.dof.gov.my', port=443): Read timed out. (read timeout=60)

In [ ]:
os.makedirs("/content/mpa_spatial", exist_ok=True)

for name, service in services.items():

    url = (
        f"{BASE_ARCGIS}/"
        f"{service}/MapServer/0/query"
    )

    params = {
        "where": "1=1",
        "outFields": "*",
        "returnGeometry": "true",
        "outSR": "4326",
        "f": "geojson"
    }

    print("\nDownloading:", name)

    r = session.get(
        url,
        params=params,
        verify=False,
        timeout=120
    )

    try:
        data = r.json()
    except Exception:
        print("Not JSON")
        print(r.text[:500])
        continue

    if "error" in data:
        print("ArcGIS error:")
        print(json.dumps(data["error"], indent=2))
        continue

    if data.get("type") != "FeatureCollection":
        print("Unexpected response")
        print(json.dumps(data, indent=2)[:1000])
        continue

    features = data.get("features", [])

    print("Features:", len(features))

    output = (
        f"/content/mpa_spatial/"
        f"{name}.geojson"
    )

    with open(
        output,
        "w",
        encoding="utf-8"
    ) as f:
        json.dump(data, f)

    print("Saved:", output)

Downloading: marine_park_islands

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'myfirst.dof.gov.my'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
WARNING:urllib3.connectionpool:Retrying (Retry(total=4, connect=5, read=4, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='myfirst.dof.gov.my', port=443): Read timed out. (read timeout=120)")': /arcgis/rest/services/MYFIRST_TL/MU_PulauTamanLaut/MapServer/0/query?where=1%3D1&outFields=%2A&returnGeometry=true&outSR=4326&f=geojson
/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'myfirst.dof.gov.my'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

KeyboardInterrupt:

In [ ]:
import geopandas as gpd
import os

for file in sorted(
    os.listdir("/content/mpa_spatial")
):

    if not file.endswith(".geojson"):
        continue

    path = (
        f"/content/mpa_spatial/{file}"
    )

    gdf = gpd.read_file(path)

    print("\n========================")
    print(file)
    print("========================")

    print("Rows:", len(gdf))
    print("CRS:", gdf.crs)

    print("\nGeometry:")
    print(
        gdf.geometry
        .geom_type
        .value_counts()
    )

    print("\nColumns:")
    print(gdf.columns.tolist())

    print("\nSample attributes:")

    display(
        gdf
        .drop(columns="geometry")
        .head(3)
    )

In [ ]:
import pandas as pd
import geopandas as gpd
import re

mpa = pd.read_csv(
          "/content/mpa_all_cleaned.csv",
          dtype={
          "state_code": "string",
          "district_code": "string",
          "mpa_code": "string",
          "island_code": "string",
          "marine_park_id": "string",
      })

islands_geo = gpd.read_file(
    "/content/mpa_spatial/marine_park_islands.geojson"
)

fishery_geo = gpd.read_file(
    "/content/mpa_spatial/fishery_prohibited_area.geojson"
)

refugia_geo = gpd.read_file(
    "/content/mpa_spatial/refugia.geojson"
)

conservatory_geo = gpd.read_file(
    "/content/mpa_spatial/conservatory.geojson"
)

marine_park_boundary = gpd.read_file(
    "/content/mpa_spatial/marine_park_boundary.geojson"
)

In [ ]:
csv_codes = set(
    mpa.loc[
        mpa["mpa_type"] == "Island",
        "island_code"
    ].dropna()
)

geo_codes = set(
    islands_geo["Kod_Pulau"].dropna()
)

print("CSV island codes:", len(csv_codes))
print("ArcGIS island codes:", len(geo_codes))

print(
    "In CSV but not ArcGIS:",
    csv_codes - geo_codes
)

print(
    "In ArcGIS but not CSV:",
    geo_codes - csv_codes
)

In [ ]:
mpa_islands = (
    mpa[
        mpa["mpa_type"] == "Island"
    ]
    .merge(
        islands_geo[
            [
                "Kod_Pulau",
                "geometry"
            ]
        ],
        left_on="island_code",
        right_on="Kod_Pulau",
        how="left",
        validate="one_to_one"
    )
)

print("Island rows:", len(mpa_islands))
print(
    "Missing geometry:",
    mpa_islands["geometry"].isna().sum()
)

In [ ]:
import re
import pandas as pd

def normalize_text(x):
    if pd.isna(x):
        return pd.NA

    x = str(x).upper().strip()
    x = re.sub(r"[^A-Z0-9]+", " ", x)
    x = re.sub(r"\s+", " ", x).strip()

    return x


# Keys in your cleaned MPA table
mpa["_STATE_KEY"] = mpa["state"].apply(normalize_text)
mpa["_LOCATION_KEY"] = mpa["location"].apply(normalize_text)


# Keys in ArcGIS layers
for gdf in [
    fishery_geo,
    refugia_geo,
    conservatory_geo
]:
    gdf["_STATE_KEY"] = gdf["Negeri"].apply(normalize_text)
    gdf["_LOCATION_KEY"] = gdf["Lokasi"].apply(normalize_text)

In [ ]:
mpa_fishery = (
    mpa[
        mpa["mpa_type"] == "Fishery Prohibited Area"
    ]
    .merge(
        fishery_geo[
            [
                "_STATE_KEY",
                "_LOCATION_KEY",
                "Area_sqkm",
                "geometry"
            ]
        ].rename(
            columns={
                "Area_sqkm": "arcgis_area_km2"
            }
        ),
        on=[
            "_STATE_KEY",
            "_LOCATION_KEY"
        ],
        how="left",
        validate="one_to_one"
    )
)

print("Fishery rows:", len(mpa_fishery))
print(
    "Missing geometry:",
    mpa_fishery["geometry"].isna().sum()
)

In [ ]:
mpa_refugia = (
    mpa[
        mpa["mpa_type"] == "Refugia"
    ]
    .merge(
        refugia_geo[
            [
                "_STATE_KEY",
                "_LOCATION_KEY",
                "Area_sqkm",
                "geometry"
            ]
        ].rename(
            columns={
                "Area_sqkm": "arcgis_area_km2"
            }
        ),
        on=[
            "_STATE_KEY",
            "_LOCATION_KEY"
        ],
        how="left",
        validate="one_to_one"
    )
)

print("Refugia rows:", len(mpa_refugia))
print(
    "Missing geometry:",
    mpa_refugia["geometry"].isna().sum()
)

In [ ]:
mpa_conservatory = (
    mpa[
        mpa["mpa_type"] == "Conservatory"
    ]
    .merge(
        conservatory_geo[
            [
                "_STATE_KEY",
                "_LOCATION_KEY",
                "Area_sqkm",
                "geometry"
            ]
        ].rename(
            columns={
                "Area_sqkm": "arcgis_area_km2"
            }
        ),
        on=[
            "_STATE_KEY",
            "_LOCATION_KEY"
        ],
        how="left",
        validate="one_to_one"
    )
)

print("Conservatory rows:", len(mpa_conservatory))
print(
    "Missing geometry:",
    mpa_conservatory["geometry"].isna().sum()
)

In [ ]:
mpa_islands = (
    mpa[
        mpa["mpa_type"] == "Island"
    ]
    .merge(
        islands_geo[
            [
                "Kod_Pulau",
                "Area_Kmsq",
                "geometry"
            ]
        ].rename(
            columns={
                "Area_Kmsq": "arcgis_area_km2"
            }
        ),
        left_on="island_code",
        right_on="Kod_Pulau",
        how="left",
        validate="one_to_one"
    )
)

In [ ]:
mpa_islands["area_difference"] = (
    mpa_islands["area_km2"]
    - mpa_islands["arcgis_area_km2"]
)

print(
    mpa_islands["area_difference"]
    .abs()
    .describe()
)

In [ ]:
import geopandas as gpd

mpa_geo = pd.concat(
    [
        mpa_islands,
        mpa_fishery,
        mpa_refugia,
        mpa_conservatory
    ],
    ignore_index=True
)

mpa_geo = gpd.GeoDataFrame(
    mpa_geo,
    geometry="geometry",
    crs="EPSG:4326"
)

In [ ]:
print("Total rows:", len(mpa_geo))

print("\nMPA types:")
print(
    mpa_geo["mpa_type"]
    .value_counts()
)

print(
    "\nMissing geometry:",
    mpa_geo.geometry.isna().sum()
)

print("\nGeometry types:")
print(
    mpa_geo.geometry
    .geom_type
    .value_counts()
)

print(
    "\nInvalid geometry:",
    (~mpa_geo.geometry.is_valid).sum()
)

In [ ]:
mpa_geo = mpa_geo.drop(
    columns=[
        "Kod_Pulau",
        "_STATE_KEY",
        "_LOCATION_KEY"
    ],
    errors="ignore"
)

In [ ]:
mpa_geo["geometry_source"] = "MyFiRSt ArcGIS"

In [ ]:
mpa_geo.to_file(
    "/content/mpa_master_geo.geojson",
    driver="GeoJSON"
)

mpa_geo.to_file(
    "/content/mpa_master_geo.gpkg",
    layer="mpa_sites",
    driver="GPKG"
)

In [ ]:
mpa_geo

#MQIMS

In [ ]:
!pip install pdfplumber

Collecting pdfplumber
  Downloading pdfplumber-0.11.10-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 1.7 MB/s eta 0:00:00
Collecting pdfminer.six==20260107 (from pdfplumber)
  Downloading pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Collecting Pillow>=12.2.0 (from pdfplumber)
  Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting pypdfium2>=5.9.0 (from pdfplumber)
  Downloading pypdfium2-5.13.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 5.5 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (3.4.9)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.13/dist-packages (from pdfminer.six==20260107->pdfplumber) (50.0.1)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)
Downloading pdfplumber-0.11.10-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 6.4 MB/s eta 0:00:00
Downloading pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 71.3 MB/s eta 0:00:00
Downloading pillow-12.3.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 97.8 MB/s eta 0:00:00
Downloading pypdfium2-5.13.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 106.5 MB/s eta 0:00:00
Installing collected packages: pypdfium2, Pillow, pdfminer.six, pdfplumber
  Attempting uninstall: Pillow
    Found existing installation: pillow 11.3.0
    Uninstalling pillow-11.3.0:
      Successfully uninstalled pillow-11.3.0
Successfully installed Pillow-12.3.0 pdfminer.six-20260107 pdfplumber-0.11.10 pypdfium2-5.13.0

In [ ]:
import pdfplumber
import pandas as pd
import os
import re

TABLE_TITLES = {
    "Coastal": [
        "marine water quality status for coastal"
    ],

    "Estuary": [
        "marine water quality status for estuary",
        "marine water quality status for estuaries"
    ],

    "Island": [
        "marine water quality status for island",
        "marine water quality status for islands"
    ]
}


def is_real_mwqi_table(table):
    if not table or len(table) < 3:
        return False

    header_text = " ".join(
        str(cell)
        for row in table[:3]
        for cell in row
        if cell is not None
    )

    header_text = re.sub(r"\s+", " ", header_text).upper()

    # Common features of real station tables
    has_station = (
        "STATION" in header_text
        or "STESEN" in header_text
    )

    has_mwqi = (
        "MWQI" in header_text
        or "MMWQI" in header_text
    )

    # At least one year from our historical period
    has_year = bool(
        re.search(r"\b20(?:1[3-9]|2[0-5])\b", header_text)
    )

    return has_station and has_mwqi and has_year


def detect_mwqi_table(text):
    """Return Coastal, Estuary, Island, or None."""
    if not text:
        return None

    # Normalize whitespace because PDF extraction may insert line breaks
    clean = re.sub(r"\s+", " ", text).lower()

    for category, titles in TABLE_TITLES.items():
      for title in titles:
        if title in clean:
            return category

    return None


def extract_mwqi_tables(pdf_path):
    results = []

    with pdfplumber.open(pdf_path) as pdf:

        print(f"\nScanning: {os.path.basename(pdf_path)}")

        for page_num, page in enumerate(pdf.pages, start=1):

            text = page.extract_text() or ""
            category = detect_mwqi_table(text)

            # Not one of our tables
            if category is None:
                continue

            print(
                f"✓ Page {page_num}: "
                f"Marine Water Quality Status for {category}"
            )

            tables = page.extract_tables()

            for table_num, table in enumerate(tables):

                if not is_real_mwqi_table(table):
                    print(
                        f"  ✗ Skipping table {table_num} "
                        f"(not a station MWQI table)"
                    )
                    continue

                temp = pd.DataFrame(table)

                temp["CATEGORY"] = category
                temp["PDF_PAGE"] = page_num
                temp["TABLE_NUM"] = table_num
                temp["SOURCE_FILE"] = os.path.basename(pdf_path)

                results.append(temp)

                print(
                    f"  ✓ Extracted table {table_num}: "
                    f"{len(temp)-2} station rows"
                )

        return results


def convert_2013_2015_table(raw, category, source_file):

    df = raw.iloc[2:, :8].copy()

    df.columns = [
        "STATE_NAME",
        "STATION_CLASSIFICATION",
        "STATION_LOCATION",
        "OLD_STATION_ID",
        "2013",
        "2014",
        "2015",
        "STATUS_2015"
    ]

    text_cols = [
        "STATE_NAME",
        "STATION_CLASSIFICATION",
        "STATION_LOCATION",
        "OLD_STATION_ID"
    ]

    for col in text_cols:
        df[col] = (
            df[col]
            .astype("string")
            .str.replace("\n", " ", regex=False)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

    # Missing states are caused by merged PDF cells
    df["STATE_NAME"] = df["STATE_NAME"].replace(
        ["", "None", "<NA>"], pd.NA
    )

    df["STATE_NAME"] = df["STATE_NAME"].ffill()

    # No new MM... ID yet
    df["STATION_ID"] = pd.NA

    df = df.melt(
        id_vars=[
            "STATE_NAME",
            "STATION_CLASSIFICATION",
            "STATION_LOCATION",
            "OLD_STATION_ID",
            "STATION_ID"
        ],
        value_vars=["2013", "2014", "2015"],
        var_name="YEAR",
        value_name="MWQI"
    )

    df["YEAR"] = df["YEAR"].astype(int)

    df["MWQI"] = pd.to_numeric(
        df["MWQI"].replace("-", pd.NA),
        errors="coerce"
    )

    df["CATEGORY"] = category
    df["SOURCE_FILE"] = source_file

    return df


def convert_2016_2020_table(raw, category, source_file):

    df = raw.iloc[2:, :11].copy()

    df.columns = [
        "STATE_NAME",
        "STATION_CLASSIFICATION",
        "STATION_LOCATION",
        "OLD_STATION_ID",
        "STATION_ID",
        "2016",
        "2017",
        "2018",
        "2019",
        "2020",
        "STATUS_2020"
    ]

    text_cols = [
        "STATE_NAME",
        "STATION_CLASSIFICATION",
        "STATION_LOCATION",
        "OLD_STATION_ID",
        "STATION_ID"
    ]

    for col in text_cols:
        df[col] = (
            df[col]
            .astype("string")
            .str.replace("\n", " ", regex=False)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

    df["STATE_NAME"] = df["STATE_NAME"].replace(
        ["", "None", "<NA>"], pd.NA
    )

    df["STATE_NAME"] = df["STATE_NAME"].ffill()

    df = df.melt(
        id_vars=[
            "STATE_NAME",
            "STATION_CLASSIFICATION",
            "STATION_LOCATION",
            "OLD_STATION_ID",
            "STATION_ID"
        ],
        value_vars=[
            "2016",
            "2017",
            "2018",
            "2019",
            "2020"
        ],
        var_name="YEAR",
        value_name="MWQI"
    )

    df["YEAR"] = df["YEAR"].astype(int)

    df["MWQI"] = pd.to_numeric(
        df["MWQI"].replace("-", pd.NA),
        errors="coerce"
    )

    df["CATEGORY"] = category
    df["SOURCE_FILE"] = source_file

    return df


def convert_2021_2025_table(raw, category, source_file):

    df = raw.iloc[2:, :11].copy()

    df.columns = [
        "STATE_NAME",
        "STATION_CLASSIFICATION",
        "STATION_LOCATION",
        "STATION_ID",
        "2021",
        "2022",
        "2023",
        "2024",
        "2025",
        "STATUS_2025"
    ]

    text_cols = [
        "STATE_NAME",
        "STATION_CLASSIFICATION",
        "STATION_LOCATION",
        "STATION_ID"
    ]

    for col in text_cols:
        df[col] = (
            df[col]
            .astype("string")
            .str.replace("\n", " ", regex=False)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

    df["STATE_NAME"] = df["STATE_NAME"].replace(
        ["", "None", "<NA>"], pd.NA
    )

    df["STATE_NAME"] = df["STATE_NAME"].ffill()

    df = df.melt(
        id_vars=[
            "STATE_NAME",
            "STATION_CLASSIFICATION",
            "STATION_LOCATION",
            "STATION_ID"
        ],
        value_vars=[
            "2021",
            "2022",
            "2023",
            "2024",
            "2025"
        ],
        var_name="YEAR",
        value_name="MWQI"
    )

    df["YEAR"] = df["YEAR"].astype(int)

    df["MWQI"] = pd.to_numeric(
        df["MWQI"].replace("-", pd.NA),
        errors="coerce"
    )

    df["CATEGORY"] = category
    df["SOURCE_FILE"] = source_file

    return df

In [ ]:
pdf_paths = [
    "/content/mqims 2013-2015.pdf",
    "/content/mqims 2016-2020.pdf",
    "/content/mqims 2021-2025.pdf"
]

all_tables = []

for pdf_path in pdf_paths:

    print("\n" + "=" * 80)
    print(f"PROCESSING: {pdf_path}")
    print("=" * 80)

    tables = extract_mwqi_tables(pdf_path)
    all_tables.extend(tables)

print("\nTotal valid MWQI tables:", len(all_tables))

================================================================================
PROCESSING: /content/mqims 2013-2015.pdf
================================================================================

Scanning: mqims 2013-2015.pdf
✓ Page 2: Marine Water Quality Status for Coastal
  ✗ Skipping table 0 (not a station MWQI table)
✓ Page 6: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 18 station rows
✓ Page 7: Marine Water Quality Status for Coastal
  ✗ Skipping table 0 (not a station MWQI table)
  ✓ Extracted table 1: 27 station rows
✓ Page 8: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 27 station rows
✓ Page 9: Marine Water Quality Status for Coastal
  ✗ Skipping table 0 (not a station MWQI table)
  ✓ Extracted table 1: 26 station rows
✓ Page 10: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 28 station rows
✓ Page 11: Marine Water Quality Status for Coastal
  ✗ Skipping table 0 (not a station MWQI table)
  ✓ Extracted table 1: 29 station rows
✓ Page 13: Marine Water Quality Status for Estuary
  ✗ Skipping table 0 (not a station MWQI table)
  ✓ Extracted table 1: 17 station rows
✓ Page 14: Marine Water Quality Status for Estuary
  ✓ Extracted table 0: 26 station rows
✓ Page 15: Marine Water Quality Status for Estuary
  ✗ Skipping table 0 (not a station MWQI table)
  ✓ Extracted table 1: 25 station rows
✓ Page 16: Marine Water Quality Status for Estuary
  ✓ Extracted table 0: 8 station rows
  ✗ Skipping table 1 (not a station MWQI table)
  ✗ Skipping table 2 (not a station MWQI table)
✓ Page 21: Marine Water Quality Status for Island
  ✗ Skipping table 0 (not a station MWQI table)
  ✗ Skipping table 1 (not a station MWQI table)
  ✗ Skipping table 2 (not a station MWQI table)
  ✗ Skipping table 3 (not a station MWQI table)
✓ Page 22: Marine Water Quality Status for Island
  ✓ Extracted table 0: 27 station rows
✓ Page 23: Marine Water Quality Status for Island
  ✗ Skipping table 0 (not a station MWQI table)
  ✓ Extracted table 1: 23 station rows
✓ Page 24: Marine Water Quality Status for Island
  ✓ Extracted table 0: 30 station rows
✓ Page 25: Marine Water Quality Status for Island
  ✗ Skipping table 0 (not a station MWQI table)
  ✓ Extracted table 1: 10 station rows

================================================================================
PROCESSING: /content/mqims 2016-2020.pdf
================================================================================

Scanning: mqims 2016-2020.pdf
✓ Page 123: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 25 station rows
✓ Page 124: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 34 station rows
✓ Page 125: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 35 station rows
✓ Page 126: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 33 station rows
✓ Page 127: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 34 station rows
✓ Page 128: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 29 station rows
✓ Page 129: Marine Water Quality Status for Coastal
  ✗ Skipping table 0 (not a station MWQI table)
✓ Page 130: Marine Water Quality Status for Estuary
  ✓ Extracted table 0: 29 station rows
✓ Page 131: Marine Water Quality Status for Estuary
  ✓ Extracted table 0: 31 station rows
✓ Page 132: Marine Water Quality Status for Estuary
  ✓ Extracted table 0: 28 station rows
✓ Page 133: Marine Water Quality Status for Estuary
  ✗ Skipping table 0 (not a station MWQI table)
✓ Page 137: Marine Water Quality Status for Island
  ✓ Extracted table 0: 35 station rows
✓ Page 138: Marine Water Quality Status for Island
  ✓ Extracted table 0: 34 station rows
✓ Page 139: Marine Water Quality Status for Island
  ✓ Extracted table 0: 27 station rows
✓ Page 140: Marine Water Quality Status for Island
  ✗ Skipping table 0 (not a station MWQI table)

================================================================================
PROCESSING: /content/mqims 2021-2025.pdf
================================================================================

Scanning: mqims 2021-2025.pdf
✓ Page 6: Marine Water Quality Status for Island
✓ Page 183: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 18 station rows
✓ Page 184: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 28 station rows
✓ Page 185: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 28 station rows
✓ Page 186: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 29 station rows
✓ Page 187: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 27 station rows
✓ Page 188: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 29 station rows
✓ Page 189: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 24 station rows
✓ Page 190: Marine Water Quality Status for Coastal
  ✓ Extracted table 0: 5 station rows
  ✗ Skipping table 1 (not a station MWQI table)
✓ Page 191: Marine Water Quality Status for Estuary
  ✓ Extracted table 0: 13 station rows
✓ Page 192: Marine Water Quality Status for Estuary
  ✓ Extracted table 0: 26 station rows
✓ Page 193: Marine Water Quality Status for Estuary
  ✓ Extracted table 0: 24 station rows
✓ Page 194: Marine Water Quality Status for Estuary
  ✓ Extracted table 0: 22 station rows
✓ Page 195: Marine Water Quality Status for Island
  ✗ Skipping table 0 (not a station MWQI table)
  ✗ Skipping table 1 (not a station MWQI table)
✓ Page 199: Marine Water Quality Status for Island
  ✓ Extracted table 0: 38 station rows
✓ Page 200: Marine Water Quality Status for Island
  ✓ Extracted table 0: 33 station rows
✓ Page 201: Marine Water Quality Status for Island
  ✓ Extracted table 0: 24 station rows
✓ Page 202: Marine Water Quality Status for Island
  ✗ Skipping table 0 (not a station MWQI table)

Total valid MWQI tables: 41

In [ ]:
cleaned_tables = []

for raw in all_tables:

    source_file = raw["SOURCE_FILE"].iloc[0]
    category = raw["CATEGORY"].iloc[0]

    original = raw.drop(
        columns=[
            "CATEGORY",
            "PDF_PAGE",
            "TABLE_NUM",
            "SOURCE_FILE"
        ],
        errors="ignore"
    )

    if "2013-2015" in source_file:

        clean = convert_2013_2015_table(
            original,
            category,
            source_file
        )

    elif "2016-2020" in source_file:

        clean = convert_2016_2020_table(
            original,
            category,
            source_file
        )

    elif "2021-2025" in source_file:

        clean = convert_2021_2025_table(
            original,
            category,
            source_file
        )

    else:
        print("Unknown source:", source_file)
        continue

    cleaned_tables.append(clean)

In [ ]:
df_mwims = pd.concat(
    cleaned_tables,
    ignore_index=True
)

/tmp/ipykernel_3933/1574785541.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_mwims = pd.concat(

##Data Cleaning

In [ ]:
state_name_map = {
    "Negeri Sembilan": "N. Sembilan",
}

df_mwims["STATE_NAME"] = (
    df_mwims["STATE_NAME"]
    .replace(state_name_map)
    .str.strip()
)

In [ ]:
def classify_mwqi(x):

    if pd.isna(x):
        return pd.NA

    if 90 <= x <= 100:
        return "Excellent"
    elif 80 <= x < 90:
        return "Good"
    elif 50 <= x < 80:
        return "Moderate"
    elif 0 <= x < 50:
        return "Poor"

    return pd.NA


df_mwims["MWQI_RANGE"] = (
    df_mwims["MWQI"]
    .apply(classify_mwqi)
)

In [ ]:
# Clean placeholder station IDs again
df_mwims["STATION_ID"] = (
    df_mwims["STATION_ID"]
    .astype("string")
    .str.strip()
    .replace(
        ["", "-", "NA", "N/A", "None", "<NA>"],
        pd.NA
    )
)

In [ ]:
import re
import pandas as pd

def normalize_location(x):
    if pd.isna(x):
        return pd.NA

    x = str(x).upper().strip()

    # Important: longest first
    x = re.sub(r"\(III\)", "3", x)
    x = re.sub(r"\(II\)", "2", x)
    x = re.sub(r"\(I\)", "1", x)

    # Remove footnote symbols
    x = x.replace("*", "")

    # Normalize punctuation / spacing
    x = re.sub(r"[^A-Z0-9]+", " ", x)
    x = re.sub(r"\s+", " ", x).strip()

    return x

In [ ]:
df_mwims["LOCATION_KEY"] = (
    df_mwims["STATION_LOCATION"]
    .apply(normalize_location)
)

In [ ]:
bridge = (
    df_mwims[
        df_mwims["YEAR"].between(2016, 2020)
        & df_mwims["OLD_STATION_ID"].notna()
        & df_mwims["STATION_ID"].notna()
    ][
        [
            "STATE_NAME",
            "CATEGORY",
            "OLD_STATION_ID",
            "STATION_ID",
            "STATION_LOCATION",
            "LOCATION_KEY"
        ]
    ]
    .drop_duplicates()
)

In [ ]:
bridge_check = (
    bridge
    .groupby(
        [
            "STATE_NAME",
            "CATEGORY",
            "OLD_STATION_ID",
            "LOCATION_KEY"
        ]
    )["STATION_ID"]
    .nunique()
    .reset_index(name="N_NEW_IDS")
)

display(
    bridge_check[
        bridge_check["N_NEW_IDS"] > 1
    ]
)

Empty DataFrame
Columns: [STATE_NAME, CATEGORY, OLD_STATION_ID, LOCATION_KEY, N_NEW_IDS]
Index: []

In [ ]:
location_bridge = (
    bridge
    .drop_duplicates(
        [
            "STATE_NAME",
            "CATEGORY",
            "OLD_STATION_ID",
            "LOCATION_KEY"
        ]
    )
    .set_index(
        [
            "STATE_NAME",
            "CATEGORY",
            "OLD_STATION_ID",
            "LOCATION_KEY"
        ]
    )["STATION_ID"]
    .to_dict()
)

In [ ]:
for col in ["OLD_STATION_ID", "STATION_ID"]:
    df_mwims[col] = (
        df_mwims[col]
        .astype("string")
        .str.strip()
        .replace(
            ["", "-", "NA", "N/A", "None", "<NA>"],
            pd.NA
        )
    )

df_mwims["STATION_LOCATION"] = (
    df_mwims["STATION_LOCATION"]
    .astype("string")
    .str.replace("\n", " ", regex=False)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [ ]:
mask_2013_2015 = df_mwims["YEAR"].between(2013, 2015)

df_mwims.loc[
    mask_2013_2015,
    "STATION_ID"
] = pd.NA

In [ ]:
def map_historical_station(row):

    if not (2013 <= row["YEAR"] <= 2015):
        return row["STATION_ID"]

    if pd.isna(row["OLD_STATION_ID"]):
        return pd.NA

    key = (
        row["STATE_NAME"],
        row["CATEGORY"],
        row["OLD_STATION_ID"],
        row["LOCATION_KEY"]
    )

    return location_bridge.get(key, pd.NA)


df_mwims["STATION_ID"] = df_mwims.apply(
    map_historical_station,
    axis=1
)

In [ ]:
unresolved = (
    df_mwims[
        df_mwims["YEAR"].between(2013, 2015)
        & df_mwims["STATION_ID"].isna()
    ][
        [
            "STATE_NAME",
            "CATEGORY",
            "STATION_LOCATION",
            "OLD_STATION_ID"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        [
            "STATE_NAME",
            "CATEGORY",
            "STATION_LOCATION"
        ]
    )
)

print(
    "Stations still unresolved:",
    len(unresolved)
)

display(unresolved)

Stations still unresolved: 34

,STATE_NAME,CATEGORY,STATION_LOCATION,OLD_STATION_ID
160,Johor,Coastal,Jeti Tanjong Belungkor,1440963
537,Johor,Estuary,Kuala Sungai Kim-Kim,1439965
535,Johor,Estuary,Kuala Sungai Melayu,1437946
534,Johor,Estuary,Kuala Sungai Skudai,1437922
536,Johor,Estuary,Kuala Sungai Tebrau,1438943
698,Kedah,Island,Pantai Chenang,7KD08
702,Kedah,Island,Perak,7KP01
701,Kedah,Island,Segantang,7KR01
699,Kedah,Island,Tanjung Rhu,7KD09
700,Kedah,Island,Teluk Ewa,7KD10
941,Labuan,Island,Lubuk Temiang,7LD03
778,Melaka,Island,Undan (Point A),7MP03
779,Melaka,Island,Undan (Point B),7MP03
228,Pahang,Coastal,Pantai Batu Hitam,3833915 (A)
229,Pahang,Coastal,Pantai Batu Hitam,3833915 (B)
230,Pahang,Coastal,Pantai Berserah,3933941 (A)
231,Pahang,Coastal,Pantai Berserah,3933941 (B)
222,Pahang,Coastal,Pantai Cherating (Club Med),4133903 (A)
223,Pahang,Coastal,Pantai Cherating (Club Med),4133903 (B)
224,Pahang,Coastal,Pantai Cherating (Legend),4133942 (A)
225,Pahang,Coastal,Pantai Cherating (Legend),4133942 (B)
226,Pahang,Coastal,Pantai Muhibbah Balok,3933901 (A)
227,Pahang,Coastal,Pantai Muhibbah Balok,3933901 (B)
236,Pahang,Coastal,Pantai Sepat,3737915
232,Pahang,Coastal,Pantai Teluk Cempedak,3833910 (A)
233,Pahang,Coastal,Pantai Teluk Cempedak,3833910 (B)
234,Pahang,Coastal,Pantai Teluk Gelora,3833909 (A)
235,Pahang,Coastal,Pantai Teluk Gelora,3833909 (B)
793,Pahang,Island,Sepui,7CM08
788,Pahang,Island,Tioman (Teluk Salang),7CM01
9,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas I,5303932
10,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas II,5303933
11,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas III,5302939
847,Terengganu,Island,Redang (North),7TM06

In [ ]:
# Find whether a state/category/location uniquely corresponds
# to exactly one modern STATION_ID

location_mapping_check = (
    bridge
    .groupby(
        [
            "STATE_NAME",
            "CATEGORY",
            "LOCATION_KEY"
        ]
    )["STATION_ID"]
    .nunique()
    .reset_index(name="N_NEW_IDS")
)

# Only locations with exactly one modern ID are safe
safe_locations = location_mapping_check[
    location_mapping_check["N_NEW_IDS"] == 1
]

location_lookup = (
    bridge
    .merge(
        safe_locations[
            [
                "STATE_NAME",
                "CATEGORY",
                "LOCATION_KEY"
            ]
        ],
        on=[
            "STATE_NAME",
            "CATEGORY",
            "LOCATION_KEY"
        ],
        how="inner"
    )
    .drop_duplicates(
        [
            "STATE_NAME",
            "CATEGORY",
            "LOCATION_KEY"
        ]
    )
    .set_index(
        [
            "STATE_NAME",
            "CATEGORY",
            "LOCATION_KEY"
        ]
    )["STATION_ID"]
    .to_dict()
)

In [ ]:
def map_by_unique_location(row):

    # Don't touch later years
    if not (2013 <= row["YEAR"] <= 2015):
        return row["STATION_ID"]

    # Already resolved
    if pd.notna(row["STATION_ID"]):
        return row["STATION_ID"]

    key = (
        row["STATE_NAME"],
        row["CATEGORY"],
        row["LOCATION_KEY"]
    )

    return location_lookup.get(key, pd.NA)


df_mwims["STATION_ID"] = df_mwims.apply(
    map_by_unique_location,
    axis=1
)

In [ ]:
unresolved = (
    df_mwims[
        df_mwims["YEAR"].between(2013, 2015)
        & df_mwims["STATION_ID"].isna()
    ][
        [
            "STATE_NAME",
            "CATEGORY",
            "STATION_LOCATION",
            "OLD_STATION_ID"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        [
            "STATE_NAME",
            "CATEGORY",
            "STATION_LOCATION",
            "OLD_STATION_ID"
        ]
    )
)

print("Still unresolved:", len(unresolved))
display(unresolved)

Still unresolved: 25

,STATE_NAME,CATEGORY,STATION_LOCATION,OLD_STATION_ID
160,Johor,Coastal,Jeti Tanjong Belungkor,1440963
537,Johor,Estuary,Kuala Sungai Kim-Kim,1439965
535,Johor,Estuary,Kuala Sungai Melayu,1437946
534,Johor,Estuary,Kuala Sungai Skudai,1437922
536,Johor,Estuary,Kuala Sungai Tebrau,1438943
702,Kedah,Island,Perak,7KP01
941,Labuan,Island,Lubuk Temiang,7LD03
228,Pahang,Coastal,Pantai Batu Hitam,3833915 (A)
229,Pahang,Coastal,Pantai Batu Hitam,3833915 (B)
230,Pahang,Coastal,Pantai Berserah,3933941 (A)
231,Pahang,Coastal,Pantai Berserah,3933941 (B)
222,Pahang,Coastal,Pantai Cherating (Club Med),4133903 (A)
223,Pahang,Coastal,Pantai Cherating (Club Med),4133903 (B)
224,Pahang,Coastal,Pantai Cherating (Legend),4133942 (A)
225,Pahang,Coastal,Pantai Cherating (Legend),4133942 (B)
226,Pahang,Coastal,Pantai Muhibbah Balok,3933901 (A)
227,Pahang,Coastal,Pantai Muhibbah Balok,3933901 (B)
236,Pahang,Coastal,Pantai Sepat,3737915
232,Pahang,Coastal,Pantai Teluk Cempedak,3833910 (A)
233,Pahang,Coastal,Pantai Teluk Cempedak,3833910 (B)
234,Pahang,Coastal,Pantai Teluk Gelora,3833909 (A)
235,Pahang,Coastal,Pantai Teluk Gelora,3833909 (B)
9,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas I,5303932
10,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas II,5303933
11,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas III,5302939

In [ ]:
manual_mapping = {

    # -------------------------
    # PAHANG - confirmed bridge
    # -------------------------

    ("Pahang", "Coastal", "4133903 (A)", "Pantai Cherating (Club Med)"):
        "MMCC001",

    ("Pahang", "Coastal", "4133903 (B)", "Pantai Cherating (Club Med)"):
        "MMCC002",

    ("Pahang", "Coastal", "4133942 (A)", "Pantai Cherating (Legend)"):
        "MMCC003",

    ("Pahang", "Coastal", "4133942 (B)", "Pantai Cherating (Legend)"):
        "MMCC004",

    ("Pahang", "Coastal", "3933901 (A)", "Pantai Muhibbah Balok"):
        "MMCC005",

    ("Pahang", "Coastal", "3933901 (B)", "Pantai Muhibbah Balok"):
        "MMCC006",

    ("Pahang", "Coastal", "3833915 (A)", "Pantai Batu Hitam"):
        "MMCC007",

    ("Pahang", "Coastal", "3833915 (B)", "Pantai Batu Hitam"):
        "MMCC008",

    ("Pahang", "Coastal", "3933941 (A)", "Pantai Berserah"):
        "MMCC009",

    ("Pahang", "Coastal", "3933941 (B)", "Pantai Berserah"):
        "MMCC010",

    ("Pahang", "Coastal", "3833910 (A)", "Pantai Teluk Cempedak"):
        "MMCC011",

    ("Pahang", "Coastal", "3833910 (B)", "Pantai Teluk Cempedak"):
        "MMCC012",

    ("Pahang", "Coastal", "3833909 (A)", "Pantai Teluk Gelora"):
        "MMCC013",

    ("Pahang", "Coastal", "3833909 (B)", "Pantai Teluk Gelora"):
        "MMCC014",

    ("Pahang", "Coastal", "3737915", "Pantai Sepat"):
        "MMCC015",

    # -------------------------
    # PULAU PINANG
    # -------------------------

    ("Pulau Pinang", "Coastal", "5303932",
     "Kawasan Perindustrian Bayan Lepas I"):
        "MMPC002",

    # -------------------------
    # LABUAN
    # -------------------------

    ("Labuan", "Island", "7LD03", "Lubuk Temiang"):
        "MMLD003",
}

In [ ]:
pulau_perak_mask = (
    (df_mwims["STATE_NAME"] == "Kedah")
    & (df_mwims["CATEGORY"] == "Island")
    & (
        (df_mwims["OLD_STATION_ID"] == "7KP01")
        | (df_mwims["STATION_ID"] == "MMRP001")
        | (df_mwims["STATION_LOCATION"].isin(["Perak", "Pulau Perak"]))
    )
)

df_mwims.loc[pulau_perak_mask, "STATION_ID"] = "MMKP004"

In [ ]:
def apply_manual_mapping(row):

    if pd.notna(row["STATION_ID"]):
        return row["STATION_ID"]

    key = (
        row["STATE_NAME"],
        row["CATEGORY"],
        row["OLD_STATION_ID"],
        row["STATION_LOCATION"]
    )

    return manual_mapping.get(key, pd.NA)


df_mwims["STATION_ID"] = df_mwims.apply(
    apply_manual_mapping,
    axis=1
)

In [ ]:
unresolved = (
    df_mwims[
        df_mwims["YEAR"].between(2013, 2015)
        & df_mwims["STATION_ID"].isna()
    ][
        [
            "STATE_NAME",
            "CATEGORY",
            "STATION_LOCATION",
            "OLD_STATION_ID"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        [
            "STATE_NAME",
            "CATEGORY",
            "STATION_LOCATION",
            "OLD_STATION_ID"
        ]
    )
)

print("Still unresolved:", len(unresolved))
display(unresolved)

Still unresolved: 7

,STATE_NAME,CATEGORY,STATION_LOCATION,OLD_STATION_ID
160,Johor,Coastal,Jeti Tanjong Belungkor,1440963
537,Johor,Estuary,Kuala Sungai Kim-Kim,1439965
535,Johor,Estuary,Kuala Sungai Melayu,1437946
534,Johor,Estuary,Kuala Sungai Skudai,1437922
536,Johor,Estuary,Kuala Sungai Tebrau,1438943
10,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas II,5303933
11,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas III,5302939

In [ ]:
historical_manual = {
    ("Johor", "Coastal", "1440963", "Jeti Tanjong Belungkor"):
        "HIST_1440963_JETI_TANJONG_BELUNGKOR",

    ("Johor", "Estuary", "1439965", "Kuala Sungai Kim-Kim"):
        "HIST_1439965_KUALA_SUNGAI_KIM_KIM",

    ("Pulau Pinang", "Coastal", "5303933",
     "Kawasan Perindustrian Bayan Lepas II"):
        "HIST_5303933_BAYAN_LEPAS_2",

    ("Pulau Pinang", "Coastal", "5302939",
     "Kawasan Perindustrian Bayan Lepas III"):
        "HIST_5302939_BAYAN_LEPAS_3",
}

In [ ]:
def apply_historical_mapping(row):

    if pd.notna(row["STATION_ID"]):
        return row["STATION_ID"]

    key = (
        row["STATE_NAME"],
        row["CATEGORY"],
        row["OLD_STATION_ID"],
        row["STATION_LOCATION"]
    )

    return historical_manual.get(key, pd.NA)


df_mwims["STATION_ID"] = df_mwims.apply(
    apply_historical_mapping,
    axis=1
)

In [ ]:
unresolved = (
    df_mwims[
        df_mwims["YEAR"].between(2013, 2015)
        & df_mwims["STATION_ID"].isna()
    ][
        [
            "STATE_NAME",
            "CATEGORY",
            "STATION_LOCATION",
            "OLD_STATION_ID"
        ]
    ]
    .drop_duplicates()
)

print("2013-2015 unresolved:", len(unresolved))
display(unresolved)

2013-2015 unresolved: 3

    STATE_NAME CATEGORY     STATION_LOCATION OLD_STATION_ID
534      Johor  Estuary  Kuala Sungai Skudai        1437922
535      Johor  Estuary  Kuala Sungai Melayu        1437946
536      Johor  Estuary  Kuala Sungai Tebrau        1438943

In [ ]:
missing_ids = (
    df_mwims[
        df_mwims["STATION_ID"].isna()
    ][
        [
            "STATE_NAME",
            "CATEGORY",
            "STATION_LOCATION",
            "OLD_STATION_ID",
            "YEAR",
            "MWQI"
        ]
    ]
)

print("Rows with missing STATION_ID:", len(missing_ids))

display(
    missing_ids.sort_values(
        ["STATE_NAME", "CATEGORY", "STATION_LOCATION", "YEAR"]
    )
)

Rows with missing STATION_ID: 39

,STATE_NAME,CATEGORY,STATION_LOCATION,OLD_STATION_ID,YEAR,MWQI
535,Johor,Estuary,Kuala Sungai Melayu,1437946,2013,83.38
561,Johor,Estuary,Kuala Sungai Melayu,1437946,2014,82.71
587,Johor,Estuary,Kuala Sungai Melayu,1437946,2015,88.96
2068,Johor,Estuary,Kuala Sungai Melayu,1437946,2016,58.00
2099,Johor,Estuary,Kuala Sungai Melayu,1437946,2017,63.00
2130,Johor,Estuary,Kuala Sungai Melayu,1437946,2018,NaN
2161,Johor,Estuary,Kuala Sungai Melayu,1437946,2019,NaN
2192,Johor,Estuary,Kuala Sungai Melayu,1437946,2020,NaN
534,Johor,Estuary,Kuala Sungai Skudai,1437922,2013,66.47
560,Johor,Estuary,Kuala Sungai Skudai,1437922,2014,64.21
586,Johor,Estuary,Kuala Sungai Skudai,1437922,2015,87.73
2069,Johor,Estuary,Kuala Sungai Skudai,1437922,2016,65.00
2100,Johor,Estuary,Kuala Sungai Skudai,1437922,2017,40.00
2131,Johor,Estuary,Kuala Sungai Skudai,1437922,2018,NaN
2162,Johor,Estuary,Kuala Sungai Skudai,1437922,2019,NaN
2193,Johor,Estuary,Kuala Sungai Skudai,1437922,2020,NaN
536,Johor,Estuary,Kuala Sungai Tebrau,1438943,2013,59.89
562,Johor,Estuary,Kuala Sungai Tebrau,1438943,2014,51.23
588,Johor,Estuary,Kuala Sungai Tebrau,1438943,2015,84.41
2070,Johor,Estuary,Kuala Sungai Tebrau,1438943,2016,56.00
2101,Johor,Estuary,Kuala Sungai Tebrau,1438943,2017,62.00
2132,Johor,Estuary,Kuala Sungai Tebrau,1438943,2018,NaN
2163,Johor,Estuary,Kuala Sungai Tebrau,1438943,2019,NaN
2194,Johor,Estuary,Kuala Sungai Tebrau,1438943,2020,NaN
2364,Kedah,Island,Lembu**,7KM05,2016,71.00
2399,Kedah,Island,Lembu**,7KM05,2017,NaN
2434,Kedah,Island,Lembu**,7KM05,2018,NaN
2469,Kedah,Island,Lembu**,7KM05,2019,NaN
2504,Kedah,Island,Lembu**,7KM05,2020,NaN
974,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas 2**,5303933,2016,NaN
999,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas 2**,5303933,2017,NaN
1024,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas 2**,5303933,2018,NaN
1049,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas 2**,5303933,2019,NaN
1074,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas 2**,5303933,2020,NaN
975,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas 3**,5302939,2016,50.00
1000,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas 3**,5302939,2017,NaN
1025,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas 3**,5302939,2018,NaN
1050,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas 3**,5302939,2019,NaN
1075,Pulau Pinang,Coastal,Kawasan Perindustrian Bayan Lepas 3**,5302939,2020,NaN

In [ ]:
historical_lookup = (
    df_mwims[
        df_mwims["STATION_ID"]
        .astype("string")
        .str.startswith("HIST_", na=False)
        & df_mwims["OLD_STATION_ID"].notna()
    ][
        [
            "STATE_NAME",
            "CATEGORY",
            "OLD_STATION_ID",
            "STATION_ID"
        ]
    ]
    .drop_duplicates()
)

In [ ]:
hist_check = (
    historical_lookup
    .groupby(
        [
            "STATE_NAME",
            "CATEGORY",
            "OLD_STATION_ID"
        ]
    )["STATION_ID"]
    .nunique()
    .reset_index(name="N_HIST_IDS")
)

display(
    hist_check[
        hist_check["N_HIST_IDS"] > 1
    ]
)

Empty DataFrame
Columns: [STATE_NAME, CATEGORY, OLD_STATION_ID, N_HIST_IDS]
Index: []

In [ ]:
hist_id_lookup = (
    historical_lookup
    .drop_duplicates(
        [
            "STATE_NAME",
            "CATEGORY",
            "OLD_STATION_ID"
        ]
    )
    .set_index(
        [
            "STATE_NAME",
            "CATEGORY",
            "OLD_STATION_ID"
        ]
    )["STATION_ID"]
    .to_dict()
)

In [ ]:
def fill_existing_historical_id(row):

    if pd.notna(row["STATION_ID"]):
        return row["STATION_ID"]

    if pd.isna(row["OLD_STATION_ID"]):
        return pd.NA

    key = (
        row["STATE_NAME"],
        row["CATEGORY"],
        row["OLD_STATION_ID"]
    )

    return hist_id_lookup.get(key, pd.NA)


df_mwims["STATION_ID"] = df_mwims.apply(
    fill_existing_historical_id,
    axis=1
)

In [ ]:
print(
    "Remaining missing IDs:",
    df_mwims["STATION_ID"].isna().sum()
)

Remaining missing IDs: 29

In [ ]:
df_mwims["STATION_ID_TYPE"] = "MODERN"

df_mwims.loc[
    df_mwims["STATION_ID"]
    .astype("string")
    .str.startswith("HIST_", na=False),
    "STATION_ID_TYPE"
] = "LEGACY"

In [ ]:
print(df_mwims["STATION_ID_TYPE"].value_counts())

STATION_ID_TYPE
MODERN    4651
LEGACY      22
Name: count, dtype: int64

In [ ]:
duplicate_station_year = (
    df_mwims[
        df_mwims.duplicated(
            [
                "STATE_NAME",
                "CATEGORY",
                "STATION_ID",
                "YEAR"
            ],
            keep=False
        )
    ]
)

print(
    "Duplicate station-year rows:",
    len(duplicate_station_year)
)

display(
    duplicate_station_year.sort_values(
        [
            "STATE_NAME",
            "CATEGORY",
            "STATION_ID",
            "YEAR"
        ]
    )
)

Duplicate station-year rows: 24

,STATE_NAME,STATION_CLASSIFICATION,STATION_LOCATION,OLD_STATION_ID,STATION_ID,YEAR,MWQI,CATEGORY,SOURCE_FILE,MWQI_RANGE,LOCATION_KEY,STATION_ID_TYPE
534,Johor,<NA>,Kuala Sungai Skudai,1437922,<NA>,2013,66.47,Estuary,mqims 2013-2015.pdf,Moderate,KUALA SUNGAI SKUDAI,MODERN
535,Johor,<NA>,Kuala Sungai Melayu,1437946,<NA>,2013,83.38,Estuary,mqims 2013-2015.pdf,Good,KUALA SUNGAI MELAYU,MODERN
536,Johor,<NA>,Kuala Sungai Tebrau,1438943,<NA>,2013,59.89,Estuary,mqims 2013-2015.pdf,Moderate,KUALA SUNGAI TEBRAU,MODERN
560,Johor,<NA>,Kuala Sungai Skudai,1437922,<NA>,2014,64.21,Estuary,mqims 2013-2015.pdf,Moderate,KUALA SUNGAI SKUDAI,MODERN
561,Johor,<NA>,Kuala Sungai Melayu,1437946,<NA>,2014,82.71,Estuary,mqims 2013-2015.pdf,Good,KUALA SUNGAI MELAYU,MODERN
562,Johor,<NA>,Kuala Sungai Tebrau,1438943,<NA>,2014,51.23,Estuary,mqims 2013-2015.pdf,Moderate,KUALA SUNGAI TEBRAU,MODERN
586,Johor,<NA>,Kuala Sungai Skudai,1437922,<NA>,2015,87.73,Estuary,mqims 2013-2015.pdf,Good,KUALA SUNGAI SKUDAI,MODERN
587,Johor,<NA>,Kuala Sungai Melayu,1437946,<NA>,2015,88.96,Estuary,mqims 2013-2015.pdf,Good,KUALA SUNGAI MELAYU,MODERN
588,Johor,<NA>,Kuala Sungai Tebrau,1438943,<NA>,2015,84.41,Estuary,mqims 2013-2015.pdf,Good,KUALA SUNGAI TEBRAU,MODERN
2068,Johor,Muara Sungai / Estuary,Kuala Sungai Melayu,1437946,<NA>,2016,58.00,Estuary,mqims 2016-2020.pdf,Moderate,KUALA SUNGAI MELAYU,MODERN
2069,Johor,<NA>,Kuala Sungai Skudai,1437922,<NA>,2016,65.00,Estuary,mqims 2016-2020.pdf,Moderate,KUALA SUNGAI SKUDAI,MODERN
2070,Johor,<NA>,Kuala Sungai Tebrau,1438943,<NA>,2016,56.00,Estuary,mqims 2016-2020.pdf,Moderate,KUALA SUNGAI TEBRAU,MODERN
2099,Johor,Muara Sungai / Estuary,Kuala Sungai Melayu,1437946,<NA>,2017,63.00,Estuary,mqims 2016-2020.pdf,Moderate,KUALA SUNGAI MELAYU,MODERN
2100,Johor,<NA>,Kuala Sungai Skudai,1437922,<NA>,2017,40.00,Estuary,mqims 2016-2020.pdf,Poor,KUALA SUNGAI SKUDAI,MODERN
2101,Johor,<NA>,Kuala Sungai Tebrau,1438943,<NA>,2017,62.00,Estuary,mqims 2016-2020.pdf,Moderate,KUALA SUNGAI TEBRAU,MODERN
2130,Johor,Muara Sungai / Estuary,Kuala Sungai Melayu,1437946,<NA>,2018,NaN,Estuary,mqims 2016-2020.pdf,<NA>,KUALA SUNGAI MELAYU,MODERN
2131,Johor,<NA>,Kuala Sungai Skudai,1437922,<NA>,2018,NaN,Estuary,mqims 2016-2020.pdf,<NA>,KUALA SUNGAI SKUDAI,MODERN
2132,Johor,<NA>,Kuala Sungai Tebrau,1438943,<NA>,2018,NaN,Estuary,mqims 2016-2020.pdf,<NA>,KUALA SUNGAI TEBRAU,MODERN
2161,Johor,Muara Sungai / Estuary,Kuala Sungai Melayu,1437946,<NA>,2019,NaN,Estuary,mqims 2016-2020.pdf,<NA>,KUALA SUNGAI MELAYU,MODERN
2162,Johor,<NA>,Kuala Sungai Skudai,1437922,<NA>,2019,NaN,Estuary,mqims 2016-2020.pdf,<NA>,KUALA SUNGAI SKUDAI,MODERN
2163,Johor,<NA>,Kuala Sungai Tebrau,1438943,<NA>,2019,NaN,Estuary,mqims 2016-2020.pdf,<NA>,KUALA SUNGAI TEBRAU,MODERN
2192,Johor,Muara Sungai / Estuary,Kuala Sungai Melayu,1437946,<NA>,2020,NaN,Estuary,mqims 2016-2020.pdf,<NA>,KUALA SUNGAI MELAYU,MODERN
2193,Johor,<NA>,Kuala Sungai Skudai,1437922,<NA>,2020,NaN,Estuary,mqims 2016-2020.pdf,<NA>,KUALA SUNGAI SKUDAI,MODERN
2194,Johor,<NA>,Kuala Sungai Tebrau,1438943,<NA>,2020,NaN,Estuary,mqims 2016-2020.pdf,<NA>,KUALA SUNGAI TEBRAU,MODERN

In [ ]:
missing = (
    df_mwims[
        df_mwims["STATION_ID"].isna()
    ][
        [
            "STATE_NAME",
            "CATEGORY",
            "STATION_LOCATION",
            "OLD_STATION_ID"
        ]
    ]
    .drop_duplicates()
)

print("Stations without modern ID:", len(missing))
display(missing)

Stations without modern ID: 4

     STATE_NAME CATEGORY     STATION_LOCATION OLD_STATION_ID
534       Johor  Estuary  Kuala Sungai Skudai        1437922
535       Johor  Estuary  Kuala Sungai Melayu        1437946
536       Johor  Estuary  Kuala Sungai Tebrau        1438943
2364      Kedah   Island              Lembu**          7KM05

In [ ]:
mask_historical = (
    df_mwims["STATION_ID"].isna()
    & df_mwims["OLD_STATION_ID"].notna()
)

df_mwims.loc[
    mask_historical,
    "STATION_ID"
] = (
    "HIST_"
    + df_mwims.loc[
        mask_historical,
        "OLD_STATION_ID"
    ].astype("string")
)

In [ ]:
df_mwims["STATION_ID_TYPE"] = "MODERN"

df_mwims.loc[
    df_mwims["STATION_ID"]
    .astype("string")
    .str.startswith("HIST_", na=False),
    "STATION_ID_TYPE"
] = "LEGACY"

In [ ]:
print(
    df_mwims["STATION_ID_TYPE"].value_counts()
)

STATION_ID_TYPE
MODERN    4622
LEGACY      51
Name: count, dtype: int64

In [ ]:
duplicate_station_year = df_mwims[
    df_mwims.duplicated(
        [
            "STATE_NAME",
            "CATEGORY",
            "STATION_ID",
            "YEAR"
        ],
        keep=False
    )
]

print(
    "Duplicate station-year rows:",
    len(duplicate_station_year)
)

display(
    duplicate_station_year.sort_values(
        [
            "STATE_NAME",
            "CATEGORY",
            "STATION_ID",
            "YEAR"
        ]
    )
)

Duplicate station-year rows: 0

Empty DataFrame
Columns: [STATE_NAME, STATION_CLASSIFICATION, STATION_LOCATION, OLD_STATION_ID, STATION_ID, YEAR, MWQI, CATEGORY, SOURCE_FILE, MWQI_RANGE, LOCATION_KEY, STATION_ID_TYPE]
Index: []

In [ ]:
print(
    "Missing station IDs:",
    df_mwims["STATION_ID"].isna().sum()
)

print(
    "Duplicate station-years:",
    df_mwims.duplicated(
        [
            "STATE_NAME",
            "CATEGORY",
            "STATION_ID",
            "YEAR"
        ]
    ).sum()
)

Missing station IDs: 0
Duplicate station-years: 0

In [ ]:
df_mwims = df_mwims.drop(
    columns=["STATION_CLASSIFICATION", "OLD_STATION_ID", "LOCATION_KEY"],
    errors="ignore"
)

In [ ]:
df_mwims

,STATE_NAME,STATION_LOCATION,STATION_ID,YEAR,MWQI,CATEGORY,SOURCE_FILE,MWQI_RANGE,STATION_ID_TYPE
0,Kedah,Pantai Merdeka,MMKC001,2013,59.92,Coastal,mqims 2013-2015.pdf,Moderate,MODERN
1,Kedah,Langkawi Island Resort,MMKC002,2013,60.61,Coastal,mqims 2013-2015.pdf,Moderate,MODERN
2,Kedah,Pantai Kok,MMKC003,2013,69.04,Coastal,mqims 2013-2015.pdf,Moderate,MODERN
3,Kedah,Pantai Kuah,MMKC004,2013,62.02,Coastal,mqims 2013-2015.pdf,Moderate,MODERN
4,Kedah,Pantai Pasir Tengkorak,MMKC005,2013,84.28,Coastal,mqims 2013-2015.pdf,Good,MODERN
...,...,...,...,...,...,...,...,...,...
4668,W.P. Labuan,Lubuk Temiang,MMLD003,2025,83.00,Island,mqims 2021-2025.pdf,Good,MODERN
4669,W.P. Labuan,Ranca-Ranca,MMLD004,2025,78.00,Island,mqims 2021-2025.pdf,Moderate,MODERN
4670,W.P. Labuan,Kuraman,MMLM001,2025,87.00,Island,mqims 2021-2025.pdf,Good,MODERN
4671,W.P. Labuan,Rusukan Besar,MMLM002,2025,69.00,Island,mqims 2021-2025.pdf,Moderate,MODERN
4672,W.P. Labuan,Rusukan Kecil,MMLM003,2025,65.00,Island,mqims 2021-2025.pdf,Moderate,MODERN

In [ ]:
df_mwims[df_mwims["STATION_LOCATION"] == "Lembu**"]

,STATE_NAME,STATION_LOCATION,STATION_ID,YEAR,MWQI,CATEGORY,SOURCE_FILE,MWQI_RANGE,STATION_ID_TYPE
2364,Kedah,Lembu**,HIST_7KM05,2016,71.0,Island,mqims 2016-2020.pdf,Moderate,LEGACY
2399,Kedah,Lembu**,HIST_7KM05,2017,NaN,Island,mqims 2016-2020.pdf,<NA>,LEGACY
2434,Kedah,Lembu**,HIST_7KM05,2018,NaN,Island,mqims 2016-2020.pdf,<NA>,LEGACY
2469,Kedah,Lembu**,HIST_7KM05,2019,NaN,Island,mqims 2016-2020.pdf,<NA>,LEGACY
2504,Kedah,Lembu**,HIST_7KM05,2020,NaN,Island,mqims 2016-2020.pdf,<NA>,LEGACY

In [ ]:
df_mwims.to_csv("mwqi_master_csv", index=False)

In [ ]:
import requests
import json

url = "https://eqms.doe.gov.my/api3/publicportalmqims/mqimsstation"

r = requests.get(
    url,
    timeout=60,
    verify=False
)

print("Status:", r.status_code)
print("Content-Type:", r.headers.get("content-type"))

data = r.json()

print(type(data))

if isinstance(data, dict):
    print("Keys:", data.keys())

print(json.dumps(data, indent=2)[:5000])

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'eqms.doe.gov.my'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Status: 200
Content-Type: application/json; charset=utf-8
<class 'list'>
[
  {
    "ID": 138,
    "STATE_ID": 8,
    "REGION_ID": 1,
    "STATION_STATUS": 1,
    "CLASS": "1/R",
    "STATION_ID_OLD": "4205908\u00a0",
    "STATION_ID": "MMAC001",
    "STATION_LOCATION": "PANTAI PASIR BOGAK",
    "STATE_NAME": "Perak",
    "CATEGORY": "Coastal",
    "CLASSIFICATION": "",
    "LONGITUDE": 100.551,
    "LATITUDE": 4.21176
  },
  {
    "ID": 139,
    "STATE_ID": 8,
    "REGION_ID": 1,
    "STATION_STATUS": 1,
    "CLASS": "1/R",
    "STATION_ID_OLD": "4205928\u00a0",
    "STATION_ID": "MMAC002",
    "STATION_LOCATION": "PANTAI TELUK DALAM",
    "STATE_NAME": "Perak",
    "CATEGORY": "Coastal",
    "CLASSIFICATION": "",
    "LONGITUDE": 100.556,
    "LATITUDE": 4.25
  },
  {
    "ID": 144,
    "STATE_ID": 8,
    "REGION_ID": 1,
    "STATION_STATUS": 1,
    "CLASS": "1/R",
    "STATION_ID_OLD": "4205923\u00a0",
    "STATION_ID": "MMAC003",
    "STATION_LOCATION": "PANTAI TELUK BATIK",
    "STATE_NAME": "Perak",
    "CATEGORY": "Coastal",
    "CLASSIFICATION": "",
    "LONGITUDE": 100.606,
    "LATITUDE": 4.18732
  },
  {
    "ID": 143,
    "STATE_ID": 8,
    "REGION_ID": 1,
    "STATION_STATUS": 1,
    "CLASS": "1/R",
    "STATION_ID_OLD": "4406927\u00a0",
    "STATION_ID": "MMAC004",
    "STATION_LOCATION": "PANTAI TANJUNG BATU",
    "STATE_NAME": "Perak",
    "CATEGORY": "Coastal",
    "CLASSIFICATION": "",
    "LONGITUDE": 100.595,
    "LATITUDE": 4.42659
  },
  {
    "ID": 145,
    "STATE_ID": 8,
    "REGION_ID": 1,
    "STATION_STATUS": 1,
    "CLASS": "3",
    "STATION_ID_OLD": "-",
    "STATION_ID": "MMAC005",
    "STATION_LOCATION": "TELUK RUBIAH",
    "STATE_NAME": "Perak",
    "CATEGORY": "Coastal",
    "CLASSIFICATION": "",
    "LONGITUDE": 100.622,
    "LATITUDE": 4.16016
  },
  {
    "ID": 142,
    "STATE_ID": 8,
    "REGION_ID": 1,
    "STATION_STATUS": 1,
    "CLASS": "2/R",
    "STATION_ID_OLD": "-",
    "STATION_ID": "MMAC006",
    "STATION_LOCATION": "PANTAI DAMAI LAUT",
    "STATE_NAME": "Perak",
    "CATEGORY": "Coastal",
    "CLASSIFICATION": "",
    "LONGITUDE": 100.589,
    "LATITUDE": 4.26412
  },
  {
    "ID": 141,
    "STATE_ID": 8,
    "REGION_ID": 1,
    "STATION_STATUS": 1,
    "CLASS": "2/R",
    "STATION_ID_OLD": "-",
    "STATION_ID": "MMAC007",
    "STATION_LOCATION": "TELUK SENANGIN",
    "STATE_NAME": "Perak",
    "CATEGORY": "Coastal",
    "CLASSIFICATION": "",
    "LONGITUDE": 100.582,
    "LATITUDE": 4.29387
  },
  {
    "ID": 140,
    "STATE_ID": 8,
    "REGION_ID": 1,
    "STATION_STATUS": 1,
    "CLASS": "1/R",
    "STATION_ID_OLD": "4305924\u00a0",
    "STATION_ID": "MMAC008",
    "STATION_LOCATION": "PANTAI PASIR PANJANG",
    "STATE_NAME": "Perak",
    "CATEGORY": "Coastal",
    "CLASSIFICATION": "",
    "LONGITUDE": 100.568,
    "LATITUDE": 4.34797
  },
  {
    "ID": 150,
    "STATE_ID": 8,
    "REGION_ID": 1,
    "STATION_STATUS": 1,
    "CLASS": "E1",
    "STATION_ID_OLD": "4205930\u00a0",
    "STATION_ID": "MMAE001",
    "STATION_LOCATION": "KUALA SUNGAI MANJUNG",
    "STATE_NAME": "Perak",
    "CATEGORY": "Estuary",
    "CLASSIFICATION": "",
    "LONGITUDE": 100.594,
    "LATITUDE": 4.24841
  },
  {
    "ID": 148,
    "STATE_ID": 8,
    "REGION_ID": 1,
    "STATION_STATUS": 1,
    "CLASS": "E1",
    "STATION_ID_OLD": "4906926\u00a0",
    "STATION_ID": "MMAE002",
    "STATION_LOCATION": "KUALA SUNGAI GULA",
    "STATE_NAME": "Perak",
    "CATEGORY": "Estuary",
    "CLASSIFICATION": "",
    "LONGITUDE": 100.467,
    "LATITUDE": 4.92269
  },
  {
    "ID": 147,
    "STATE_ID": 8,
    "REGION_ID": 1,
    "STATION_STATUS": 1,
    "CLASS": "E1",
    "STATION_ID_OLD": "4994919\u00a0",
    "STATION_ID": "MMAE003",
    "STATION_LOCATION": "KUALA SUNGAI KURAU",
    "STATE_NAME": "Perak",
    "CATEGORY": "Estuary",
    "CLASSIFICATION": "",
    "LONGITUDE": 100.415,
    "LATITUDE": 4.99481
  },
  {
    "ID": 146,
    "STATE_ID": 8,
    "REGION_ID": 1,
    "STATION_STATUS": 1,
    "CLASS": "E1",
    "STATION_ID_OLD": "5003921\u00a0",
    "STATION_ID": "MMAE004",
    "STATION_LOCATION": "KUALA SUNGAI TANJUNG PIANDANG",
    "STATE_NAME": "Perak",
    "CATEGORY": "Estuary",
    "CLASSIFICATION": "",
    "LONGITUDE": 100.374,
    "LATITUDE": 5.07661
  },
  {
    "ID": 149,
    "STATE_ID": 8,
    "REGION_ID": 1,
    "STATION_STATUS": 1,
    "CLASS": "E1",
    "STATION_ID_OLD": "4806925\u00a0",
    "STATION_ID": "MMAE005",
    "STATION_LOCATION": "KUALA SUNGAI SEPETANG",
    "STATE_NAME": "Perak",
    "CATEGORY": "Estuary",
    "CLASSIFICATION": "",
    "LONGITUDE": 100.588,
    "LATITUDE": 4.7756
  },
  {
    "ID": 151,
    "STATE_ID": 8,
    "REGION_ID": 1,
    "STATION_STATUS": 1,
    "CLASS": "E1",
    "STATION_ID_OLD": "4007901\u00a0",
    "STATION_ID": "MMAE006",
    "STATION_LOCATION": "KUALA SUNGAI PERAK",
    "STATE_NAME": "Perak",
    "CATEGORY": "Estuary",
    "CLASSIFICATION": "",
    "LONGITUDE": 100.756,
    "LATITUDE": 4.00002
  },
  {
    "ID": 155,
    "STATE_ID": 8,
    "REGION_ID": 1,
    "STATION_STATUS": 1,
    "CLASS": "1",
    "STATI

In [ ]:
import pandas as pd

# data = r.json()
station_coords = pd.DataFrame(data)

print("API rows:", len(station_coords))
print(station_coords.columns.tolist())

display(station_coords.head())

API rows: 369
['ID', 'STATE_ID', 'REGION_ID', 'STATION_STATUS', 'CLASS', 'STATION_ID_OLD', 'STATION_ID', 'STATION_LOCATION', 'STATE_NAME', 'CATEGORY', 'CLASSIFICATION', 'LONGITUDE', 'LATITUDE']

,ID,STATE_ID,REGION_ID,STATION_STATUS,CLASS,STATION_ID_OLD,STATION_ID,STATION_LOCATION,STATE_NAME,CATEGORY,CLASSIFICATION,LONGITUDE,LATITUDE
0,138,8,1,1,1/R,4205908,MMAC001,PANTAI PASIR BOGAK,Perak,Coastal,,100.551,4.21176
1,139,8,1,1,1/R,4205928,MMAC002,PANTAI TELUK DALAM,Perak,Coastal,,100.556,4.25000
2,144,8,1,1,1/R,4205923,MMAC003,PANTAI TELUK BATIK,Perak,Coastal,,100.606,4.18732
3,143,8,1,1,1/R,4406927,MMAC004,PANTAI TANJUNG BATU,Perak,Coastal,,100.595,4.42659
4,145,8,1,1,3,-,MMAC005,TELUK RUBIAH,Perak,Coastal,,100.622,4.16016

In [ ]:
# Clean IDs
station_coords["STATION_ID"] = (
    station_coords["STATION_ID"]
    .astype("string")
    .str.strip()
    .str.upper()
    .replace(["", "-", "NA", "N/A"], pd.NA)
)

station_coords["STATION_ID_OLD"] = (
    station_coords["STATION_ID_OLD"]
    .astype("string")
    .str.replace("\u00a0", "", regex=False)   # remove non-breaking spaces
    .str.strip()
    .replace(["", "-", "NA", "N/A"], pd.NA)
)

# Clean text
for col in ["STATE_NAME", "STATION_LOCATION", "CATEGORY"]:
    station_coords[col] = (
        station_coords[col]
        .astype("string")
        .str.strip()
    )

# Coordinates
station_coords["LATITUDE"] = pd.to_numeric(
    station_coords["LATITUDE"],
    errors="coerce"
)

station_coords["LONGITUDE"] = pd.to_numeric(
    station_coords["LONGITUDE"],
    errors="coerce"
)

# Match your MWQI state naming convention
station_coords["STATE_NAME"] = (
    station_coords["STATE_NAME"]
    .replace({
        "W.P. Labuan": "Labuan",
        "W.P Labuan": "Labuan",
        "N. Sembilan": "Negeri Sembilan"
    })
)

In [ ]:
station_reference = station_coords[
    [
        "ID",
        "STATION_ID",
        "STATION_ID_OLD",
        "STATION_LOCATION",
        "STATE_NAME",
        "CATEGORY",
        "STATION_STATUS",
        "CLASS",
        "LATITUDE",
        "LONGITUDE"
    ]
].copy()

In [ ]:
print("Station records:", len(station_reference))

print(
    "Missing modern IDs:",
    station_reference["STATION_ID"].isna().sum()
)

print(
    "Missing latitude:",
    station_reference["LATITUDE"].isna().sum()
)

print(
    "Missing longitude:",
    station_reference["LONGITUDE"].isna().sum()
)

print(
    "Duplicated modern station IDs:",
    station_reference["STATION_ID"]
    .duplicated(keep=False)
    .sum()
)

Station records: 369
Missing modern IDs: 0
Missing latitude: 0
Missing longitude: 0
Duplicated modern station IDs: 0

In [ ]:
invalid_coords = station_reference[
    station_reference["LATITUDE"].notna()
    & station_reference["LONGITUDE"].notna()
    & (
        ~station_reference["LATITUDE"].between(0, 8)
        | ~station_reference["LONGITUDE"].between(99, 120)
    )
]

print("Suspicious coordinates:", len(invalid_coords))

display(invalid_coords)

Suspicious coordinates: 1

,ID,STATION_ID,STATION_ID_OLD,STATION_LOCATION,STATE_NAME,CATEGORY,STATION_STATUS,CLASS,LATITUDE,LONGITUDE
284,159,MMKP004,<NA>,PERAK,Kedah,Island,1,1,5.68145,98.936

In [ ]:
mwqi_modern_ids = set(
    df_mwims.loc[
        df_mwims["STATION_ID_TYPE"] == "MODERN",
        "STATION_ID"
    ]
    .dropna()
    .astype("string")
    .str.strip()
)

api_ids = set(
    station_reference["STATION_ID"]
    .dropna()
)

print("Modern stations in MWQI:", len(mwqi_modern_ids))
print("Stations in MQIMS API:", len(api_ids))

print("\nMWQI modern IDs missing from API:")
print(mwqi_modern_ids - api_ids)

print("\nAPI IDs not in historical MWQI dataset:")
print(api_ids - mwqi_modern_ids)

Modern stations in MWQI: 368
Stations in MQIMS API: 369

MWQI modern IDs missing from API:
set()

API IDs not in historical MWQI dataset:
{'TEST001'}

In [ ]:
df_mwims_with_coords = df_mwims.merge(
    station_reference[
        [
            "STATION_ID",
            "LATITUDE",
            "LONGITUDE",
            "STATION_STATUS"
        ]
    ],
    on="STATION_ID",
    how="left",
    validate="many_to_one"
)

print("Before merge:", len(df_mwims))
print("After merge:", len(df_mwims_with_coords))

Before merge: 4673
After merge: 4673

In [ ]:
missing_coords = (
    master_with_coords[
        master_with_coords["LATITUDE"].isna()
        | master_with_coords["LONGITUDE"].isna()
    ][
        [
            "STATE_NAME",
            "CATEGORY",
            "STATION_LOCATION",
            "STATION_ID",
            "STATION_ID_TYPE"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        [
            "STATE_NAME",
            "CATEGORY",
            "STATION_LOCATION"
        ]
    )
)

print(
    "Distinct stations without coordinates:",
    len(missing_coords)
)

display(missing_coords)

NameError: name 'master_with_coords' is not defined

In [ ]:
import geopandas as gpd

mwims_stations = (
    df_mwims_with_coords[
        df_mwims_with_coords["LATITUDE"].notna()
        & df_mwims_with_coords["LONGITUDE"].notna()
    ][
        [
            "STATION_ID",
            "STATION_ID_TYPE",
            "STATE_NAME",
            "STATION_LOCATION",
            "CATEGORY",
            "STATION_STATUS",
            "LATITUDE",
            "LONGITUDE"
        ]
    ]
    .drop_duplicates(
        subset=["STATION_ID"]
    )
    .reset_index(drop=True)
)

mwims_stations = gpd.GeoDataFrame(
    mwims_stations,
    geometry=gpd.points_from_xy(
        mwims_stations["LONGITUDE"],
        mwims_stations["LATITUDE"]
    ),
    crs="EPSG:4326"
)

print("Spatial monitoring stations:", len(mwims_stations))

display(mwims_stations.head())

Spatial monitoring stations: 368

,STATION_ID,STATION_ID_TYPE,STATE_NAME,STATION_LOCATION,CATEGORY,STATION_STATUS,LATITUDE,LONGITUDE,geometry
0,MMKC001,MODERN,Kedah,Pantai Merdeka,Coastal,1.0,5.669760,100.369000,POINT (100.369 5.66976)
1,MMKC002,MODERN,Kedah,Langkawi Island Resort,Coastal,1.0,6.296690,99.861000,POINT (99.861 6.29669)
2,MMKC003,MODERN,Kedah,Pantai Kok,Coastal,1.0,6.366070,99.679100,POINT (99.6791 6.36607)
3,MMKC004,MODERN,Kedah,Pantai Kuah,Coastal,1.0,6.313553,99.851419,POINT (99.85142 6.31355)
4,MMKC005,MODERN,Kedah,Pantai Pasir Tengkorak,Coastal,1.0,6.431230,99.726100,POINT (99.7261 6.43123)

In [ ]:
mwims_stations.to_file(
    "/content/mwims_stations.geojson",
    driver="GeoJSON"
)

mwims_stations.to_file(
    "/content/mwims_stations.gpkg",
    layer="mwims_stations",
    driver="GPKG"
)

In [ ]:
import pandas as pd
import geopandas as gpd
import numpy as np

# Load
mwqi = pd.read_csv("/content/mwqi_master_csv")

stations = gpd.read_file(
    "/content/mwims_stations.gpkg"
)

# Attach coordinates to historical MWQI
mwqi_history = mwqi.merge(
    stations[
        [
            "STATION_ID",
            "LATITUDE",
            "LONGITUDE",
            "STATION_STATUS"
        ]
    ],
    on="STATION_ID",
    how="left",
    validate="many_to_one"
)

print("Original rows:", len(mwqi))
print("After merge:", len(mwqi_history))

Original rows: 4673
After merge: 4673

In [ ]:
print(
    mwqi_history[
        mwqi_history["STATION_ID_TYPE"] == "MODERN"
    ][["LATITUDE", "LONGITUDE"]]
    .isna()
    .any(axis=1)
    .sum()
)

0

In [ ]:
recent = mwqi_history[
    (mwqi_history["STATION_ID_TYPE"] == "MODERN")
    & (mwqi_history["YEAR"].between(2021, 2025))
].copy()

In [ ]:
trend = recent.pivot(
    index="STATION_ID",
    columns="YEAR",
    values="MWQI"
)

trend.columns = [
    f"MWQI_{year}"
    for year in trend.columns
]

trend = trend.reset_index()

display(trend.head())

  STATION_ID  MWQI_2021  MWQI_2022  MWQI_2023  MWQI_2024  MWQI_2025
0    MMAC001       95.0       94.0       92.0       95.0       95.0
1    MMAC002       94.0       92.0       93.0       95.0       91.0
2    MMAC003       78.0       89.0       92.0       95.0       95.0
3    MMAC004       93.0       94.0       93.0       96.0       92.0
4    MMAC005       90.0       81.0       88.0       96.0       95.0

In [ ]:
trend["CHANGE_1Y"] = (
    trend["MWQI_2025"]
    - trend["MWQI_2024"]
)

trend["CHANGE_5Y"] = (
    trend["MWQI_2025"]
    - trend["MWQI_2021"]
)

trend["MEAN_5Y"] = trend[
    [
        "MWQI_2021",
        "MWQI_2022",
        "MWQI_2023",
        "MWQI_2024",
        "MWQI_2025"
    ]
].mean(axis=1)

trend["MIN_5Y"] = trend[
    [
        "MWQI_2021",
        "MWQI_2022",
        "MWQI_2023",
        "MWQI_2024",
        "MWQI_2025"
    ]
].min(axis=1)

In [ ]:
years = np.array(
    [2021, 2022, 2023, 2024, 2025]
)

def calculate_slope(row):

    values = np.array([
        row["MWQI_2021"],
        row["MWQI_2022"],
        row["MWQI_2023"],
        row["MWQI_2024"],
        row["MWQI_2025"]
    ])

    return np.polyfit(
        years,
        values,
        1
    )[0]


trend["TREND_SLOPE_5Y"] = trend.apply(
    calculate_slope,
    axis=1
)

In [ ]:
trend["TREND_DIRECTION"] = np.select(
    [
        trend["TREND_SLOPE_5Y"] < -0.5,
        trend["TREND_SLOPE_5Y"] > 0.5
    ],
    [
        "Declining",
        "Improving"
    ],
    default="Stable"
)

In [ ]:
latest = (
    mwqi_history[
        (mwqi_history["YEAR"] == 2025)
        & (mwqi_history["STATION_ID_TYPE"] == "MODERN")
    ][
        [
            "STATION_ID",
            "STATE_NAME",
            "STATION_LOCATION",
            "CATEGORY",
            "MWQI",
            "MWQI_RANGE"
        ]
    ]
    .rename(
        columns={
            "MWQI": "LATEST_MWQI",
            "MWQI_RANGE": "LATEST_CLASS"
        }
    )
)

In [ ]:
station_summary = (
    stations
    .merge(
        latest,
        on="STATION_ID",
        how="left",
        validate="one_to_one",
        suffixes=("", "_MWQI")
    )
    .merge(
        trend,
        on="STATION_ID",
        how="left",
        validate="one_to_one"
    )
)

print("Dashboard stations:", len(station_summary))

Dashboard stations: 368

In [ ]:
station_summary["CURRENT_POOR"] = (
    station_summary["LATEST_CLASS"] == "Poor"
)

station_summary["CURRENT_MODERATE"] = (
    station_summary["LATEST_CLASS"] == "Moderate"
)

station_summary["DECLINING_5Y"] = (
    station_summary["TREND_DIRECTION"] == "Declining"
)

station_summary["DROP_5_PLUS"] = (
    station_summary["CHANGE_5Y"] <= -5
)

station_summary["DROP_10_PLUS"] = (
    station_summary["CHANGE_5Y"] <= -10
)

In [ ]:
# Tabular station summary
station_summary.drop(
    columns="geometry"
).to_csv(
    "/content/station_dashboard_summary.csv",
    index=False
)

# Spatial station summary
station_summary.to_file(
    "/content/station_dashboard_summary.geojson",
    driver="GeoJSON"
)

# Complete time series
mwqi_history.to_csv(
    "/content/mwqi_history_with_coords.csv",
    index=False
)

#MPA new

In [ ]:
import pandas as pd

mpa = pd.read_excel("Malaysia_MPA_Clean.xlsx")

print(mpa.shape)
print(mpa.columns.tolist())

display(mpa.head())

(51, 17)
['MPA_ID', 'MPA_Name', 'State', 'Latitude', 'Longitude', 'Designation', 'Designation_Type', 'Status', 'Established', 'Area_ha', 'Area_km2', 'Marine_Area_ha', 'IUCN_Category', 'No_Take', 'Has_Polygon', 'Source', 'Notes']

,MPA_ID,MPA_Name,State,Latitude,Longitude,Designation,Designation_Type,Status,Established,Area_ha,Area_km2,Marine_Area_ha,IUCN_Category,No_Take,Has_Polygon,Source,Notes
0,2003900,Pulau Aur Marine Park,Johor,2.455600,104.523831,Marine Park,National,Designated,1994-10-20,9745.0,97.45,0.0,II,Unknown,True,Coral Triangle Atlas (see notes),Boundary created by buffering 2nm from the co...
1,2003000,Pulau Babi Besar Marine Park,Johor,2.446666,103.986472,Marine Park,National,Designated,1994-10-20,8414.0,84.14,0.0,II,Unknown,True,Coral Triangle Atlas (see notes),Boundary created by buffering 2nm from the co...
2,2002800,Pulau Babi Hujong Marine Park,Johor,2.498046,103.954415,Marine Park,National,Designated,1994-10-20,5235.0,52.35,0.0,II,Unknown,False,Coral Triangle Atlas (see notes),Boundary created by buffering 2nm from the co...
3,2002900,Pulau Babi Tengah Marine Park,Johor,2.483528,103.963313,Marine Park,National,Designated,1994-10-20,5149.0,51.49,0.0,II,Unknown,False,Coral Triangle Atlas (see notes),Boundary created by buffering 2nm from the co...
4,2002600,Pulau Gual Marine Park,Johor,2.545041,103.972148,Marine Park,National,Designated,1994-10-20,4570.0,45.70,0.0,II,Unknown,False,Coral Triangle Atlas (see notes),Boundary created by buffering 2nm from the co...

In [ ]:
mpa["Latitude"] = pd.to_numeric(
    mpa["Latitude"],
    errors="coerce"
)

mpa["Longitude"] = pd.to_numeric(
    mpa["Longitude"],
    errors="coerce"
)

# Match your MQIMS/MWQI state naming
mpa["State"] = (
    mpa["State"]
    .astype("string")
    .str.strip()
    .replace({
        "W.P Labuan": "Labuan",
        "W.P. Labuan": "Labuan"
    })
)

In [ ]:
print(
    "Missing latitude:",
    mpa["Latitude"].isna().sum()
)

print(
    "Missing longitude:",
    mpa["Longitude"].isna().sum()
)

Missing latitude: 0
Missing longitude: 0

In [ ]:
invalid = mpa[
    ~mpa["Latitude"].between(0, 8)
    |
    ~mpa["Longitude"].between(99, 120)
]

display(invalid)

Empty DataFrame
Columns: [MPA_ID, MPA_Name, State, Latitude, Longitude, Designation, Designation_Type, Status, Established, Area_ha, Area_km2, Marine_Area_ha, IUCN_Category, No_Take, Has_Polygon, Source, Notes]
Index: []

In [ ]:
import geopandas as gpd

mpa_geo = gpd.GeoDataFrame(
    mpa,
    geometry=gpd.points_from_xy(
        mpa["Longitude"],
        mpa["Latitude"]
    ),
    crs="EPSG:4326"
)

In [ ]:
print(mpa_geo.crs)
print(mpa_geo.geometry.geom_type.value_counts())

display(
    mpa_geo[
        [
            "MPA_Name",
            "State",
            "Latitude",
            "Longitude",
            "geometry"
        ]
    ].head()
)

EPSG:4326
Point    51
Name: count, dtype: int64

,MPA_Name,State,Latitude,Longitude,geometry
0,Pulau Aur Marine Park,Johor,2.455600,104.523831,POINT (104.52383 2.4556)
1,Pulau Babi Besar Marine Park,Johor,2.446666,103.986472,POINT (103.98647 2.44667)
2,Pulau Babi Hujong Marine Park,Johor,2.498046,103.954415,POINT (103.95442 2.49805)
3,Pulau Babi Tengah Marine Park,Johor,2.483528,103.963313,POINT (103.96331 2.48353)
4,Pulau Gual Marine Park,Johor,2.545041,103.972148,POINT (103.97215 2.54504)

In [ ]:
mpa_geo["Established"] = pd.to_datetime(
    mpa_geo["Established"],
    errors="coerce"
)

mpa_geo["Established"] = (
    mpa_geo["Established"]
    .dt.strftime("%Y-%m-%d")
)

In [ ]:
mpa_geo = mpa_geo.where(
    pd.notnull(mpa_geo),
    None
)

In [ ]:
output_file = "mpa_points.geojson"

mpa_geo.to_file(
    output_file,
    driver="GeoJSON"
)

print(
    f"Saved {len(mpa_geo)} MPA points to {output_file}"
)

Saved 51 MPA points to mpa_points.geojson

In [ ]:
check = gpd.read_file(
    "mpa_points.geojson"
)

print("Rows:", len(check))
print("CRS:", check.crs)
print(
    "Geometry:",
    check.geometry.geom_type.value_counts()
)

display(check.head())

Rows: 51
CRS: EPSG:4326
Geometry: Point    51
Name: count, dtype: int64

,MPA_ID,MPA_Name,State,Latitude,Longitude,Designation,Designation_Type,Status,Established,Area_ha,Area_km2,Marine_Area_ha,IUCN_Category,No_Take,Has_Polygon,Source,Notes,geometry
0,2003900,Pulau Aur Marine Park,Johor,2.455600,104.523831,Marine Park,National,Designated,1994-10-20,9745.0,97.45,0.0,II,Unknown,True,Coral Triangle Atlas (see notes),Boundary created by buffering 2nm from the co...,POINT (104.52383 2.4556)
1,2003000,Pulau Babi Besar Marine Park,Johor,2.446666,103.986472,Marine Park,National,Designated,1994-10-20,8414.0,84.14,0.0,II,Unknown,True,Coral Triangle Atlas (see notes),Boundary created by buffering 2nm from the co...,POINT (103.98647 2.44667)
2,2002800,Pulau Babi Hujong Marine Park,Johor,2.498046,103.954415,Marine Park,National,Designated,1994-10-20,5235.0,52.35,0.0,II,Unknown,False,Coral Triangle Atlas (see notes),Boundary created by buffering 2nm from the co...,POINT (103.95442 2.49805)
3,2002900,Pulau Babi Tengah Marine Park,Johor,2.483528,103.963313,Marine Park,National,Designated,1994-10-20,5149.0,51.49,0.0,II,Unknown,False,Coral Triangle Atlas (see notes),Boundary created by buffering 2nm from the co...,POINT (103.96331 2.48353)
4,2002600,Pulau Gual Marine Park,Johor,2.545041,103.972148,Marine Park,National,Designated,1994-10-20,4570.0,45.70,0.0,II,Unknown,False,Coral Triangle Atlas (see notes),Boundary created by buffering 2nm from the co...,POINT (103.97215 2.54504)

In [ ]:
check = gpd.read_file(
    "mpa_points.geojson"
)

print("Rows:", len(check))
print("CRS:", check.crs)
print(
    "Geometry:",
    check.geometry.geom_type.value_counts()
)

display(check.head())

Rows: 51
CRS: EPSG:4326
Geometry: Point    51
Name: count, dtype: int64

,MPA_ID,MPA_Name,State,Latitude,Longitude,Designation,Designation_Type,Status,Established,Area_ha,Area_km2,Marine_Area_ha,IUCN_Category,No_Take,Has_Polygon,Source,Notes,geometry
0,2003900,Pulau Aur Marine Park,Johor,2.455600,104.523831,Marine Park,National,Designated,1994-10-20,9745.0,97.45,0.0,II,Unknown,True,Coral Triangle Atlas (see notes),Boundary created by buffering 2nm from the co...,POINT (104.52383 2.4556)
1,2003000,Pulau Babi Besar Marine Park,Johor,2.446666,103.986472,Marine Park,National,Designated,1994-10-20,8414.0,84.14,0.0,II,Unknown,True,Coral Triangle Atlas (see notes),Boundary created by buffering 2nm from the co...,POINT (103.98647 2.44667)
2,2002800,Pulau Babi Hujong Marine Park,Johor,2.498046,103.954415,Marine Park,National,Designated,1994-10-20,5235.0,52.35,0.0,II,Unknown,False,Coral Triangle Atlas (see notes),Boundary created by buffering 2nm from the co...,POINT (103.95442 2.49805)
3,2002900,Pulau Babi Tengah Marine Park,Johor,2.483528,103.963313,Marine Park,National,Designated,1994-10-20,5149.0,51.49,0.0,II,Unknown,False,Coral Triangle Atlas (see notes),Boundary created by buffering 2nm from the co...,POINT (103.96331 2.48353)
4,2002600,Pulau Gual Marine Park,Johor,2.545041,103.972148,Marine Park,National,Designated,1994-10-20,4570.0,45.70,0.0,II,Unknown,False,Coral Triangle Atlas (see notes),Boundary created by buffering 2nm from the co...,POINT (103.97215 2.54504)

# Data merging for website

In [ ]:
import geopandas as gpd
import pandas as pd
import numpy as np
from pyproj import Geod

stations = gpd.read_file(
    "station_dashboard_summary.geojson"
)

mpas = gpd.read_file(
    "mpa_points.geojson"
)

print("Stations:", len(stations))
print("MPAs:", len(mpas))

print(stations.crs)
print(mpas.crs)

Stations: 368
MPAs: 51
EPSG:4326
EPSG:4326

In [ ]:
geod = Geod(ellps="WGS84")

links = []

for _, station in stations.iterrows():

    station_lon = station.geometry.x
    station_lat = station.geometry.y

    best = None

    for _, mpa in mpas.iterrows():

        mpa_lon = mpa.geometry.x
        mpa_lat = mpa.geometry.y

        _, _, distance_m = geod.inv(
            station_lon,
            station_lat,
            mpa_lon,
            mpa_lat
        )

        distance_km = distance_m / 1000

        if best is None or distance_km < best["DISTANCE_KM"]:
            best = {
                "STATION_ID": station["STATION_ID"],
                "NEAREST_MPA_ID": mpa["MPA_ID"],
                "NEAREST_MPA_NAME": mpa["MPA_Name"],
                "NEAREST_MPA_STATE": mpa["State"],
                "NEAREST_MPA_DESIGNATION": mpa["Designation"],
                "DISTANCE_KM": distance_km
            }

    links.append(best)

In [ ]:
nearest_mpa = pd.DataFrame(links)

display(nearest_mpa.head())

,STATION_ID,NEAREST_MPA_ID,NEAREST_MPA_NAME,NEAREST_MPA_STATE,NEAREST_MPA_DESIGNATION,DISTANCE_KM
0,MMKC001,2001000,Pulau Lembu Marine Park,Kedah,Marine Park,56.392985
1,MMKC002,2000900,Pulau Segantang Marine Park,Kedah,Marine Park,29.161937
2,MMKC003,2000900,Pulau Segantang Marine Park,Kedah,Marine Park,45.298747
3,MMKC004,2000900,Pulau Segantang Marine Park,Kedah,Marine Park,31.243000
4,MMKC005,2000900,Pulau Segantang Marine Park,Kedah,Marine Park,48.569175

In [ ]:
nearest_mpa["DISTANCE_KM"].describe()

count    368.000000
mean      90.161629
std       82.460157
min        0.119149
25%       21.999076
50%       69.152698
75%      125.843390
max      308.733045
Name: DISTANCE_KM, dtype: float64

In [ ]:
stations_enriched = stations.merge(
    nearest_mpa,
    on="STATION_ID",
    how="left",
    validate="one_to_one"
)

print(len(stations_enriched))

368

In [ ]:
print(
    "Missing nearest MPA:",
    stations_enriched["NEAREST_MPA_ID"]
    .isna()
    .sum()
)

Missing nearest MPA: 0

In [ ]:
def proximity_band(distance):
    if pd.isna(distance):
        return "Unknown"
    elif distance <= 10:
        return "≤10 km"
    elif distance <= 25:
        return "10–25 km"
    elif distance <= 50:
        return "25–50 km"
    else:
        return ">50 km"

stations_enriched["MPA_DISTANCE_BAND"] = (
    stations_enriched["DISTANCE_KM"]
    .apply(proximity_band)
)

In [ ]:
stations_enriched.to_file(
    "station_dashboard_summary_enriched.geojson",
    driver="GeoJSON"
)

In [ ]:
check = gpd.read_file(
    "station_dashboard_summary_enriched.geojson"
)

print(check.shape)

display(
    check[
        [
            "STATION_ID",
            "LATEST_MWQI",
            "NEAREST_MPA_NAME",
            "DISTANCE_KM",
            "MPA_DISTANCE_BAND"
        ]
    ].head()
)

(368, 36)

,STATION_ID,LATEST_MWQI,NEAREST_MPA_NAME,DISTANCE_KM,MPA_DISTANCE_BAND
0,MMKC001,88.0,Pulau Lembu Marine Park,56.392985,>50 km
1,MMKC002,96.0,Pulau Segantang Marine Park,29.161937,25–50 km
2,MMKC003,96.0,Pulau Segantang Marine Park,45.298747,25–50 km
3,MMKC004,91.0,Pulau Segantang Marine Park,31.243000,25–50 km
4,MMKC005,95.0,Pulau Segantang Marine Park,48.569175,25–50 km